### ISSUE TITLE
TODO: Find out what faction the Ratchet inhabitants belonged to

### ISSUE THREAD

**Issue by mindphluxnet** [The-Alpha-Project/alpha-core#1010]
**Describe what needs to be implemented or enhanced**
Because it's not 673 and the DBC doesn't have a Ratchet faction.

Bonus if you can find out what faction Jorb (Lizzarik's Bodyguard) belonged to. Because 474 doesn't exist either ...

**Comment by Yushe** [comment]
They could be set to the Booty Bay faction since they both behave similarly.
