### ISSUE TITLE
Quest "Ineptitude + Chemicals = Fun" can't be completed

### ISSUE THREAD

**Issue by mindphluxnet** [The-Alpha-Project/alpha-core#1013]
**Describe the bug**
The quest "Ineptitude + Chemicals = Fun" (1073) cannot be completed as it exists now as one of the required items is not available to players.

Required items are: 

- 4x Minor Mana Potion
- 2x Elixir of Fortitude

While both items exist there's no way for players to create the Elixir of Fortitude as the recipe is not learned from the Alchemy trainer as it is in vanilla. Instead, the only way to learn it was [from a scroll which is marked as deprecated](https://db.thealphaproject.eu/index.php?action=show_item&id=2554&filter=fortitude&sort_order=name&pos=5&max=8) and doesn't drop from any source.

**Possible resolution**
There are two possible avenues of resolution:

- replace the Elixir of Fortitude with another item
- restore the Deprecated Recipe: Elixir of Fortitude item and add it to appropiate drop tables

Personally I prefer the latter as it makes sense. For one, we don't know if the recipe was indeed deprecated in 0.5.3 or if that tag was added later. It's perfectly plausible this was done when the recipe became a trainer recipe and the item did indeed drop in 0.5.3. Second, even though the alpha was still a long way from completion it just doesn't make sense to design a quest asking for a crafted item that was basically removed from the game. Even if an item wasn't finalized the quest designers added a placeholder to make the quest at least work.

The first avenue would not be Blizzlike. The quest remained the same in vanilla so it's very likely identical in 0.5.3. The Elixir of Fortitude - as it was back then - perfectly matches the level of the other required item and the request matches the objective asked by almost all of the "you have to find a player who can make this" quests.

**Suggestion**
- Restore item 2554 to "Recipe: Elixir of Fortitude"
- add it to all loot sources between level 10 and 20 at a chance of 0.02% with some select mobs dropping it at 0.03-0.1%

**Comment by Fluglow** [comment]
It looks like Elixir of Fortitude was later added as a higher level item, renaming the version we have to Minor Fortitude. For example, Elixir of Fortitude is listed [here](https://crawler.thealphaproject.eu/mnt/crawler/media/Database/Allakhazam/creatures-details-2004.txt) and [here](https://crawler.thealphaproject.eu/mnt/crawler/media/Website/wow.allakhazam.com/web.archive.org/web/20040819193111/http:/wow.allakhazam.com/db/skills.html%3Fline=171.html) as a 175 craft and dropping from 30+. However, it's listed as vendor recipe [here](https://crawler.thealphaproject.eu/mnt/crawler/media/Website/wowvault.ign.com/web.archive.org/web/20040815172140/http:/wowvault.ign.com/View.php%3Fview=Crafting.List.html) as a skill level 50 craft.

**Comment by mindphluxnet** [comment]
Hm, vendor recipe sounds plausible - all other quests involving crafting used trainer or vendor recipes - but now we don't know which vendor sold it ...
