### ISSUE TITLE
TODO: Update Theramore display_id

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#1016]
Theramore
========

We don't have any screenshots of this area showing the old models we should be using. 
Here is one way we could try to solve Theramore's shane cube

4973 Guard Lasister
--------------------

There are 2 other named guard using display_id 3138
There are  2 other named guard using display_id 3139

All 4 are located in Theramore.

For 0.5.3, Guard Lasister should probably use one of those.
3138 could fit, but no evidence.

![Capture d’écran_2023-03-22_03-19-35](https://user-images.githubusercontent.com/72315006/226915534-40866fd6-e432-41d2-a6e1-c7269fa122af.png)

![Capture d’écran_2023-03-22_03-19-09](https://user-images.githubusercontent.com/72315006/226915548-d5854171-1fc9-4429-92aa-b3e7a19f09bb.png)

5088 Falgran Hastil
-----------------
![Capture d’écran_2023-03-22_07-20-41](https://user-images.githubusercontent.com/72315006/226915902-a2b17e1f-7bf4-49fa-9300-8d0fd33352df.png)

do we have infos about why he is not spawned ?

5046 Lieutenant Caldwell
------------------
![Capture d’écran_2023-03-22_14-19-14](https://user-images.githubusercontent.com/72315006/226916915-4692efe9-c4a6-4f20-94a9-3ff6b85a8649.png)

do we have infos about why he is not spawned ?

General Guards
------------

Here is the display_id push of theramore linked guards, we can see the first set of guards : 2977 2978  2979 2980 (used for Theramore Guard)

![Capture d’écran_2023-03-22_04-13-26](https://user-images.githubusercontent.com/72315006/226915597-fc72d2a0-4866-4d6c-80c6-64ae0a1f0a4f.png)

Notice the second set : 2081 2082 2083 2084 (not used by any NPCs). 

There are 3 types of mobs that most likely use these sets : Theramore Lieutenant, Theramore Skirmisher, Theramore Practicing guards.
Vanilla will use variations of the Theramore Guard model for these 3  NPCs (face variation mostly)

![Capture d’écran_2023-03-22_02-25-09](https://user-images.githubusercontent.com/72315006/226915764-f81ced54-55e4-4a99-905d-d336dbcd3d68.png)
![skirmisher](https://user-images.githubusercontent.com/72315006/226915784-fa7e8e06-a3e9-4687-9ab2-ed56cd4a2bf8.jpg)

Since we cant know at this point, we could use : 

4947 Theramore Lieutenant : 2977 2978 2979 2980
4951 Theramore Practicing guard : 2081 2082 2083 2084
5044 Theramore Skirmisher : 2977 2978 2979 2980

We could do different combinaison too 

4947 Theramore Lieutenant : 2977 2978 2979 2980
4951 Theramore Practicing guard : 2081 2083 
5044 Theramore Skirmisher :  2082 2084

Here is probably the new models push (could be added in version 0.6), this could indicate that blizzard reworked this area at this time
That also means that only screenshots before 0.6 could confirm the right models .

![Capture d’écran_2023-03-22_02-44-09](https://user-images.githubusercontent.com/72315006/226915865-ae23a965-cb2a-4d07-b122-126085ea257b.png)

As we can see, there are mostly just variations of standard theramore guard, so we could decide to just use the first guard set and not the second :

4947 Theramore Lieutenant : 2977 2978 2979 2980
4951 Theramore Practicing guard : 2977 2978 2979 2980
5044 Theramore Skirmisher : 2977 2978 2979 2980

Normal NPCs
------------------

About all normal Npcs : food & drink , general goods, armorer, profession trainers, bartender...

Although the entries for most of these NPCS are very high, they probably all used old human models for 0.5.3
Besides some named NPC and guards, everybody in Theramore is missing display_id.

There are so many missing models that there wouldn't be enough unused human display_id in the entire set to apply to them.
There is probably no other way they could use models other than old human. 

Ofc It applies only for Human NPCs. Other races should use respective placeholder.

we could also notify than the bloodelf placeholder is used by Fiora Longears here (Bartender model seems not part of 0.5.3)
![197317784-bc5cffcb-361f-40c9-8c79-384fb3225bc4](https://user-images.githubusercontent.com/72315006/226917426-45d7d184-a942-4be0-9c9e-b6f971f89791.jpg)

We also know than Kenna Larnad is surely located in Theramore and use female dwarf placeholder (blizzlike)
![Capture d’écran_2023-03-22_14-22-22](https://user-images.githubusercontent.com/72315006/226917614-56a5b704-ce3b-4bfa-ba88-aaeb06d20b68.png)

We have some screenshot from other area showing old human placeholder used for bartender, blacksmith trainer, general vendors...
We could use them on theramore NPCs.

![](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/UNSORTED/www_worldofwar_net/articles_images_cgo-august2002.jpg)
![](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Cities/Stormwind/2003-06-30-10-31-12.jpg)
![](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Duskwood/Dancer_SS0410-03.jpg)
![](https://user-images.githubusercontent.com/72315006/220664065-2d0daf7d-031f-4645-b3a6-22b39c9574e4.JPG)
![image](https://user-images.githubusercontent.com/72315006/226918774-254c53fc-3bf8-40ee-8f70-c7573b09fde2.png)
![](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/UNSORTED/ign_alpha_beta/world-of-warcraft-20050519010523981-1131492.jpg)
![](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Elwynn%20Forest/31.jpg)
![](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Duskwood/U165P115T15D123778F238DT20040408140008.jpg)
![](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Stranglethorn%20Vale/18.jpg)
![](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Blasted%20Lands/quest_test_october_2003.png)
![](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Cities/Stormwind/Morgan%20Pestle.PNG)

**Comment by mindphluxnet** [comment]
Falgran Hastil: he has no spawn point because he is summoned by a quest_end_script ([Wowhead comment](https://www.wowhead.com/classic/npc=5088/falgran-hastil#comments)) 
Lieutenant Caldwell: same, he spawns during the quest [Questioning Reethe](http://classicdb.ch/?quest=1273)
