### ISSUE TITLE
TODO: Fix Wailing Caverns faction

### ISSUE THREAD

**Issue by mindphluxnet** [The-Alpha-Project/alpha-core#1019]
**Describe what needs to be implemented or enhanced**
Wailing Caverns creatures have faction 270 which doesn't exist. Should probably be just set to something hostile towards players?

**Comment by Yushe** [comment]
The only hostile NPCs within the Wailing Caverns have either ID 14 (Non-social Monsters) and ID 16 (Monsters).
I suggest that the creatures gets set to ID 14 and the humanoids get set to ID 16 within the Wailing Caverns.
