### ISSUE TITLE
TODO: Find remaining display_ids for Feralas

### ISSUE THREAD

**Issue by mindphluxnet** [The-Alpha-Project/alpha-core#1041]
**Describe what needs to be implemented or enhanced**
Feralas needs some display_id love too:

- -4491.134765625 -769.4718017578125 -37.24376678466797 1 - Rendow
- -4527.1767578125 -788.6441650390625 -41.991397857666016 1 - Falfindel Waywarder
- -4347.287109375 224.04266357421875 25.413349151611328 1 - Sage Palerunner
- -4347.41552734375 160.3411865234375 34.43212127685547 1 - Krueg Skullsplitter
- -5046.1650390625 1611.496826171875 68.76206970214844 1 - Bloodroar the Stalker

**Comment by geo-tp** [comment]
Same as #1035 for standard placeholders if we want to resolve them without evidence.
Models with evidence were already changed here https://github.com/The-Alpha-Project/alpha-core/pull/536


Alliance Camp
--------------

Probably NE placeholder

4048 Falfindel waywarder 2572
1695 Rendow 2575


Horde Camp
------------------
Probably orc/tauren placeholder

5390 Sage Palerunner 2578
4544 Krueg Skillsplitter 2576 OR 3508


Bloodroar the Stalker
-----------------
![Capture d’écran_2022-08-21_02-29-39](https://user-images.githubusercontent.com/72315006/227724449-4b2a81f5-2730-4633-86c1-3327fd97e279.png)

Seems to be the hulking set for feralas, we could use the highest scalled 3209

5346 Bloodroar the Stalker 3209
