### ISSUE TITLE
TODO: Find remaining display_ids for Teldrassil

### ISSUE THREAD

**Issue by mindphluxnet** [The-Alpha-Project/alpha-core#1044]
**Describe what needs to be implemented or enhanced**
There are some display_ids missing in Teldrassil and Darnassus:

- 9891.8134765625 992.0621948242188 1313.831787109375 1 - Danyla
- 9756.037109375 903.1170043945312 1295.517333984375 1 - Nyoma
- 10388.861328125 762.1815795898438 1319.810302734375 1 - Melithar Staghelm
- 9658.6513671875 2511.0771484375 1331.6341552734375 1 - Elyissa
- 10123.5927734375 2528.143310546875 1318.676025390625 1 - Jartsam

**Comment by geo-tp** [comment]
- [ ] Danyla
- [ ] Nyoma
- [ ]  Melithar Staghelm
- [x] Elyissa
- [ ]  Jartsam
