### ISSUE TITLE
TODO: Spawn Skeletal enforcers

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#1055]
**Describe what needs to be implemented or enhanced**

https://crawler.thealphaproject.eu/mnt/crawler/media/Website/warcry.com/Atlas-May-June-2004/WoW%20Warcry%20-%20Content%20-%20Atlas%20-%20Duskwood.php.html

As we can see on Duskwood map, Skeletal Enforcers should be spawned at Raven Hill

https://db.thealphaproject.eu/index.php?action=show_creature&id=725&filter=unused&sort_order=name&pos=99&max=133

**Expected end result**
725 Skeletal Enforcers should be spawned at Raven Hill near other Skeletal Fiend & Skeletal Horror
[UNUSED] should be remove from his name

**Comment by mindphluxnet** [comment]
Should they share spawns with Skeletal Fiend/Horror? The area is crowded already.

**Comment by geo-tp** [comment]
most likely
