### ISSUE TITLE
TODO:  Rework Loch Modan NPCs

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#1062]
Rework Loch Modan NPCs
==============

Brock Stoneseeker
-------------
![brock carto](https://user-images.githubusercontent.com/72315006/227774711-b594bd5f-a7c2-41f7-9bbc-80e61ad5ac9c.jpg)

1681 Brock subnme should be changed to "Cartography Trainer"

Karm Ironquill
---------------

1764 Karm Ironquill subname should be changed to "Cartography Supplies" (should we remove vendor list ?)

Noma Bluntnose
------------

https://crawler.thealphaproject.eu/mnt/crawler/media/Website/warcry.com/Atlas-May-June-2004/WoW%20Warcry%20-%20Content%20-%20Atlas%20-%20Loch%20Modan.php.html

no ignored spawn in DB

1879 Noma Bluntnose should be spawned in Thelsamar, most likely in same house as 1139 Magistrate Bluntnose.

Berte & Evalyn
------------------

![images_3726](https://user-images.githubusercontent.com/72315006/227774729-e98c3ee1-cfa9-4d11-bcd0-2a76777aa687.jpg)

As we can see here, they seems to have waypoints

![king_day03_1232](https://user-images.githubusercontent.com/72315006/227774743-749bf235-eb2b-4831-a289-1409ba276d06.JPG)
![king_day03_1230](https://user-images.githubusercontent.com/72315006/227774744-62872d68-6240-467c-8d11-bfdd848c3b3f.JPG)

Since Noma (npc above), Berte and Evalyn have linked entries, this text could be from Noma : 
![berte_evalyn](https://user-images.githubusercontent.com/72315006/227774769-21ba95a4-a153-4a80-a4da-dfd1697aeae2.png)

no ignored spawn in DB for them

1880 Berte, 1881 Evalyn should be spawned in Thelsamar
Subnames should be changed to "Needs Model"
Maybe they planned to have dwarf kid, that could explain this mention

Spider trainer
-----------
![WoWScrnShot_052304_090316](https://user-images.githubusercontent.com/72315006/227774777-bba5fd1d-1322-47af-a772-e21d6f60a043.jpg)

2872 Whaldek Darkbenk should be relocated to screenshot loc

(we could also try to determine Tamed Spider scale thanks to this img)

**Comment by mindphluxnet** [comment]
I must be blind but where is Whaldak Darkbenk in the screenshot?

**Comment by mindphluxnet** [comment]
This seems to be the broadcast text for the kids:

![image](https://user-images.githubusercontent.com/4683319/227932754-4805b7fd-b646-4da2-bfee-4e4a3d772e53.png)

Safe to assume the scripting went like this:

- kids run around in town
- Mona is calling for them, they run back to the house
- dialogue ensues
- they run off again

Question remains if this was tied to server time? Doesn't make much sense to say "it's barely dark" if it's not evening.

**Comment by geo-tp** [comment]
> I must be blind but where is Whaldak Darkbenk in the screenshot?

![227774777-bba5fd1d-1322-47af-a772-e21d6f60a043](https://user-images.githubusercontent.com/72315006/227942709-cce8d169-073c-4a9d-b83e-f1488e0ad2d7.jpg)

**Comment by mindphluxnet** [comment]
I've spawned him there but he summons his pet (size's good btw) to the left side, not to the right.

**Comment by geo-tp** [comment]
As we see on screenshot, spider is also spawned to the left on Whaldek (his orientation is barely the same as tauren)

**Comment by mindphluxnet** [comment]
That would mean he's standing on the road ... that can't be right. There's not much room really.

**Comment by geo-tp** [comment]
Just checked and you are right.
He must be Whaldek cause we know he should stand in this exact area, most likely not a player on screenshot.

Leave it as you did, way better than old location
