### ISSUE TITLE
TODO: Durotar rework

### ISSUE THREAD

**Issue by mindphluxnet** [The-Alpha-Project/alpha-core#1077]
**Describe what needs to be implemented or enhanced**
3139 [Misha Torkren](https://db.thealphaproject.eu/index.php?action=show_creature&id=3193&filter=misha&sort_order=name&pos=1&max=1) is standing at her release position but that can't be quite correct for 0.5.3 since her farmstead isn't yet there. We need to find out where she was standing; possibly at the nearby hut?

**Comment by geo-tp** [comment]
![images_6760](https://user-images.githubusercontent.com/72315006/228242634-dda6ee09-6456-476d-ac68-e135cac2a0e6.jpg)

is it actual pos ?

**Comment by mindphluxnet** [comment]
Hm, okay, that's the same spot.
