### ISSUE TITLE
Stonetalon Mountains is missing enemies

### ISSUE THREAD

**Issue by mindphluxnet** [The-Alpha-Project/alpha-core#1110]
**Describe the bug**
For the quest "Goblin Invaders" the player needs to kill Venture Co. Cutters and Grinders in Greatwood Vale. There's just one slight problem: they don't exist.

The creatures are in the database - although incomplete in terms of stats and virtual equipment - but they have no spawn points, likely because they got removed before vanilla launched. The quest got rewritten to only requiring Venture Co. Loggers in Windshear Crag. Greatwood Vale was repurposed to house the Grimtotem clan of tauren. 

We do know the mobs existed in alpha because we have screenshots of them ([Cutter](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Stonetalon%20Mountains/images_4515.jpg), [Grinder](https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Stonetalon%20Mountains/images_4504.jpg)), which is fortunate because that way we also know what virtual equipment they were using.

According to [Allakhazam](https://web.archive.org/web/20040711114350/http://wow.allakhazam.com/db/quest.html?wquest=1062) the quest was originally asking the player to also kill Venture Co. Loggers which fits Goblin Workshop listing them as also being present in Greatwood Vale ([Link](https://web.archive.org/web/20041222102506/http://goblinworkshop.com/areas/greatwood-vale.html)) along with a named elite mob we don't have in the database. Fortunately Goblin Workshop [can offer some pointers](https://web.archive.org/web/20080612014233/http://www.goblinworkshop.com/creatures/taskmaster-whipfang.html) to restore him although it's unclear what race he's supposed to be - Whipfang doesn't sound like a goblin to me, maybe a gnoll?

Thanks to an old Warcry map we also can get some ideas on where to put these mobs ([Link](https://crawler.thealphaproject.eu/mnt/crawler/media/Website/warcry.com/Atlas-May-June-2004/WoW%20Warcry%20-%20Content%20-%20Atlas%20-%20Stonetalon.php.html)). The map also mentions Venture Co. Planners we also have in our database. No idea what they were for as no quests seems to ask for their departure.

Since we only have vague placement information - and only two screenshots that don't exactly tell us much - it seems we'll need to get creative. I'm very much for restoring this cut content even though it'll be not exactly how it was in 0.5.3. How about you folks?

**Comment by geo-tp** [comment]
Concerning Taskmaster Whipfang

https://www.wowhead.com/classic/npc=5932/taskmaster-whipfang

![Capture d’écran_2023-04-02_01-22-18](https://user-images.githubusercontent.com/72315006/229322031-1c543154-fbc2-4eec-92bb-c8cb18994e2d.png)

We have it but  he is `ignored=1` because of too high entry (5932), greater than max_entry

Probably this quest should not be ingame for 0.5.3 ?

**Comment by mindphluxnet** [comment]
Taskmaster Whipfang isn't part of any quest so that's no problem.
