### ISSUE TITLE
Keryn Sylvius has questionable text.

### ISSUE THREAD

**Issue by heyitsbench** [The-Alpha-Project/alpha-core#1114]
**Describe the bug**
Keryn Sylvius, when interacted with by a non-rogue class, states the following:
```
Have a look at my meats, friend. You won't want to go out into the Barrens without a good stock of provisions.
```

**Steps to reproduce**
1. Create a human mage. (Probably happens with other non-rogue classes/non-human races)
2. Interact with Keryn Sylvius in Goldshire.
3. Observe her text.

**Expected behavior**
I wouldn't expect her to bring up the Barrens, residing in Goldshire. Other class trainers just give the 'Greetings $n' text when talked to by a class they don't teach, I'd expect her to say similar.

**Screenshots**
[The text in question](https://user-images.githubusercontent.com/38561765/229367914-5ddce0cc-5353-4f1f-b798-025e83768d79.png).

**Sources**
Could not find a source.

**Comment by onza120** [comment]
"Drusilla La Salle" - Warlock Trainer, outside Northshire Abbey (Human starting zone) states to non warlock classes "Where would you like to fly to?" Instead should be saying "Greetings <username>"

![image](https://github.com/The-Alpha-Project/alpha-core/assets/27241700/023f4810-194d-4dfa-b532-7bdd9cec2f3d)
