### ISSUE TITLE
TODO: Update Maris Granger

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#1118]
**Describe what needs to be implemented or enhanced**

https://db.thealphaproject.eu/index.php?action=show_creature&id=1292

We know that Skinning Trainer are not part of 0.5.3, Maris Granger has been reused from Armor Merchant to Skinning Trainer

We can clearly see here a sort of "mail" NPC display_id
![Capture d’écran_2023-04-04_19-07-25](https://user-images.githubusercontent.com/72315006/229866030-a2500f9c-390c-4a76-b366-e98f409bb6d7.png)

This model will be updated to skinning display_id

![Capture d’écran_2023-04-04_16-04-24](https://user-images.githubusercontent.com/72315006/229866097-21efb160-a980-47a3-a077-504a929788b2.png)

![Capture_decran_2023-04-04_14-37-04](https://user-images.githubusercontent.com/72315006/229869056-3bb953eb-f068-4419-b46b-ebd4397c09be.png)

**Expected end result**
1292 Maris Granger subname should be updated to "Mail Armor Merchant"
Flag should  be updated accordingly

**Comment by GrenderG** [comment]
> Same for Aldric Moore
> 
> https://db.thealphaproject.eu/index.php?action=show_creature&id=1294
> 
> He was reused from Leather Armor Merchant to Mail Armor Merchant.
> 
> old model ![Capture d’écran_2023-04-05_15-00-24](https://user-images.githubusercontent.com/72315006/230087998-bf0cf3ac-d086-442f-9d85-0ebfbdbf1a69.png)
> 
> new ![Capture d’écran_2023-04-05_14-59-14](https://user-images.githubusercontent.com/72315006/230088028-58f8df90-f270-4378-9956-d8614901c86e.png)
> 
> It makes sense, : 2 cloth, 2 leather, 2 mail (after update)
> 
> ![Capture_decran_2023-04-04_14-37-04](https://user-images.githubusercontent.com/72315006/230088242-d8b23a23-eb2b-4134-b6dd-70db8265bc3d.png)
> 
> 1294 Aldric Moore subname should be updated to "Leather Armor Merchant", vendor list should be updated

@geo-tp can you move this to its own Issue? Thanks.
