### ISSUE TITLE
TODO: Spawn Hill Giant

### ISSUE THREAD

**Issue by Yushe** [The-Alpha-Project/alpha-core#1128]
So far we only have one screenshot of the Hill Giant in action and thats about all the info we currently have.
As geo said in #573 the NPC might be using waypoints to patrol the area.

I will just leave this open to discussion & debate for now.
- [ ] Correct Hill Giants stats
- [ ] Spawn Hill Giant

Coords of the screenshot: `-138.912 -4226.490 118.364`

# Screenshots
![186518155-365fe42e-1ba8-46e0-99a4-6d1bb716a01b](https://user-images.githubusercontent.com/10089856/230522469-7b51f1ef-802c-4b33-9d57-a35def24b680.jpg)
![WoWScrnShot_040723_022835](https://user-images.githubusercontent.com/10089856/230522458-73942c90-cc6f-4905-b38c-83fbc7e42d39.jpg)

**Comment by mindphluxnet** [comment]
We don't know the Hill Giant's level, do we? Also, is he elite or not? I assume he is which would be in line with other roaming "a surprise elite mob kills you while you are afk" mobs (Son of Arugal comes to mind).

At least in my data we don't have any waypoints for him. Unlikely we have sniffs either as he seems to have been removed for release.

**Comment by geo-tp** [comment]
Hill giant is unused on release, most likely he was replaced by this guy :

Grimungous
https://www.wowhead.com/classic/npc=8215

Since Grimungous is not part of 0.5.3, we could reuse waypoints to apply on Hill giant.
It's basically the same area and it could be the real waypoints for Hill giant
We could compare screenshot of Hill Giant with Grimungous path on 1.12 client to be sure

**Comment by Yushe** [comment]
It does seem like Grimungous walks past the same area looking at the path on wowhead.

**Comment by GrenderG** [comment]
> Hill giant is unused on release, most likely he was replaced by this guy :
> 
> Grimungous https://www.wowhead.com/classic/npc=8215
> 
> Since Grimungous is not part of 0.5.3, we could reuse waypoints to apply on Hill giant. It's basically the same area and it could be the real waypoints for Hill giant We could compare screenshot of Hill Giant with Grimungous path on 1.12 client to be sure

This sounds like a really good idea. :+1:
