### ISSUE TITLE
TODO: Spawn Port Master Szik

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#1138]
**Describe what needs to be implemented or enhanced**
![boatvendor](https://user-images.githubusercontent.com/72315006/232312613-aaeea491-301f-4c9a-94f8-39dc2823771b.jpg)

https://db.thealphaproject.eu/index.php?action=show_creature&id=2662

**Expected end result**
2662 Port Master Szik should be spawned in Booty Bay

**Comment by Yushe** [comment]
What the hell is a Boat Vendor...?
