### ISSUE TITLE
TODO: Bring back a lost quest [Ambushed in the Forest]

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#1148]
[Ambassador Berrybuck](https://db.thealphaproject.eu/index.php?action=show_creature&id=271&filter=berrybuck&sort_order=name&pos=1&max=1) should offer a quest called [Ambushed in the Forest].

**Information about the quest**
- It should have an ID of 172. Currently this ID slot is empty and it was reused in vanilla for [the Children's Week](https://www.wowhead.com/classic/quest=172/childrens-week) quest
- It should be a lvl 25 quest
- It should belong to "Duskwood" quests in the quest log.
---
_[**QUEST LOG**]_

**Objective**
Retrieve Ambassador Berrybuck's satchel and bring it back to him in Darkshire.

**Description**
Lord Ebonlocke sent me to Stormwind to represent Darkshire at the recent council of the House of Nobles. I was tasked with requesting military aid in light of the undead infestation which has taken over the forest.

But on my way back a band of thieves ambushed me. I was forced to drive my cart to The Rotting Orchard in southern Duskwood.

Before the thieves could rob me of my goods, a pack of ferocious Worgen overtook the thugs. Now I need you to retrieve my satchel from the chest in the wagon.

**Talking to NPC with incomplete quest**
Were you able to locate my satchel? I had it stashed in my chest which was in the back of the wagon. Last I saw, the thieves had the cart south at [The Rotting Orchard.

**Talking to NPC with completed quest**
Most impressive, [Name]. I can't thank you enough for your assistance. This satchel contains all of my notes and correspondence from my recent trip to Stormwind. Now, I must present the dark news to Lord Ebonlocke. We might not have the assistance of the Stormwind Army but at least we have our Night Watch.

**Reward**
There are two sources, one from May 2005 listing only a cash reward of 14 silver. The second being 19 silver 82 copper from May 2004. I believe the second one should be used as it is closer to Alpha.

No item rewards are ever mentioned, there's a likelyhood this quest had none.
No experience is mentioned, however 

---
_[**DOING THE QUEST**]_

After taking the quest the player has to go to the Rotting Orchard and loot [the Ambassador's Satchel](https://db.thealphaproject.eu/index.php?action=show_item&id=1923&filter=satchel&sort_order=name&pos=1&max=6) from [the Ambassador's Locker](https://db.thealphaproject.eu/index.php?action=show_go&id=41&filter=locker&sort_order=name&pos=1&max=9), which is already spawned in the game by the cart next to the big house.

![Ambassador's Locker](https://github.com/The-Alpha-Project/alpha-core/assets/111394734/850c154c-c0d1-435b-8f46-551ef47617b2)

---
_[**SOURCES**]_
https://crawler.thealphaproject.eu/mnt/crawler/media/Database/WarcraftStrategy/quest_details_june_2004.html
https://crawler.thealphaproject.eu/mnt/crawler/media/Website/ultimategamers/web.archive.org/web/20040529080132/http:/www.ultimategamers.com/worldofwarcraft/quests/duskwoodquests.html
https://web.archive.org/web/20081001035811/http://www.goblinworkshop.com/quests/ambushed-in-the-forest.html
https://crawler.thealphaproject.eu/mnt/crawler/media/Text/Allakhazam/Allakahzam-Guides-2004.txt
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Duskwood/0415wow01.jpg | 4f3c00101e12fcff
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Duskwood/images_5622.jpg | 01c0c8c8c0000002

Screenshots are from first days of 0.6.

**Comment by GizzleBizzle** [comment]
![obraz](https://github.com/The-Alpha-Project/alpha-core/assets/111394734/e573cd83-fa6d-4a30-8764-981e787c20d2)

Is it something, that could be changed? This quest should be listed under "Duskwood" category.
Will reopen when I get he answer.

**Comment by GrenderG** [comment]
I think it's not possible to set Duskwood as quest zone in 0.5.3.
