### ISSUE TITLE
TODO: Finish implementing Shaia and Lewin NPCs

### ISSUE THREAD

**Issue by GrenderG** [The-Alpha-Project/alpha-core#1163]
**Describe what needs to be implemented or enhanced**
They are vendors but they aren't selling anything nor have the proper flag.

**Expected end result**
They should actually be vendors selling the proper armors. Currently both Melea and Shaia have the same <Mail Armor Merchant> subname, we should also investigate if this is correct and what should each of them sell.

4178 Shaia 
4239 Lewin

**Comment by mindphluxnet** [comment]
Interestingly, Shaia was not spawned in Vanilla (at least according to Wowhead Classic). It's likely she existed in alpha and sold exactly the same stuff as Melea until the devs decided she wasn't needed. So if anything she should have the exact same inventory as Melea.

Lewin also no longer existed in Vanilla/Classic. He should likely sell whatever other leather armor merchants were selling back then.

If you give the OK I can implement this.

**Comment by geo-tp** [comment]
![image](https://github.com/The-Alpha-Project/alpha-core/assets/72315006/4c0b977c-aa1e-49b1-a5ec-3e833590b1a0)

I think you are right, these sellers seem to have been deleted because they all sold the same thing, some of them have also been modified to sell other types of armor later
