### ISSUE TITLE
Issues with pathfinding for Gol'Bolar Quarry cave in Dun Morogh

### ISSUE THREAD

**Issue by EsreverWoW** [The-Alpha-Project/alpha-core#1170]
**Describe the bug**
There seems to be some issues with pathfinding in parts of the Gol'Bolar Quarry cave.

**Steps to reproduce**
1. Encounter enemies. Have them move into certain areas by manually placing them or having them run off when low health.
2. They will float upward Z-axis to the top of the cave and then cannot reach the player. You will hear their footstetps above.
3. Move to a position of line of sight where you may be seen. They will then adjust their position to then reach the player.

**Expected behavior**
These enemies should remain inside of the cave and not find themselves outside of it.

**Screenshots**
https://github.com/The-Alpha-Project/alpha-core/assets/49285632/0c210b3a-0af7-4ae3-9210-06c8dd429de4

**Sources**
None

**Comment by EsreverWoW** [comment]
Note that this was recorded on the new Brill Alpha PTR realm.

**Comment by devw4r** [comment]
Namigator resolving wrong (above cave Z)

Map 0 -5722.27  -1687.44    358.59  
Namigator Z: 377

Map 0 -5711.44  -1702.63    359.749 
Namigator Z: 378

Map 0 -5707.4    -1698        359.636 
Namigator Z: 376

@namreeb
