### ISSUE TITLE
TODO:  Change  Uldaman entrance mobs with Troggs

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#1241]
**Describe what needs to be implemented or enhanced**
![79](https://github.com/The-Alpha-Project/alpha-core/assets/72315006/eab52b6b-700c-4c18-95b8-57b3d0adde55)
![73](https://github.com/The-Alpha-Project/alpha-core/assets/72315006/37760b76-108a-43e8-bb37-503b4ffbe145)
![75](https://github.com/The-Alpha-Project/alpha-core/assets/72315006/13470a03-4008-4e99-8e7e-7eaf5d0a153f)
![72](https://github.com/The-Alpha-Project/alpha-core/assets/72315006/82455127-6cd5-4a5c-8d4e-badb357c74cd)
![78](https://github.com/The-Alpha-Project/alpha-core/assets/72315006/c8ae3dca-4ce9-4db0-ac5d-20b0d8aeb171)

Unused mobs 
https://db.thealphaproject.eu/index.php?action=show_creature&id=2889
https://db.thealphaproject.eu/index.php?action=show_creature&id=2890
https://db.thealphaproject.eu/index.php?action=show_creature&id=2891

**Expected end result**

Change Dwarf outdoor mobs from Uldaman entrance with these 3 unused trogg entries

**Comment by Yushe** [comment]
It's a shame the only images that you were able to find don't even have the mobs selected so we currently don't know if they had a different level or not.

**Comment by geo-tp** [comment]
![stonevault](https://github.com/The-Alpha-Project/alpha-core/assets/72315006/c4d96106-6f09-4871-b403-cab136009dc9)

linked entries, probably they follow a logical level range like 38-39
