### ISSUE TITLE
TODO: Change Unlit Torch's Icon

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#1277]
[Unlit Poor Torch](https://db.thealphaproject.eu/index.php?action=show_item&id=6183&filter=unlit&sort_order=name&pos=2&max=2) should use the Icon ID of 135434.

**Source from 0.5.5**
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Elwynn%20Forest/fish12.jpg | 18181c1010e1fdfc
https://www.wowhead.com/classic/icon=135434/inv-torch-unlit

**Comment by mindphluxnet** [comment]
I don't think this is possible as there's no itemdisplayinfo entry in the DBC using this icon. It likely got added later.

**Comment by geo-tp** [comment]
as mindphlux said, this display_id does not exist for 0.5.3, probably the placeholder is this one

![unlit](https://github.com/The-Alpha-Project/alpha-core/assets/72315006/102ac99c-4343-4222-861c-b95730f24a37)
