### ISSUE TITLE
TODO: Rename and spawn the Loch Modan Horde Runners

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#1288]
[Haren Swifthoof](https://db.thealphaproject.eu/index.php?action=show_creature&id=2478&filter=horde+runner&sort_order=name&pos=2&max=2) and [Gradok](https://db.thealphaproject.eu/index.php?action=show_creature&id=2477&filter=horde+runner&sort_order=name&pos=1&max=2) should be renamed to Tauren Horde Runner and Orc Horde Runner respectively.

Once the NPCs have been renamed spawn another Orc Horde Runner following the already existing Orc Horde Runner (So that they are forming a line while following the Tauren Horde runner). 

**Source** From 0.5.5
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Loch%20Modan/screens_139.jpg | f9f000100200e400

https://archive.thealphaproject.eu/media/Alpha-Project-Archive/UNSORTED/www_judgehype_com/Galerie%20d-images%20-%20Beta%20screenshots%20-%2027%20mars%202004%20-%20World%20of%20Warcraft%20-%20JudgeHype%20-%2004-09-2021%2004-34-49/27%20MARCH%2004%20-%20105.jpg | 1ec6e7ef7f200700

**Comment by shobhit9957** [comment]
Hey, I would love to contribute.. can you please guide me... i'm a beginner here.

**Comment by geo-tp** [comment]
> Hey, I would love to contribute.. can you please guide me... i'm a beginner here.

Check discord : https://discord.gg/RzBMAKU


Concerning `Orc Horde Runner`, the 3rd guys was replace by this guy : https://www.wowhead.com/classic/fr/npc=7170/thragomm

`Orc Horder runner` should be probably spawned 2 times but since this guys have waypoints, it's better to bring Thragomm and rename it `Orc Horde Runner`.

**Comment by GizzleBizzle** [comment]
One more thing, their subnames should be removed. They were added later.

After removing <Horde Runner> subtext it will be 100% correct.

**Comment by GrenderG** [comment]
Reopening so we don't forget!
