### ISSUE TITLE
TODO: Add an ability to Defias Pillagers

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#1290]
[Defias Pillagers](https://db.thealphaproject.eu/index.php?action=show_creature&id=589&filter=pillager&sort_order=name&pos=1&max=2) should use [Frost Armor](https://db.thealphaproject.eu/index.php?action=show_spell&id=7300&filter=frost&sort_order=Name_enUS&pos=27&max=184).

[SPECULATION]
Though it isn't known which rank it should be, there isn't much difference between the two available ranks. The chill effect is the same for both of them and the only thing that changes between those ranks is 5 additional armor. I would give them the second rank as mages can learn it at lvl 10 and the mobs are 14-15.

**Sources from 0.5.5**

Pillagers chilling voidwalkers hitting them in melee range.
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Westfall/WoWScrnShot_032104_203734.jpg | 8121e8cc0ecfdf03

Getting chilled while attacking a pillager,
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Westfall/images_3261.jpg |0cccfcffedc4e040

**Comment by devw4r** [comment]
They already use Frost Armor, if you test it with a character within the mob level range you should see it trigger.

![image](https://github.com/The-Alpha-Project/alpha-core/assets/108442943/82e1ed7b-0758-4719-8e3e-d1ffa3f066ca)

@GrenderG : Close this.
