### ISSUE TITLE
TODO: Rework the Soulbound system

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#1293]
Alpha was more lenient when it came to loot restrictions. Most of items could be traded freely. Blizzard started limiting those options more and more with the following patches, citing anti-gold-seller measures.

I've done quite a lot of research and provided a lot of proof to clear any doubts.
The following group of items should be reverted back to alpha state.

----

**[World/Zone Drop Loot]**
Loot dropped randomly from mobs should NOT have any "Bind on..." tags. It should be tradeable even after using it after some time.

**Sources**
Random green from 0.6
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Arathi%20Highlands/WoWScrnShot_061104_041704.jpg

[Glimmering Mail Boots](https://db.thealphaproject.eu/index.php?action=show_item&id=4073&filter=glimmering&sort_order=name&pos=3&max=12) are a world drop, [Defias Renegade Ring](https://db.thealphaproject.eu/index.php?action=show_item&id=1076&filter=Defias+renegade&sort_order=name&pos=1&max=1) however is a zone drop from the Stockade.

---

**[Outdoor Quest Rewards]**
Rewards from outdoor quests should NOT have any "Bind on..." tags and should be traded freely, even after putting it on the character.

**Sources**
[Harvester's Robe](https://db.thealphaproject.eu/index.php?action=show_item&id=1561&filter=harvester&sort_order=name&pos=3&max=3) is a reward from [The Killing Fields](https://db.thealphaproject.eu/index.php?action=show_quest&id=9) quest in Westfall.
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Elwynn%20Forest/diary_039.jpg

[Crescent of Forlorn Spirits](https://db.thealphaproject.eu/index.php?action=show_item&id=2044&filter=crescent+of+forlorn&sort_order=name&pos=1&max=1) -> Last part of [the Legend of Stalval](https://db.thealphaproject.eu/index.php?action=show_quest&id=98) quest chain.
[Crest of Darkshire](https://db.thealphaproject.eu/index.php?action=show_item&id=6223&filter=crest+of+dark&sort_order=name&pos=1&max=1) -> Last part of [the Bride of the Embalmer] (not in 0.5.3)
[Ring of Pure Silver] (not in 0.5.3) -> Reward for [Raeane's Cleansing] (not in 0.5.3).
[Soldier Cap](https://db.thealphaproject.eu/index.php?action=show_item&id=1282&filter=soldier&sort_order=name&pos=2&max=2) -> Reward for [Morbent Fel](https://db.thealphaproject.eu/index.php?action=show_quest&id=55)
[Crusader Belt](https://db.thealphaproject.eu/index.php?action=show_item&id=3758&filter=crusader&sort_order=name&pos=2&max=3) ->Reward for [Syndicate Assasins](https://db.thealphaproject.eu/index.php?action=show_quest&id=505)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/UNSORTED/www3_telus_net/www3_telus_netPush_1_-_Dwarf_Warrior_KyanMehwulfe_Lv30_04-08.jpg

From 0.5.4
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Westfall/NoBans.jpg | 5f40c0dcde7efe00

**Rings**
As you can notice in the screenshots above rings should also not have any "Bind on..." tags, however they should all have "Unique" tags. This was most likely done by Blizzard to prevent characters from buying/getting two of the same rings from other people.

----

**Elite Outdoor Quests**
Even quests, which are elite offer rewards, which can be traded with everybody.

**Sources**
[Gold Lion Shield](https://db.thealphaproject.eu/index.php?action=show_item&id=2916&filter=gold+lion&sort_order=name&pos=1&max=1) is a reward for [A Grim Task](https://db.thealphaproject.eu/index.php?action=show_quest&id=304), an elite quest in Wetlands (from 0.5.5)

[Orc Crusher](https://db.thealphaproject.eu/index.php?action=show_item&id=6093&filter=Orc+crusher&sort_order=name&pos=1&max=1) is a reward for [Tharil'zun](https://db.thealphaproject.eu/index.php?action=show_quest&id=19), an elite quest in Redridge.

----

**[Rewards for Quests in Instances]**
Rewards from quests in instances should be "Bind on pickup". This was most likely done by Blizzard to prevent some characters avoiding doing difficult quests (or even instances) by paying people to get them those items.

**Source**
Reward from an elite quest in Blackfathom Deeps (from 0.5.5)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Cities/Stormwind/elitequest_reward.jpg | 141c9ec6fc3c3e00

----

**[Crafting items]**
Items from crafting should NOT have a "Bind on..." tag UNLESS they are rare (blue).

**Sources**
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Redridge%20Mountains/hs016.jpg

[Golden Scale Shoulders](https://db.thealphaproject.eu/index.php?action=show_item&id=3841&filter=Golden+scale&sort_order=name&pos=6&max=11) and [Leggings](https://db.thealphaproject.eu/index.php?action=show_item&id=3843&filter=Golden+scale&sort_order=name&pos=5&max=11) are not soulbound while the [rare chest](https://db.thealphaproject.eu/index.php?action=show_item&id=2870&filter=silver+scale&sort_order=name&pos=1&max=1) has this tag.
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/UNSORTED/www3_telus_net/www3_telus_netPush_1_-_Dwarf_Warrior_KyanMehwulfe_Lv30_04-08.jpg

----

**[Dungeon Loot]**
Loot dropped by bosses in alpha instances should be Bind of Equip instead of Bind on Pickup.

**Sources**
[Lavishly Jeweled Ring](https://db.thealphaproject.eu/index.php?action=show_item&id=1156&filter=lavishly&sort_order=name&pos=1&max=1), which drops from [Gilnid](https://db.thealphaproject.eu/index.php?action=show_creature&id=1763) in the Deadmines. (From 0.5.4)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Instances/Dungeons/Deadmines/AwesomeAlphaLoot.jpg | fc3c3c38b0e0c0c2

[Corsair's Overshirt](https://db.thealphaproject.eu/index.php?action=show_item&id=5202), which drops from [VanCleef](https://db.thealphaproject.eu/index.php?action=show_creature&id=639&filter=vancleef&sort_order=name&pos=1&max=1) in the Deadmines (from 0.5.5)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Elwynn%20Forest/images_3209.jpg | 818c1c7c3f00f0fe

[Commander's Crest](https://db.thealphaproject.eu/index.php?action=show_item&id=6320&filter=commander%27s&sort_order=name&pos=1&max=1), which drops from [Commander Springvale](https://db.thealphaproject.eu/index.php?action=show_creature&id=4278) in SFK (from 0.5.5)
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Elwynn%20Forest/670.jpg | 0313c7e7c0c7fffc

**Comment by mindphluxnet** [comment]
Are drops from instanced rare spawns (Bruegal Ironknuckle, Miner Johnson come to mind) supposed to be BoP or BoE? They aren't really bosses but they are named in a dungeon.

**Comment by GizzleBizzle** [comment]
Items from rare mobs in instances should also be BoE. 

https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Cities/Undercity/WoWScrnShot_052704_021926%20(1).jpg | 8181808080f3fbff
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Eastern%20Kingdoms/Swamp%20of%20Sorrows/WoWScrnShot_061204_042146.jpg | bcf8980000e086ff

[Black Malice](https://db.thealphaproject.eu/index.php?action=show_item&id=3194&filter=malice&sort_order=name&pos=1&max=1) and Haunting Blade (not present in our database) are drops from the [Deathsworn Captain](https://db.thealphaproject.eu/index.php?action=show_creature&id=3872&filter=deathsworn&sort_order=name&pos=1&max=1), a rare in SFK.

Both screenshots are from the end of 0.6
