### ISSUE TITLE
TODO: Spawn Theramore NPCs

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#1307]
**Describe what needs to be implemented or enhanced**

https://db.thealphaproject.eu/index.php?action=show_creature&id=5046
https://db.thealphaproject.eu/index.php?action=show_creature&id=5044

https://www.wowhead.com/classic/fr/npc=5046/lieutenant-caldwell
https://www.wowhead.com/classic/npc=5044/theramore-skirmisher

**Expected end result**
Lieutenant Caldwell and Theramore Skirmisher should be spawned at wowhead loc

**Comment by GrenderG** [comment]
Hmmm are you sure these existed in 0.5.3?

**Comment by geo-tp** [comment]
Most likely, unique display_id and low entry (max is 5759). Why they are despawned ?

Or maybe these guys are spawned by a script ?

**Comment by GrenderG** [comment]
Looks like it, they aren't spawned by default in Vanilla either. Most likely related to some quest involving Paval Reethe NPC.

**Comment by geo-tp** [comment]
https://classicdb.ch/?quest=1273

you are right, i close this
