### ISSUE TITLE
TODO: Update Pet trainers

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#1335]
Harb Clawhoof
========

https://db.thealphaproject.eu/index.php?action=show_creature&id=3685

In 1.12, he is kodo vendor,
In 0.5.3, he is cat trainer.

Change flag accordingly

Galthuk
=======

![](https://user-images.githubusercontent.com/72315006/209007464-268a1873-ea05-4a5d-ab35-194f904bc788.png)

https://db.thealphaproject.eu/index.php?action=show_creature&id=4043

Change subname to Bear Trainer

**Comment by mindphluxnet** [comment]
This can be closed; the current database seems to incorporate both of these changes.
