### ISSUE TITLE
TODO: Rename Kingsblood

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#1338]
[Kingsblood ](https://www.wowhead.com/classic/item=3356/kingsblood) was originally called Crownroyal. 

**Sources**
- The original Game Object called [Crownroyal](https://db.thealphaproject.eu/index.php?action=show_go&id=1624&filter=crownroyal&sort_order=name&pos=1&max=1) shares the same ID as the classic version of [Kingsblood](https://www.wowhead.com/classic/object=1624/kingsblood).

- Screenshot from 0.5.5
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Cities/Stormwind/141.jpg

**Comment by GrenderG** [comment]
[I changed this in the past already](https://github.com/The-Alpha-Project/alpha-core/commit/a4546228dfab43899e8a37dac21c83b6e06a7c77), looks like it was overwritten for some reason. Thank you for noticing!
