### ISSUE TITLE
When your pet is out of mana and it tries to cast something, player character gets the "Not enough mana" spam.

### ISSUE THREAD

**Issue by GrenderG** [The-Alpha-Project/alpha-core#1353]
**Describe the bug**

**Steps to reproduce**
1. Summon a pet that uses mana like the Warlock Imp.
2. Make it attack a mob until it's out of mana.
3. Receive the "Not enough mana" message spam.

**Expected behavior**
This message should only trigger if the player is out of mana, not pet.

**Video**
https://github.com/The-Alpha-Project/alpha-core/assets/8654362/2a670d81-82a0-4684-86b3-0229e795081b

**Comment by geo-tp** [comment]
Are we sure this is not the expected behavior ?

It seems that we are using the correct OPCODE and the correct SpellCheckCastResult
![a](https://github.com/The-Alpha-Project/alpha-core/assets/72315006/8ee83696-3e29-4bac-ac6d-f14e2d71b35c)


I checked and the only way to remove the spam that I found is to not send the pet cast failure

**Comment by Fluglow** [comment]
The issue is that `PetManager` is using `casting_spell.meets_casting_requisites` in some auto cast checks, which is sending the cast error. We should probably modify that method to never send errors.

**Comment by geo-tp** [comment]
Here's what I understand but maybe i'm wrong

`PetAI._perform_auto_cast` -> `SpellManager.meets_casting_requisites` -> `SpellManager.send_cast_result`  -> `PetManager.handle_cast_result`

and then `PetManager.handle_cast_result` send `OpCode.SMSG_PET_CAST_FAILED` with `SPELL_FAILED_NO_POWER`   
and it seems that it is this pet opcode who displays the message "No enough Mana" to the player


Would the correct behavior be not to send this message to the client as not to display anything ?

or 

Should we show this message once and prevent the pet from autocasting after that to avoid the spam ?
