### ISSUE TITLE
TODO: Spawn missing Mottled Riptooth creatures

### ISSUE THREAD

**Issue by GrenderG** [The-Alpha-Project/alpha-core#1360]
**Describe what needs to be implemented or enhanced**
In the early days, quest [Omer's Revenge](https://db.thealphaproject.eu/index.php?action=show_quest&id=295) also required [Mottled Riptooth](https://db.thealphaproject.eu/index.php?action=show_creature&id=1066) to be slain. The quest already has the changes implemented, but we need to spawn those mobs since they weren't spawned in Vanilla.

**Expected end result**
1. Remove `UNUSED` from the NPC subname.
2. Add loot tables to the mob if needed (from what I saw in Allakhazam we could simply copy them from the other 2 raptors).
3. Spawn a reasonable amount of this NPC in the appropriate guessed place(s).

**Comment by geo-tp** [comment]
https://crawler.thealphaproject.eu/mnt/crawler/media/Website/warcry.com/Atlas-May-June-2004/WoW%20Warcry%20-%20Content%20-%20Atlas%20-%20Wetlands.php.html

lvl 27-28
