### ISSUE TITLE
Stocking Jetsteam (317) Objective Doesn't Match Description 

### ISSUE THREAD

**Issue by Alonin** [The-Alpha-Project/alpha-core#1371]
**Describe the bug**
The quest's description says you need to get 4 chunks of boar meat and 2 thick bear furs, but the actual objective is only 4 chunks of boar meat.
![image](https://github.com/The-Alpha-Project/alpha-core/assets/109882487/ca05740d-d6d3-481a-86d7-6d3a5897e5ba)

![image](https://github.com/The-Alpha-Project/alpha-core/assets/109882487/a62ab364-0499-4693-9ab4-dbb590a7c02b)

**Steps to reproduce**
1. Accept the quest
2. Compare description and objective

**Expected behavior**
Either the description needs to be changed to only mention boar meat, or the objective needs to be changed to include bear fur.

**Comment by GrenderG** [comment]
Good catch; the fur item doesn't exist in 0.5.3 so the description is what needs to be changed.
