### ISSUE TITLE
A Dark Threat Looms quest " Suspicious Barrel " inside the bridge.

### ISSUE THREAD

**Issue by Jadvar** [The-Alpha-Project/alpha-core#1376]
**Describe the bug**

Quest: A Dark Threat Looms

" Suspicious Barrel " is inside the bridge. Need to be moved slightly so its clickable =)

**Expected behavior**

Move barrel so we can click it.

**Comment by devw4r** [comment]
?

![image](https://github.com/The-Alpha-Project/alpha-core/assets/108442943/45c925a5-e516-48b7-ad4d-a63950297d07)

**Comment by GrenderG** [comment]
You are inside a column, if you move a bit you will notice it's inside of it @devw4r 😆
