### ISSUE TITLE
The Unsent Letter Incorrect Description

### ISSUE THREAD

**Issue by Alonin** [The-Alpha-Project/alpha-core#1381]
**Describe the bug**
The quest The Unsent Letter (373) says Baros Alexston is in the Cathedral District, but in 0.5.3 he is in the Trade District. Either his location or the quest description needs to be updated to match. 

https://db.thealphaproject.eu/index.php?action=show_creature&id=1646&filter=baros&sort_order=name&pos=1&max=1

**Screenshots**
![image](https://github.com/The-Alpha-Project/alpha-core/assets/109882487/4fd12413-3b82-451c-a3f8-2145cf7ecadb)

**Comment by GrenderG** [comment]
Closed on https://github.com/The-Alpha-Project/alpha-core/pull/1382
