### ISSUE TITLE
TODO: Change Dragonling diplay_id

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#1387]
**Describe what needs to be implemented or enhanced**

https://db.thealphaproject.eu/index.php?action=show_creature&id=2678

![whelp](https://github.com/The-Alpha-Project/alpha-core/assets/72315006/048f2e93-127c-4007-81ab-0e3aa4917073)

1.0 scale, the first avalaible dragon model
color variation from vanilla not present yet

**Expected end result**

```UPDATE `creature_template` SET `display_id1` = 6 WHERE (`entry` = 2678);```

**Comment by GrenderG** [comment]
Literally did that here: https://github.com/The-Alpha-Project/alpha-core/commit/8cfa4fefc8c7a59b7e8f1e91d847142c107c518e 😝
