### ISSUE TITLE
The Defias Brotherhood escort quest fail

### ISSUE THREAD

**Issue by Tenshrock** [The-Alpha-Project/alpha-core#1398]
Hi, the quest The Defias Brotherhood (https://db.thealphaproject.eu/index.php?action=show_quest&id=155) fail at the end of the escort. The message "The Defias Brotherhood failed" appear in the chat and the traitor disappear just before arriving at the waypoint.

![Sans titre](https://github.com/The-Alpha-Project/alpha-core/assets/11035915/bf56e6fc-bc52-41fb-a2cd-2d704a02e72d)

Thanks.

**Comment by GrenderG** [comment]
Weird, were you standing next to the NPC?

**Comment by Tenshrock** [comment]
Yes, right next to it like in the screenshot, it's the NPC right in front of me. The NPC was not being attacked at this time and was full life. I don't know what caused the failure.

**Comment by Alonin** [comment]
This happened to me and I believe Melsec as well, it doesn't happen every time, but I haven't been able to identify a cause.

**Comment by Tenshrock** [comment]
I confirm that this is fixed. After reviewing my recording, it turns out that the quest fails exactly 10 minutes after being taken. Wouldn't there be a default time limit for this type of quest?

**Comment by devw4r** [comment]
The event does have a time limit set:

![image](https://github.com/user-attachments/assets/dd143dc3-31be-457c-b20f-e267171ffe2b)

Not sure if thats Blizzlike @GrenderG, still in retail videos of the quest you can't see any quest timer.

**Comment by GrenderG** [comment]
This script is taken from VMaNGOS, unsure if timer is Blizzlike or not. cc @ratkosrb

**Comment by ratkosrb** [comment]
DB scripted escorts always have a time limit, to avoid quest getting stuck somehow, and thus no longer able to be started by anyone. If it's insufficient to complete the quest, then increase it.

**Comment by GrenderG** [comment]
Should be fine I think, the issue is that the NPC was not properly running before, now it runs so it takes less time.
