### ISSUE TITLE
Column missing in alpha_realm

### ISSUE THREAD

**Issue by diff3** [The-Alpha-Project/alpha-core#14]
item_flags is missing in character_inventory. Without it, the client crashes after creating a character. 

My quick fix was adding the column to the table.

ALTER TABLE alpha_realm.character_inventory ADD item_flags int NULL;

**Comment by GrenderG** [comment]
You are missing [the update](https://github.com/The-Alpha-Project/alpha-core/blob/master/etc/databases/realm/updates/updates.sql).

**Comment by diff3** [comment]
ok, I added all the updates, it's working fine

I'm using a mac, and I had trouble running update.sql, so I had to do it manually instead. I did try to install sqlcmd as well.
