### ISSUE TITLE
TODO:  Attach campfires to Survival Trainer

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#1404]
**Describe what needs to be implemented or enhanced**

Basic campfire and Bright Campfire should be learned by survival trainer
https://db.thealphaproject.eu/index.php?action=show_spell&id=818
https://db.thealphaproject.eu/index.php?action=show_spell&id=7359

![elwynn_forest_017](https://github.com/The-Alpha-Project/alpha-core/assets/72315006/3bda506e-c6c5-43dd-8c3b-6e5048e5fe32)
![XX28](https://github.com/The-Alpha-Project/alpha-core/assets/72315006/5c9d44b7-f596-4c4a-a78c-4b725b946861)

**Expected end result**

Survival trainer should be interractable and learn these 2 campfires.
Spells should appear directly into the player spellbook

**Comment by GrenderG** [comment]
Note: check if Cooking is currently teaching the campfire and if it's doing it, remove it.

**Comment by geo-tp** [comment]
![skillinsurv](https://github.com/The-Alpha-Project/alpha-core/assets/72315006/d875f4ea-9779-4d95-aa33-c98d350a1f8b)

Bright campfire could be available from survival level 25 maybe

**Comment by geo-tp** [comment]
screenshot confirmation that these spells must appear in the spellbook

![wowmakingof6](https://github.com/user-attachments/assets/99c00a86-c48b-4f0f-8e80-23f63957e3d8)
