### ISSUE TITLE
TODO: Investigate - Ironforge Surveyors

### ISSUE THREAD

**Issue by devw4r** [The-Alpha-Project/alpha-core#1440]
![image](https://github.com/user-attachments/assets/557dc9e7-9660-4006-a6bb-5fa817ed4a5d)

[Gelgann Direforge <Ironforge Surveyor>](https://web.archive.org/web/20040819193111/http://wow.allakhazam.com/db/mob.html?wmob=5788)
[Serra Mountainhome <Ironforge Surveyor>](https://web.archive.org/web/20040819193111/http://wow.allakhazam.com/db/mob.html?wmob=5789)
[Lizzle Sprysprocket <Ironforge Surveyor>](https://web.archive.org/web/20040819193111/http://wow.allakhazam.com/db/mob.html?wmob=5790)

https://warcraft.wiki.gg/wiki/Gelgann_Direforge
https://warcraft.wiki.gg/wiki/Serra_Mountainhome
https://warcraft.wiki.gg/wiki/Lizzle_Sprysprocket

**Comment by geo-tp** [comment]
Probably not spawned for 0.5.3, max entry is 5749, they were mostly added in 0.5.4
