### ISSUE TITLE
CommandManager.py Line 107 Issue

### ISSUE THREAD

**Issue by Firewarrior565** [The-Alpha-Project/alpha-core#1442]
**Describe the bug**
Starting the server i'm getting this:

 File "C:\Users\User\Desktop\alpha-core_setup\alpha-core-master\game\world\managers\CommandManager.py", line 107
    return 0, f'collision cheat {'On' if active else 'Off'}'
                                  ^^
SyntaxError: f-string: expecting '}'

Modifying line 107 in game\world\managers\CommandManager.py from:

****return 0, f'collision cheat {'On' if active else 'Off'}'**** 

to:

return 0, f'collision cheat {"On" if active else "Off"}' 

This appears to fix it. AKA swapping the ' for " .

**Steps to reproduce**
1. ...Follow Daribon's easy setup guide. https://github.com/Daribon/alpha-core_setup?fbclid=IwAR2dYkzTcJuqvoAMeoqp-Vn-Bbx5Qe1XDcyuFCg7fGMSflKwzTfXy4jjRcU
2. ... Start mariadb.bat
3. ... Run start_alpha-core.bat
4. CMD shuts down from the error unless I kick it off from within CMD.

**Expected behavior**
Server shut start happily.
**Screenshots**
If needed, add screenshots to help explain your problem.
![image](https://github.com/user-attachments/assets/7b5924d3-d097-4273-9b44-b94c86b1892b)

**Sources**
If needed, provide valid sources (original screenshots or videos, archived allakhazam...) that show what's the expected behavior or state.

**Comment by Firewarrior565** [comment]
I'm preparing a new video guide and I was going through the steps in Docker land. I ran into the same problem as I reported back in September.

**Comment by GrenderG** [comment]
What Python version are you using @Firewarrior565?

**Comment by Firewarrior565** [comment]
Sorry for the delay!  Python 3.11.2
