### ISSUE TITLE
Suggestion : Docker

### ISSUE THREAD

**Issue by Ktzomb** [The-Alpha-Project/alpha-core#16]
Hi, not really an issue just a suggestion, would you consider adding a docker build ?
https://www.docker.com/

**Comment by GrenderG** [comment]
Hello! I'm not against it, but I don't have docker knowledge. If someone else wants to add support for it, I'll accept the PR.

**Comment by Ktzomb** [comment]
I do not have much knowledge but I will give it a try, thank you

**Comment by Cyberrebell** [comment]
I think I got it working using docker-compose: #17

**Comment by GrenderG** [comment]
Implemented in #17.
