### ISSUE TITLE
Jasperlode mine cannot be handed in

### ISSUE THREAD

**Issue by Fabrice-leterme** [The-Alpha-Project/alpha-core#213]
You can complete this quest, but you can not hand it in to the quest npc.

If you do, you can no longer use any ingame options.

No talking to npc's, no using quit or logout in menu either.

**Comment by Fabrice-leterme** [comment]
This seems to be an issue with the experience received from the quest. I put the xp_rate higher (think it was x3) to speed through the content faster

**Comment by devwar87** [comment]
Was able to complete this, maybe the server crashed due some other thing in between doing the quest and turn in.

![Mine01](https://user-images.githubusercontent.com/72774832/148317182-4f7e83c9-7da9-48a0-942b-7e2b0cab0565.PNG)
![Mine02](https://user-images.githubusercontent.com/72774832/148317188-963e151f-86de-45cf-88e3-5e08bc39f7da.PNG)

**Comment by GrenderG** [comment]
Closing this as it's the same as #214
