### ISSUE TITLE
Deadmines cannon to last room

### ISSUE THREAD

**Issue by Fabrice-leterme** [The-Alpha-Project/alpha-core#215]
When engering deadmines, everything seems to work just fine until you reach the cannon to enter the final boss room.

You can load in the Defias gunpowder and the cannon says it's firing, however many times you do this the door stays locked.

**Comment by Fluglow** [comment]
Seems to require instance scripting to fix properly. You can use lockpicking to get around this issue for now.

**Comment by GrenderG** [comment]
Closing this issue as it's not specific to this instance, just general scripting system is missing.
