### ISSUE TITLE
TODO: Rage generation on damage received

### ISSUE THREAD

**Issue by GrenderG** [The-Alpha-Project/alpha-core#235]
**Describe what needs to be implemented or enhanced**
Implement rage generation on damage received.

**Expected end result**
Rage users should see their rage increment when receiving damage (if conditions are met).

**Guidance**
1. I assume a good place to implement it would be in `receive_damage`.
2. We can use the Vanilla formulae.

EDIT: Please read https://github.com/The-Alpha-Project/alpha-core/issues/235#issuecomment-1073138847 for further clarification of how it should work.

**Comment by Fluglow** [comment]
Rage generation and decay behavior varies between warrior stances (ie. shapeshift form). Bear form does not describe how rage generation works, but could be for example assumed to be the same as battle stance. The spells only apply a shapeshift on the affected unit, so `has_form` would be used to determine how rage is generated.

Descriptions from Spell.dbc:
Defensive Stance (71): "A defensive stance that reduces rage decay when out of combat.  Generate rage when you are hit."
Battle Stance (2457): "A balanced combat stance.  Generate rage when hit and when you strike an opponent."
Berserker Stance (2458): "An aggressive stance.  Generate rage when you strike an opponent."

**Comment by GrenderG** [comment]
Fixed in https://github.com/The-Alpha-Project/alpha-core/pull/241.
