### ISSUE TITLE
TODO: Critical strikes

### ISSUE THREAD

**Issue by Fluglow** [The-Alpha-Project/alpha-core#239]
**Describe what needs to be implemented or enhanced**
Implement critical strikes for spells. 

**Expected end result**
Spells should be able to result in critical strikes and deal extra damage or healing.

**Guidance**
1. Implement a method in StatManager that resolves the total critical strike chance for a spell. This should for example account for the difference in critical strike chance between magic spells and abilities. You may be able to utilize existing logic for base attacks. Spell school skill can also be accounted for similar to weapon skills, since we don't have information on how they affected combat.
2. Roll critical strike chance in either the previously mentioned method or another one depending on requirements.
3. Add critical strike bonus multiplier in `calculate_spell_damage` for spells. Different spell types may(?) have varying critical strike bonus values.

**Comment by GrenderG** [comment]
Just leaving a note here: according to 0.5.5 patch notes: `Critical hits with ranged weapons now do 100% extra damage.`. Not sure what the extra damage for ranged weapon was in 0.5.3, either 50% or 200% I guess...

**Comment by GrenderG** [comment]
Critical strikes for melee attacks have been added here: https://github.com/The-Alpha-Project/alpha-core/commit/9fa1a0250bd201fd71bccdddddb51ad2a68acdaf

**Comment by GrenderG** [comment]
https://github.com/The-Alpha-Project/alpha-core/pull/499#pullrequestreview-1077270847
