### ISSUE TITLE
Quest item not recognized for completion after level

### ISSUE THREAD

**Issue by OrthoTemplar** [The-Alpha-Project/alpha-core#255]
**Description**
When a quest that tells you take this and report/send it to this other guy then level up and after that you can't finish the Q because it doesn't register as you having the item

**Steps to reproduce**
1. Take quest - Ex: [Report to Goldshire](https://classic.wowhead.com/quest=54/report-to-goldshire)
2. Level Up
3. When trying to complete quest, NPC shows that you need item from start of Q to complete Ex: [Marshal McBride's Documents
](https://classic.wowhead.com/item=745/marshal-mcbrides-documents)

**Expected behavior**
Quest is complete-able

Also happened with [Report to Thomas](https://classic.wowhead.com/quest=71/report-to-thomas)

**Comment by OrthoTemplar** [comment]
Also happens with gather item quests - [Thelsamar Blood Sausages](https://classic.wowhead.com/quest=418/thelsamar-blood-sausages)

**Comment by devwar87** [comment]
Can't reproduce any of the above, maybe someone else can test.

![image](https://user-images.githubusercontent.com/72774832/161307152-9d7404e2-3d01-42eb-987b-1cea2f31583e.png)

**Comment by GrenderG** [comment]
I haven't been able to reproduce the issue with any of the quests you mentioned @OrthoTemplar.

**Comment by devwar87** [comment]
Is there any extra steps you might be missing? Log out? Teleport somewhere? Abandon and re-taking the quest?

**Comment by OrthoTemplar** [comment]
Can no longer reproduce
