### ISSUE TITLE
Windrider quests can't be completed and flight path window appears instead

### ISSUE THREAD

**Issue by OrthoTemplar** [The-Alpha-Project/alpha-core#256]
**Description**
It tells you to bring a item to the griffin rider but he just shows you the flight paths when talking to him.

**Steps to reproduce**
1. Take quest that tells you to give a item to transport to X city - Ex: [Honor Students](https://classic.wowhead.com/quest=6387/honor-students) , [A Swift Message](https://classic.wowhead.com/quest=6181/a-swift-message)
2. When talking to Griffinrider he gives flight paths - Ex: [Thorgrum Borrelson](https://classic.wowhead.com/npc=1572/thorgrum-borrelson) , [Thor](https://classic.wowhead.com/npc=523/thor)

**Expected behavior**
See a screen to either select the quest for completion or see flight path screen

**Comment by GrenderG** [comment]
Since gossip options don't exist in 0.5.3 I guess the correct approach would be the same as with trainers: give priority to quests over FP window.

Note: check if vendors behave correctly or not too.
