### ISSUE TITLE
Equipped items that show as red question mark disappear on log out 

### ISSUE THREAD

**Issue by OrthoTemplar** [The-Alpha-Project/alpha-core#258]
**Describe the bug**
Equipped items that show as red question mark disappear on log out. (In inventory they are kept just fine)

**Steps to reproduce**
1. Equip red question mark item - Ex: [Ironheart Chain](https://classic.wowhead.com/item=3166/ironheart-chain)
2. Log out
3. Log in
4. Check character window, item is missing

**Expected behavior**
Item is still present and equipped.

**Comment by GrenderG** [comment]
This was done intentionally to prevent client crashing due to missing display_id. Although maybe there's a less destructive approach.

**Comment by GrenderG** [comment]
From now on you won't be able to equip items with wrong display id. https://github.com/The-Alpha-Project/alpha-core/commit/43d30d2f67910330669ed4b95f927dc4985e5add
