### ISSUE TITLE
Inventory Bug - Quiver and Bag if full have issues when swapping items inside the bag

### ISSUE THREAD

**Issue by OrthoTemplar** [The-Alpha-Project/alpha-core#267]
**Describe the bug**
When swapping arrows inside the quiver they remain dimmed and you can't interact  withe them until relog. It happens with same and different type of arrows.
**Steps to reproduce**
1. Drag arrow stack over another arrow stack in the same quiver

**Expected behavior**
Arrow stacks swap properly

**Screenshots**
![image](https://user-images.githubusercontent.com/102799057/161439947-1f7a406f-e852-4a07-b8ce-1cf6cab767f3.png)

**Comment by OrthoTemplar** [comment]
This happens only if quiver is full

**Comment by OrthoTemplar** [comment]
Has same issue with normal bags with any item

**Comment by GrenderG** [comment]
Should be fixed in https://github.com/The-Alpha-Project/alpha-core/commit/49856f013d0c835e03e06c81f12bd6753c333447.
