### ISSUE TITLE
Inventory Bug - Quivers and Bags if full have issues when swapping items outside the bag

### ISSUE THREAD

**Issue by OrthoTemplar** [The-Alpha-Project/alpha-core#268]
**Describe the bug**
When swapping arrow stacks outside the quiver (example main inventory) the arrow stack from outside the quiver are labeled as the ones inside the quiver (if different types) and the ones in the quiver remain(?) unchanged from before swap.
- If you want to drag any of the arrow stacks in previous interaction, both dim as like moving both. 
- if actually moved the one inside the quiver in the main inventory the previous one that was dimmed in the main inventory disappears visually.
- - If you drag the one that was previously inside the quiver on the "empty" slot it remains dimmed and can't interact.
- - If new item is put in "empty" slot the game recovers the item
- - If you logout while you have the "empty" slot, on relog the item slot is actually empty, losing the arrow stack.

**Steps to reproduce**
1. Swap arrow stack of type A with arrow stack B in main inventory. (Quiver has to be full)
2. Try to drag arrow stack from the quiver (from previous interaction) in main inventory
3. a. Drag the same arrow stack to slot that "emptied"
3. b. Drag any item to slot that "emptied"
3. c. Logout and login to observe arrow stack in slot that "emptied" is missing completely and non recoverable

**Expected behavior**
Arrow stacks swap inventory slots

**Screenshots**
2.
![image](https://user-images.githubusercontent.com/102799057/161440989-7783269c-9284-490b-b06b-f1bb13ef33c1.png)
![image](https://user-images.githubusercontent.com/102799057/161441018-3c05be89-35b1-4021-b9ce-d5f77779e9ab.png)
3. a.
![image](https://user-images.githubusercontent.com/102799057/161441039-b901c860-3aff-4a8d-9e1a-f062b3f2dbf2.png)
3. b.
![image](https://user-images.githubusercontent.com/102799057/161441053-948f24b4-ea1c-4bad-88d0-29755407397d.png)

**Comment by OrthoTemplar** [comment]
Has same issue with normal bags with any item

**Comment by GrenderG** [comment]
Should be fixed in https://github.com/The-Alpha-Project/alpha-core/commit/49856f013d0c835e03e06c81f12bd6753c333447.
