### ISSUE TITLE
Mage Ice Armor and Frost Armor can be active at the same time

### ISSUE THREAD

**Issue by OrthoTemplar** [The-Alpha-Project/alpha-core#272]
**Describe the bug**

**Steps to reproduce**
1. Cast [Frost Armor](https://classic.wowhead.com/spell=6116/frost-armor)
2. Cast [Ice Armor](https://classic.wowhead.com/spell=7302/ice-armor)

**Expected behavior**
Ice Armor should replace Frost Armor

**Screenshots**
![image](https://user-images.githubusercontent.com/102799057/161442963-73310d5a-848c-4951-a3cf-8196dd5e49e4.png)

**Comment by Fluglow** [comment]
Requires an entry for mage armors in `ExtendedSpellData.AuraSourceRestrictions`.

**Comment by OrthoTemplar** [comment]
Same thing for warlock [Demon skin](https://classic.wowhead.com/spell=687/demon-skin) and [Demon armor](https://classic.wowhead.com/spell=706/demon-armor)

**Comment by luigimannoni** [comment]
Tried to add the spell IDs a tthe AuraSourceRestrictions, however addaura seem to trigger twice, first adding the correctly aura then removing the armor buff immediately afterwards. Won't reapply any other buffs (or at least not visible in the combat log) unless logging in again.

![Screenshot from 2022-04-16 19-56-55](https://user-images.githubusercontent.com/1405327/163687976-0ae6a2cf-2733-4621-837f-97c000308a8f.png)

**Comment by luigimannoni** [comment]
Just being idiotic, armors have multiple aura indexes hence why was removing itself
