### ISSUE TITLE
Goldshire Inn - William Pestle & Innkeeper Farley Display ID & Positions

### ISSUE THREAD

**Issue by Yushe** [The-Alpha-Project/alpha-core#295]
I found these two screenshots in the archive while looking for the correct display id to another NPC.

These screenshots provide what William Pestle used to look like and that Innkeeper Farley used to be located next to the fireplace and was holding what seems to be a golden axe.

![Innkeeper](https://raw.githubusercontent.com/The-Alpha-Project/Alpha-Project-Archive/master/Images/Azeroth/Eastern%20Kingdoms/Elwynn%20Forest/wow04032416_1080105130.jpg)

![Innkeeper & William Pestle](https://raw.githubusercontent.com/The-Alpha-Project/Alpha-Project-Archive/master/Images/Azeroth/Eastern%20Kingdoms/Elwynn%20Forest/images_1274.jpg)

**Comment by Daribon** [comment]
William Pestle should have displayid 1689.
