### ISSUE TITLE
Stormwind - Zardeth of the Black Claw - missing weapon.

### ISSUE THREAD

**Issue by ghost** [The-Alpha-Project/alpha-core#296]
![MissingWeapon](https://user-images.githubusercontent.com/72774832/168490941-be340d40-3665-4f14-8330-b6b15dc238c2.jpg)

**Comment by Daribon** [comment]
I saw this in the march 2003 gameplay trailer when he still used the same model:
![mpc-hc64_ThJquOzMrl](https://user-images.githubusercontent.com/6137576/169889047-466b1fc1-8c88-4e73-95a0-e6d35046d765.png)
I have another screenshot that looks to be taken around same time as the screenshot in OP:
![WoW_041404_019_1081994556](https://user-images.githubusercontent.com/6137576/169889752-8fd726bc-6198-454e-a04d-de821dd9f22b.jpg)

**Comment by n67094** [comment]
Someone have an idea of the name, or the id of the dagger ?

**Comment by Daribon** [comment]
Only dagger I could find in the client that seems to resemble the model used in 2003 gameplay trailer is this one:
![wow-mdx-viewer_aVPhTJF2X3](https://user-images.githubusercontent.com/6137576/178886097-0b4bc09f-6dee-4c29-b189-042cd8502a93.png)

Knife_1H_Dagger_B_02.mdx
