### ISSUE TITLE
Orgrimmar - Missing Zeppelin Operator and Teleport Quest

### ISSUE THREAD

**Issue by ghost** [The-Alpha-Project/alpha-core#297]
![MissingZepOperator](https://user-images.githubusercontent.com/72774832/168491305-9ee0542b-c02e-4b7b-88f0-1725b7ca2b7e.jpg)

![7_images_6527](https://user-images.githubusercontent.com/72774832/168498214-391fbbe6-e875-437f-a6a2-035a2b40b6c8.jpg)

**Comment by Daribon** [comment]
Just noticed, he appears to be carrying a yellow flower.

**Comment by GrenderG** [comment]
Fixed in c465c8dee385051aa8b16ab50b25e721c399104d and bf74c8aaa9d9823aec5c7b9ffc6886cc3ebc5ab9.
