### ISSUE TITLE
Find infos about Corbett Schneider spawn

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#300]
Elaine Trias display_id and location were updated.
We need to find information about Corbett Schneider.

See discussion below.

**Comment by GrenderG** [comment]
Seems like she also was spawned a bit more on her left. Also... that NPC next to Ben Trias might be Elling Trias, right? Maybe he was not spawned up there.

**Comment by Daribon** [comment]
Image is likely from 0.5.5, considering there appears to be a dwarf player by the name Thorgrim in the general chat. However it might be a human player with a dwarf name, who knows.

**Comment by geo-tp** [comment]
![city01](https://user-images.githubusercontent.com/72315006/171966034-87fdeeec-ba3c-4991-b96d-81e3122e5031.jpg)

Unknown NPC seems to be Corbett Schneider (entry: 1433), we can se on the frame that he is near Elaine Trias/Ben Trias

**Comment by Daribon** [comment]
Good find. Another mystery solved.

**Comment by GrenderG** [comment]
I actually think Corbett Schneider was never permanently spawned. In Vanilla that NPC spawns in another house after completing quest `333` https://classic.wowhead.com/quest=333/harlan-needs-a-resupply and then proceeds to walk to some other houses, including the Cheese house. Then walks outside and despawn.... So the screenshot might have just captured the moment where that NPC was talking there?

![image](https://user-images.githubusercontent.com/8654362/182002340-08e085f0-3987-442e-8348-1f5f075a2845.png)

**Comment by geo-tp** [comment]
We have 3 pre release screenshots that show him actually, so i think he is spawned permanently.

**Comment by GrenderG** [comment]
> We have 3 pre release screenshots that show him actually, so i think he is spawned permanently.

Yeah it looks very likely that that was the case.

**Comment by Daribon** [comment]
The text used in the above screenshot is at low enough broadcast text entry to have been a scripted event in alpha.
```
('', 'Hi Corbett!  Here, you go!  I trust business is faring well at your clothier shop...?', 287, 7, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 31727),
('', 'Good day, Corbett.  Here\'s your cheese, fresh made this morning!  And how are things at your shop?', 286, 7, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 31727),
('Hullo, Trias clan!  A ball of your smoked mozzarella, if you please!', '', 285, 7, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 31727),
('Good day, Elling!  Hullo Elaine!  Let me have a wheel of bleu cheese, eh?', '', 284, 7, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 31727),
('Now for that snack...', '', 283, 7, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 31727),
```

**Comment by GrenderG** [comment]
Uh, indeed. I'm more confused now.

**Comment by geo-tp** [comment]
We can see Corbett Schneider in 0.5.5 WDB

```
Entry: 1433
Name: Corbett Schneider
StaticFlags: 0
CreatureType: 0
CreatureFamily: 0


Entry: 2671
Name: Mechanical Squirrel
StaticFlags: 1064966
CreatureType: 9
CreatureFamily: 0


Entry: 2675
Name: Explosive Sheep
StaticFlags: 0
CreatureType: 7
CreatureFamily: 0


Entry: 1319
Name: Bryan Cross
Title: Shield Merchant
StaticFlags: 102
CreatureType: 7
CreatureFamily: 0


Entry: 1292
Name: Maris Granger
Title: Skinning Trainer
StaticFlags: 102
CreatureType: 7
CreatureFamily: 0


Entry: 1321
Name: Alyssa Griffith
Title: Bag Vendor
StaticFlags: 102
CreatureType: 7
CreatureFamily: 0


Entry: 5565
Name: Jillian Tanner
Title: Leatherworking Supplier
StaticFlags: 102
CreatureType: 7
CreatureFamily: 0
```

**Comment by geo-tp** [comment]
See part of hand at right
![wow2p23](https://user-images.githubusercontent.com/72315006/187037477-a1085c94-ea59-4ba5-b919-8f0cfe7ee4c1.png)

Another screenshot where we can see Corbett Schneider spawned

**Comment by geo-tp** [comment]
This guy seems most likely spawned permanently.

- He is on every npc list from various sources (WoWCentral, Allakhazam, WorldOfWar...)
- He is on 4 pre releases screenshots we have
- It appears on every WBD files we have

![Capture d’écran_2022-12-26_16-04-38](https://user-images.githubusercontent.com/72315006/209571470-48f2f8f8-39c2-413a-b027-10b6c8dc1646.png)

**Comment by mindphluxnet** [comment]
Again - he's _not_ a permanent spawn but part of an ambient event that only occurs when a player hands in the quest "Harlan Needs A Resupply" to Corbett's wife, Mara:

![image](https://user-images.githubusercontent.com/4683319/224561871-b31943f9-933f-4c7a-b0e2-d82f5b8b68a8.png)

First, the quest end script terminates itself if Corbett Schneider is already spawned in a 100 yard radius. If not, it spawns Schneider next to his wife, they talk about him having to deliver goods to Harlan (that's what the quest was about), then the script sets Schneider's movement type to waypoints. Now, the waypoint movement script takes over: he'll go upstairs, fetch his stuff, walk to Harlan, deliver the goods and then go shopping at Trias's Cheese. Then he returns and despawns.

**Comment by GrenderG** [comment]
Yeah that's the expected Vanilla behavior, but we were unsure if the same happened in 0.5.3. Most likely it did and this Issue can be closed.

**Comment by mindphluxnet** [comment]
As Daribon commented the entire broadcast text has extremely low IDs so it's extremely likely this was present in 0.5.3
