### ISSUE TITLE
Can't attack critters with spells

### ISSUE THREAD

**Issue by Daribon** [The-Alpha-Project/alpha-core#304]
**Describe the bug**
If you try to cast a spell on a critter it will never damage the critter or make the critter aggro.
The mana is spent and the cast finishes, but nothing happens after that.

Auto attack works, not any spells.

**Steps to reproduce**
1. .tel goldshire
2. Cast any spell on a critter
3. Mana is spent but nothing happens after cast.

**Expected behavior**
Critter should take damage.

**Comment by Fluglow** [comment]
Same cause as #257.

**Comment by GrenderG** [comment]
> ![Critter](https://user-images.githubusercontent.com/108442943/177428612-4da7ab02-4063-489f-9813-123c8e6819d1.PNG)

That's interesting, really good find! I wonder what happened when you tried to auto attack them though... As the cursor has the sword icon. :thinking:
