### ISSUE TITLE
TODO: NPC display_id and equipement Teldrassil

### ISSUE THREAD

**Issue by n67094** [The-Alpha-Project/alpha-core#319]
Update display_id c.f images:

Just let me know if some aren't legit.

display_id 	shadowglen
![74_RcmSZnZ](https://user-images.githubusercontent.com/15613425/179799377-79bcc70c-a5d6-429f-a61f-437e75092f0a.jpeg)

display_id 	bloodfeather Rogue
![images_2149](https://user-images.githubusercontent.com/15613425/179799995-ddca71b5-dc5d-498c-884d-085a3b402366.jpg)

display_id 	bloodfeather Sorceress
![images_2150](https://user-images.githubusercontent.com/15613425/179800020-ecd5dfa6-e495-4cb3-a52c-96a9efa06149.jpg)

display_id 	teldrassil sentinel
![jokey_WoWScrnShot_041704_231459_resize](https://user-images.githubusercontent.com/15613425/179799920-c1ae7155-3ef9-49ac-a106-7f273688b50b.jpg)
![jokey_WoWScrnShot_041704_225325_resize](https://user-images.githubusercontent.com/15613425/179799960-f3f3571b-f85c-4381-a65b-b7443cbb93ac.jpg)

display_id 	Syral bladeleaf
Weapon		Syral bladeleaf
![jokey_WoWScrnShot_041804_002033_resize](https://user-images.githubusercontent.com/15613425/179799831-e6f610ef-0734-4f2c-8230-31e23fe1fd6d.jpg)

Weapon 		Athridas Bearmantle
![wowpc_032504_022](https://user-images.githubusercontent.com/15613425/179800834-b0f20cce-fc88-4b08-87e6-b246740edfc3.jpg)

display_id        zeen foulhoof
![worldofwarcraft_040904_001](https://user-images.githubusercontent.com/15613425/179800896-f3fb002c-3a90-40be-86e6-700aa257116d.jpg)
 	
disaply_id 	Strigid Owl
![worldofwarcraft_040904_002](https://user-images.githubusercontent.com/15613425/179800975-3c16d5b2-77b2-4a2b-9eec-dbadcc340feb.jpg)

**Comment by n67094** [comment]
Erratum:
- It seems that there no display_id or substitue for Strigid Owl
- Some of the Teldrassil sentinel have display_id that I can´t find (the one with long white hair, img 5) after many iteration, substitue (+- 15 !=) can be used

**Comment by n67094** [comment]
Melithar Staghelm  and Hyacinth Mushroom don´t have the right display id, I didn´t find them :/

**Comment by mindphluxnet** [comment]
Can be closed, everything has been fixed by now.
