### ISSUE TITLE
Gilbin (presumably) has Wrong Faction

### ISSUE THREAD

**Issue by Dovvah** [The-Alpha-Project/alpha-core#341]
Gilbin <Light Armor Merchant> at XYZMapid  ` -4850 -1003 494 0` has the wrong faction set and is able to be attacked by alliance players.

Wanted to buy some armor, right clicked and murdered him :(

https://puu.sh/JedSo/caab5b969d.jpg

**Comment by Fluglow** [comment]
Laene Thundershot (5104), gun/ammo vendor in Ironforge at `-4884 -952 496 0` is also attackable.
