### ISSUE TITLE
Stacked on-use items consume the entire stack

### ISSUE THREAD

**Issue by Yushe** [The-Alpha-Project/alpha-core#351]
When using an item that is stackable and has an on-use effect it will consume the entire stack of that item.
An example of this bug in action can be performed by using item id 1251, Linen Bandage.

**Comment by Dovvah** [comment]
Have not had this issue myself even using the same linen bandages.

**Comment by GrenderG** [comment]
I'm testing it and seems like it's consuming 2 items at once (i.e. you have 3, and after using it once you'll be left with 1).

**Comment by GrenderG** [comment]
Also for some reason I can only use them in other units, not in myself. :thinking:

**Comment by Dovvah** [comment]
> I'm testing it and seems like it's consuming 2 items at once (i.e. you have 3, and after using it once you'll be left with 1).

confirming this

**Comment by Dovvah** [comment]
but this doesn't happen with Rough Sharpening Stone (2862)

**Comment by Yushe** [comment]
> Also for some reason I can only use them in other units, not in myself. 🤔

Strange because it worked fine for me when I clicked on myself.
