### ISSUE TITLE
TODO: Implement Professions and Weapon Trainers

### ISSUE THREAD

**Issue by Dovvah** [The-Alpha-Project/alpha-core#361]
**Describe what needs to be implemented or enhanced**
Professions and Weapon skills should be taught by Profession Trainers and Weapon Masters respectively, The trainer must teach the player both the skill and profession spell. 

Ex: To learn Two Handed Swords skill the player learns skillid = 55 and spellid=202. 

Note: There exists spells such as 3831(2h axes), 3833(2h maces) and 3835(2h swords) which can be cast on the player to teach the skill and spell simultaneously, but these don't seem to exist for professions.

**Comment by GrenderG** [comment]
I believe @radongc has this implementation more or less ready, hopefully he can open a PR but I haven't heard from him for a long time.

**Comment by radongc** [comment]
I believe this issue can be closed, as profession trainers are implemented and weapon skills are taught by class trainers.
