### ISSUE TITLE
It's not possible to obtain druid's Bear Form

### ISSUE THREAD

**Issue by sadpanda353** [The-Alpha-Project/alpha-core#363]
**Describe the bug**
Quest dosen't provide spell ''teleport to moonglade'' wich is not even in the .lspell command and NPC ''Dendrite Starblaze'' dosen't exist so we can't turn in the quest to go further in the chain. The only way to get the bear form is by command.

**Steps to reproduce**
1. create a night elf level 10, go to cenarrus enclave in Darnassus
2. accept part 1 and turn it upstairs
3. teleport to moonglade to find Dendrite Starblaze (wich is not there)

**Expected behavior**
when accepting the second part you are suppose to learn ''Teleport: Moonglade'' and once there is suppose to be an NPC to turn in but it is empty.

**Screenshots**
![NoPortLearn](https://user-images.githubusercontent.com/110544187/182683070-b1032afa-9bab-4097-8fbd-34c5012f3a89.png)

![Empty](https://user-images.githubusercontent.com/110544187/182683096-a3f704be-2368-4d67-9a26-c4efd88ff9dc.png)

**Sources**
![ShouldBe](https://user-images.githubusercontent.com/110544187/182683132-8439cd77-c71b-494a-8587-a840af52e217.png)

**Comment by Yushe** [comment]
Since the quest category is blank and the spell doesn't exist in the game this indicates that the quest shouldn't exist in the alpha.
I think all the class quests aren't in the game at this point.

**Comment by sadpanda353** [comment]
Yeah i think you are right priest class quest dosen't exist either so its probably affect all class quest

**Comment by GrenderG** [comment]
The quest has been removed since it doesn't belong to 0.5.3. However I have noticed that without it, there's no way to learn Bear Form. Either we are missing a 0.5.3 quest that added it, or it's missing from the Trainer.

**Comment by sadpanda353** [comment]
I think it just not there in alpha, im just usine logic but bear got only 1 ability and basic attack prob mean there were just not out yet in 0.5.3

**Comment by GrenderG** [comment]
Bear form was added to trainers in https://github.com/The-Alpha-Project/alpha-core/pull/658
