### ISSUE TITLE
Can gather anything at any level

### ISSUE THREAD

**Issue by sadpanda353** [The-Alpha-Project/alpha-core#368]
**Describe the bug**
I can mine iron ore at level 1 mining (lvl 125 ore) it probably apply to other gathering tradeskill too (not tested yet)
**Steps to reproduce**
1. create a character and learn mining
2. get a mining pick and find a node higher level than your skill

**Expected behavior**
I should not be able to mine iron ore until level 125 mining but on the picture i can at level 1

**Screenshots**
![MineAllAnyLvl](https://user-images.githubusercontent.com/110544187/182729413-515b7f27-a709-4bcc-8c95-f8e11834e095.png)

**Sources**
![IronLevel](https://user-images.githubusercontent.com/110544187/182729492-607280fe-f2ec-48a8-a28c-a0da73a04e3a.png)

**Comment by GrenderG** [comment]
![image](https://user-images.githubusercontent.com/8654362/182731271-8192a203-7845-40e6-8927-dca6be33fc54.png)
Seems like you have extra/wrong mining spell(s) that give you a permanent bonus. For example the Mining spell 2578 will always perform the mining with 100 bonus points; and 100 is the required skill for that vein in 0.5.3.

If you only have the normal Mining spell (2575) it will work fine. :+1:
