### ISSUE TITLE
Kobold Geomancer 1 shot

### ISSUE THREAD

**Issue by sadpanda353** [The-Alpha-Project/alpha-core#369]
**Describe the bug**
Killed by 1 fireball of a lvl 8 Kobold Geomancer... He did 160 damage, got there a second time and got a 174 this time.

Edit: getting the same issue with Defias Rogue Wizard near the Logging Camp, 95-96 dmg frost bolt and its a fast cast.

**Steps to reproduce**
1. Go to The Jasperlode Mine.
2. Engage a lvl 8 Kobold Geomancer.
3. Wait for the fireball

**Expected behavior**
Not getting 1 shot (2 shot with defias)

**Screenshots**
![1HitKo](https://user-images.githubusercontent.com/110544187/182749217-1d6480c3-5dfd-46fb-b5a8-77f0fb79ea4a.png)

![defias1Shot](https://user-images.githubusercontent.com/110544187/182762074-0783e143-ca3a-41db-a715-2c83806966a4.png)

**Comment by Yushe** [comment]
This isn't a one shot but the Kobold's spell might be overtuned?
I went on my level 100 test character and it hit me for 181 then 149.

**Comment by GrenderG** [comment]
See my answer in https://github.com/The-Alpha-Project/alpha-core/issues/374, they use the same Spell ID (145). My assumption is that all mobs using Spell 145 in Vanilla should use 143 in 0.5.3.
