### ISSUE TITLE
The gnolls near Hogger bug out when you kill them while they have enrage up.

### ISSUE THREAD

**Issue by Farador1** [The-Alpha-Project/alpha-core#371]
**Describe the bug**
If you get a killing blow on a gnoll near Hogger while it has enrage up, it will simply stop attacking and you are unable to attack it further. It is not lootable in this state.

**Steps to reproduce**
1. Attack the gnolls and wait for them to use enrage.
2. Land a killing blow while enrage is up.
3. ...

**Expected behavior**
They are supposed to die regardless of whether they are enraged or not.

**Screenshots**
If needed, add screenshots to help explain your problem.

**Sources**
If needed, provide valid sources (original screenshots or videos, archived allakhazam...) that show what's the expected behavior or state.

**Comment by GrenderG** [comment]
This should be fixed already. https://github.com/The-Alpha-Project/alpha-core/pull/344

**Comment by Farador1** [comment]
Ah yes, it is indeed fixed. My mistake.
