### ISSUE TITLE
Defias Pillagers in Moonbrook do way too much damage.

### ISSUE THREAD

**Issue by Farador1** [The-Alpha-Project/alpha-core#374]
**Describe the bug**
I was doing a quest to kill the Defias Pillager in Moonbrook and got oneshot by their spells several times.

**Steps to reproduce**
1. Let a Defias Pillager cast a fireball on you.
2. ...
3. ...

**Expected behavior**
I'm pretty certain their fireballs are not supposed to do 160+ damage.

**Screenshots**
If needed, add screenshots to help explain your problem.

**Sources**
If needed, provide valid sources (original screenshots or videos, archived allakhazam...) that show what's the expected behavior or state.

**Comment by GrenderG** [comment]
They are using the same spell as in Vanilla at this moment (ID 145), but that Spell does indeed more damage in 0.5.3 (`EffectBasePoints_1` is 146 in 0.5.3). They were probably using Spell 143 instead that has 59 as `EffectBasePoints_1`. That would match the damage seen in the log of this screenshot.
![image](https://user-images.githubusercontent.com/8654362/182831773-0339f143-afa5-4494-b4d0-cf10defa134f.png)

**Comment by GrenderG** [comment]
> It appears that mob spellcasters might be using Vanilla spells across the board. I encountered Tunnel Rat Geomancers in the mine to the east of the northern guard tower in Loch Modan that also did insanely high damage, as well as the dragon whelps in Redridge.

Yes, they are using 1.2 spells.
