### ISSUE TITLE
[Tirisfal Glades] Missing display id for Deathguard Lundmark

### ISSUE THREAD

**Issue by n67094** [The-Alpha-Project/alpha-core#392]
At Brill graveyards
They are dabiri's blocks for:
- ~~summoning circle (+- in the center of the graveryards)~~
- ~~doors interaction (+- in the center of the graveyards)~~
- deathguard lundmark display id (a the entrance of the graveyards)

~~At DeathKnell~~
- ~~Samuel Fipps entry id: 1919, for the quests Marla's last whish -> samuel's remains never drop~~

**Comment by GrenderG** [comment]
- Summoning circles should be removed and door interaction gameobjects most likely too as the [NPC of that quest](https://classic.wowhead.com/npc=6390) has a high entry.
- Deathguard Lundmark was in 0.5.3 as he appears in the original WDB but we don't know what's his display_id.
- Marla's Last Wish quest should be removed along with Samuel's Remains and the grave gameobject, they weren't in 0.5.3.

**Comment by mindphluxnet** [comment]
Do we have a screenshot showing him? The screenshot on Classic Wowhead can't be matched with what male undead display_ids exist.

**Comment by mindphluxnet** [comment]
How about using 1021 for Lundmark? 

![image](https://user-images.githubusercontent.com/4683319/227500251-ce5cdb72-b34e-433a-b33c-b1ec88c81b19.png)

In the MPQ the model is in a folder called "TEMPDeathGuard" which sounds like it might be the "official" placeholder Blizzard used. It's fully skinned and animated.

**Comment by geo-tp** [comment]
> How about using 1021 for Lundmark?
> 
> ![image](https://user-images.githubusercontent.com/4683319/227500251-ce5cdb72-b34e-433a-b33c-b1ec88c81b19.png)
> 
> In the MPQ the model is in a folder called "TEMPDeathGuard" which sounds like it might be the "official" placeholder Blizzard used. It's fully skinned and animated.

It makes sense

We can see here that this model is linked with other placeholders

1023 and 1025 are probably Hearthglen placeholder
1027 & 1029 are undead placeholder

![Capture d’écran_2023-03-24_14-24-47](https://user-images.githubusercontent.com/72315006/227533334-b4cae280-e963-4642-8285-a4e0ed2e163b.png)
![Capture d’écran_2023-03-24_14-26-39](https://user-images.githubusercontent.com/72315006/227533573-afff1727-c601-49ed-b008-7d94eed4ee6e.png)
![Capture d’écran_2023-03-24_14-27-01](https://user-images.githubusercontent.com/72315006/227533593-eb8279f1-b6d7-4874-878f-a55bf68b252e.png)

**Comment by mindphluxnet** [comment]
Exactly, they are even named like that in the files:

![image](https://user-images.githubusercontent.com/4683319/227534095-2a9aa9f3-c97b-4065-a5a0-fba881298053.png)

**Comment by geo-tp** [comment]
![septembre2003-48](https://user-images.githubusercontent.com/72315006/228614856-f093798e-08aa-4392-ab1e-c1835a2e9b88.jpg)

Seems to be the model we see here as placeholder for Deathguard, from Sept 2003
