### ISSUE TITLE
Warlock's Low Level Summon Imp Uses Max Rank Spells + Spellbook placement issue

### ISSUE THREAD

**Issue by Yushe** [The-Alpha-Project/alpha-core#397]
1. When a new character first learns summon imp there imp has max rank spells making it very easy to one shot everything.

2. There is another tab in the spellbook called `Demon` which I assume is meant to be where Summon Imp and other demon spells are meant to be located.

**Comment by Fluglow** [comment]
Related to pet behavior still being very incomplete (#281). Pet spells/abilities should be in the Demon/Pet tab that appears when the player has one active. Added filling the tab to #281.
