### ISSUE TITLE
TODO: Investigate inconsistencies about where/how to learn some class spells

### ISSUE THREAD

**Issue by GrenderG** [The-Alpha-Project/alpha-core#398]
**Describe what needs to be implemented or enhanced**
For example, at this moment as a Warlock you are able to learn the Summon Imp spell in two ways: either by trainer at level 1 or by completing the https://classic.wowhead.com/quest=1470/piercing-the-veil quest. I assume this is also happening with other spells for other races that are learnt through quests.

**Expected end result**
There should only be one possible way to learn a spell, we need to determine if spells that can be learned through quests need to be removed form trainers. I assume this is the case at least for Summon Imp.

**Comment by sadpanda353** [comment]
i did a warlock like 4-5 days ago a the quest was not there i swear i could only learn it by trainer at lvl 1, could it come from a recent merge ?

**Comment by GrenderG** [comment]
Well I only tested it with an Undead warlock, what race were you playing?

**Comment by sadpanda353** [comment]
human i just did it and the quest is there wich im pretty sure was not few days ago
