### ISSUE TITLE
Thawarting Kolkar Aggression

### ISSUE THREAD

**Issue by ContentRated** [The-Alpha-Project/alpha-core#400]
**Describe the bug**

**Steps to reproduce**
1. ...Quest not allowing item pick up
2. ...Orc Rouge 
3. ...Attack Plan: Sen' Jin Village

**Expected behavior**
Item pick up to complete quest
**Screenshots**
If needed, add screenshots to help explain your problem.

**Sources**
If needed, provide valid sources (original screenshots or videos, archived allakhazam...) that show what's the expected behavior or state.

**Comment by GrenderG** [comment]
Fixed in https://github.com/The-Alpha-Project/alpha-core/pull/388, PTR will be updated soon with this fix.
