### ISSUE TITLE
Map Error Origrimmar 

### ISSUE THREAD

**Issue by ContentRated** [The-Alpha-Project/alpha-core#401]
**Describe the bug**

**Steps to reproduce**
1. ...Walking into "cleft of shadows"
2. Map goes under ther city 
3. ... same on 2 different toons 
4. ...

**Expected behavior**
go to the "cleft of shadows"
**Screenshots**
If needed, add screenshots to help explain your problem.
![Uploading Screenshot (4).png…]()

**Sources**
![Screenshot (5)](https://user-images.githubusercontent.com/110740388/183263661-4febb4fe-1eb2-4544-a310-f338b7a6e364.png)

If needed, provide valid sources (original screenshots or videos, archived allakhazam...) that show what's the expected behavior or state.

**Comment by ContentRated** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/110740388/183263754-95a5a27e-d3eb-4ce6-ab93-79f78dc1d90e.png)

didnt upload first image

**Comment by ContentRated** [comment]
map is the voodoo lounge on the mini map

**Comment by devw4r** [comment]
Yeah, this is all client related, can't be fixed server side.
