### ISSUE TITLE
Hogger won't die sometime

### ISSUE THREAD

**Issue by sadpanda353** [The-Alpha-Project/alpha-core#402]
**Describe the bug**
Hogger was left at 1 hp for somewhere between 30 sec to 1 min, we were hitting him really fast like 5 hit a sec then Pod needed to alt + f4 and relog to debug him.

**Steps to reproduce**
1. get a group of 2
2. try to kill hogger and see if he die 
3. 

**Expected behavior**
Should just die when HP drop to 0

**Screenshots**

![HoggerBug](https://user-images.githubusercontent.com/110544187/183264925-f73fcfea-040d-4faa-9470-dc359c49fc9c.png)

**Comment by GrenderG** [comment]
Should be fixed in https://github.com/The-Alpha-Project/alpha-core/commit/9bcb0b57fcfa9a9a2c7e34b5fa55e892fb8ad0af.
