### ISSUE TITLE
Quest ammo for rumbleshot not working

### ISSUE THREAD

**Issue by sadpanda353** [The-Alpha-Project/alpha-core#404]
**Describe the bug**
You can pick the quest and loot the item (wich is an ''?'' item) but the npc to turn in dosen't exist.

**Steps to reproduce**
1. Do the quest ammo for rumbleshot in Kharanos.
2. try to go turn in.

**Expected behavior**
There should be an npc called Hegnar Rumbleshot on the road south of Kharanos to turn in or the item should not be lootable.

**Screenshots**
![ItemQuest](https://user-images.githubusercontent.com/110544187/183272483-b61cee18-d617-4cec-b983-78d676176b84.png)

![TurnIn](https://user-images.githubusercontent.com/110544187/183272486-9eaac6ce-4b02-477a-92d2-a807e19e67d2.png)

**Comment by GrenderG** [comment]
I think Hegnar Rumbleshot is actually spawned but he's falling below the ground, need to fix his Z or find his correct position.

**Comment by X-Genesis-Qhulut** [comment]
Suggest:

```
 update spawns_creatures set position_z = 408.804 where spawn_id = 265;
```
