### ISSUE TITLE
Defias Trapper net abilitie 

### ISSUE THREAD

**Issue by sadpanda353** [The-Alpha-Project/alpha-core#408]
**Describe the bug**
Their net abilitie stay 1 sec then goes off, classic wowhead say 5 or 10 sec. I have no evidence for that spell duration in alpha but it feel wrong.

**Steps to reproduce**
1. Fight a defiace Trapper south of sentinel hill, westfall.

**Expected behavior**
Maybe should have the same duration as classic ?

**Screenshots**
![5sec](https://user-images.githubusercontent.com/110544187/183274976-2ffc3478-4d6b-4469-96fb-4af2a82801a2.png)
![10sec](https://user-images.githubusercontent.com/110544187/183274977-2a64dbd5-62a3-4b5a-b77d-3841e50692e2.png)

**Comment by Fluglow** [comment]
The spell actually has a 15 second duration in alpha. It breaks whenever you receive damage, which might appear like a short duration if you're fighting the npc.
