### ISSUE TITLE
Trogg scout keep throwing when in melee range

### ISSUE THREAD

**Issue by sadpanda353** [The-Alpha-Project/alpha-core#412]
**Describe the bug**
The Trogg Scout in Loch Modan keep using throwing skill when in melee range + he do his actual melee damage so you get a lot of hit wich is bad for us caster with that knockback on spellcasting. (In the picture look at the combat log you will see melee hit, throwing then melee again)

**Steps to reproduce**
1. Fight a Trogg Scout in Loch Modan.

**Expected behavior**
They should not be able to use throw ability when in melee range.

**Screenshots**
![TroggScout](https://user-images.githubusercontent.com/110544187/183291974-9ded2c7a-397f-445d-9952-8340c35d290a.png)

**Comment by Yushe** [comment]
This is just to do with NPC ai still being in development, caster NPCs have this same exact issue.

**Comment by sadpanda353** [comment]
I get what you are saying but its not really the same issue since you can cast spell in melee range without issue but gun/bow/throwing need a certain distance to be used

**Comment by devw4r** [comment]
Spell min and max range is defined by client data. In the case of Throw (2764), Min range 0, Max range 30. So this is not a bug.
