### ISSUE TITLE
Something worng with that npc

### ISSUE THREAD

**Issue by sadpanda353** [The-Alpha-Project/alpha-core#413]
**Describe the bug**
Look at the picture, no need to say more.. (location Thelsamar, Loch Modan)

**Expected behavior**
Not having a cube as a hat.

**Screenshots**
![mehhhh](https://user-images.githubusercontent.com/110544187/183293072-a148185f-410f-4cb8-8e52-c6363429a6b9.png)

![mehhhh2](https://user-images.githubusercontent.com/110544187/183293039-2371c44b-c341-4715-b79c-ea2aa9597ff7.png)
om/110544187/183293038-6ddd2f59-8606-43b7-884c-f7db60928cb6.png)

**Comment by Yushe** [comment]
https://classic.wowhead.com/npc=1105/jern-hornhelm
Just like his name suggests he is meant to wear a horned helmet but I guess it changed displayid before release.

**Comment by geo-tp** [comment]
![images_3730](https://user-images.githubusercontent.com/72315006/184278833-8f6c0761-df79-49a9-936b-703226803bb9.jpg)

**Comment by GizzleBizzle** [comment]
The last screenshot is from patch 0.5.5, so either that model was finished between the leak and patch 0.5.5 or it used a different model/placeholder at that time.

There aren't any screenshots prior to 0.5.5 in the catalogue. This means this topic will become a standstill for some time.

I suggest changing the topic's name to something along the lines of "Jern Hornhelm's Model/DisplayID" to prevent people in the future making the same report over and over.
