### ISSUE TITLE
Mana tick is higher in combat 

### ISSUE THREAD

**Issue by sadpanda353** [The-Alpha-Project/alpha-core#415]
**Describe the bug**
i get 4 mana per tick out of combat and 6 per tick in combat,
EDIT: Added 2 picture, look at the chat someone did some test there is something wrong.

**Steps to reproduce**
1. use mana and test both

**Expected behavior**
Prob just inverted ? should be 4 in combat and 6 out of combat

**Screenshots**
![mana](https://user-images.githubusercontent.com/110544187/183301084-d2b0ec03-3b89-4a4b-8f70-330d4a9dbba8.png)
![mana2](https://user-images.githubusercontent.com/110544187/183301089-3496ddd3-cbda-4774-95d1-c4ffc505da97.png)

**Comment by GrenderG** [comment]
I can confirm mana regeneration doesn't seem to be accurate at this moment at least compared to Vanilla. For reference I'm leaving this here: https://vanilla-wow-archive.fandom.com/wiki/Mana_Regeneration

Things to note: Five seconds rule and no mana regeneration at all while casting (at least according to that wiki).
