### ISSUE TITLE
TODO: Remove elevators in Thousand Needles

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#416]
**Describe what needs to be implemented or enhanced**
We can see elevators here, but there are probably not part of 0.5.3.
![Capture](https://user-images.githubusercontent.com/72315006/183305125-9dbda5d6-a16e-4051-83d7-ff855f1634e9.PNG)
![Capture3](https://user-images.githubusercontent.com/72315006/183305384-a6a107fd-2c85-4b06-9f9b-fb194f3a1da7.PNG)

Instead in 0.5.3 there is a path to go to the village
![capture2](https://user-images.githubusercontent.com/72315006/183305142-8b33c107-d583-4ab5-86c7-3d391c6669f6.png)

**Expected end result**
Elevators in Thousand Needles shouldnt be spawned, remove both.

**Comment by diff3** [comment]
To remove the elevators to Freewind post:

UPDATE `spawns_gameobjects` SET `ignored`='1' WHERE `spawn_id`='16875';
UPDATE `spawns_gameobjects` SET `ignored`='1' WHERE `spawn_id`='16877';
