### ISSUE TITLE
Murloc Oracles on the Longshore in Westfall cast Holy Smite while running.

### ISSUE THREAD

**Issue by Farador1** [The-Alpha-Project/alpha-core#419]
**Describe the bug**
The Murloc Oracles on the Longshore in Westfall can cast their Holy Smite ability while running after the player.

**Steps to reproduce**
1. Aggro a Murloc Oracle.
2. Start running away from them and they will cast it while chasing you.
3. ...

**Expected behavior**
I assume Holy Smite should not be castable while they are chasing after you.
**Screenshots**
If needed, add screenshots to help explain your problem.

**Sources**
If needed, provide valid sources (original screenshots or videos, archived allakhazam...) that show what's the expected behavior or state.

**Comment by GrenderG** [comment]
Not 100% sure but this might be affecting all creatures, I think their casts are not being cancelled on movement. @Fluglow can you confirm if this is missing for all creature casts?
