### ISSUE TITLE
Defensive Stance does not generate rage

### ISSUE THREAD

**Issue by Yushe** [The-Alpha-Project/alpha-core#425]

**Comment by geo-tp** [comment]
Defensive Stance (71): "A defensive stance that reduces rage decay when out of combat. Generate rage when you are hit."
Battle Stance (2457): "A balanced combat stance. Generate rage when hit and when you strike an opponent."
Berserker Stance (2458): "An aggressive stance. Generate rage when you strike an opponent."

Defensive stance generates rage only on hit
