### ISSUE TITLE
[Paladin] Seal of Salvation can't be buffed on party members

### ISSUE THREAD

**Issue by Kabedox** [The-Alpha-Project/alpha-core#441]
**Describe the bug**
You can't buff party members with Seal of Salvation. (The Paladin can buff him-/herself though)

**Steps to reproduce**
1. Invite someone into a group
2. Try to buff said party member with Seal of Salvation

**Expected behavior**
You should be able to buff party members by clicking on their characters or by clicking their character portrait just like other Seals.

**Screenshots**

**Sources**

**Comment by Farador1** [comment]
Just as a little side note, even though it is a higher level spell, the same problem exists for Seal of Sacrifice.
