### ISSUE TITLE
[Shaman] Totems are not functional.

### ISSUE THREAD

**Issue by Farador1** [The-Alpha-Project/alpha-core#443]
EDITED BY Grender, see https://github.com/The-Alpha-Project/alpha-core/issues/443#issuecomment-1213401709.
---

**Describe the bug**
When you summon totems, they don't do anything and they just follow you around. None of the totems do what they're supposed to. There is also no limit to how many totems you can drop, and they never despawn. They don't even despawn when you log out but they do stop following you and remain stationary when you do that.

**Steps to reproduce**
1. Make a shaman.
2. Summon a bunch of different totems.
3. ...

**Expected behavior**
Totems are supposed to remain stationary where you drop them and only remain for the duration specified on the spell's tooltip. They are also supposed to do have whatever effect the tooltip specifies, which currently they do not.
**Screenshots**
![image](https://user-images.githubusercontent.com/110574922/183930063-b08607de-c9d5-4c91-8757-59d41058a630.png)

**Sources**
If needed, provide valid sources (original screenshots or videos, archived allakhazam...) that show what's the expected behavior or state.

**Comment by GrenderG** [comment]
Reopening this as there are still some issues:
1. Summoning a totem of the same type should despawn any existing one.
2. Their spells/auras doesn't seem to properly work.

**Comment by GrenderG** [comment]
Completed with https://github.com/The-Alpha-Project/alpha-core/pull/874
