### ISSUE TITLE
[Shaman] Issues with Lightning Storm's spell.

### ISSUE THREAD

**Issue by Farador1** [The-Alpha-Project/alpha-core#444]
**Describe the bug**
When you use Lightning Storm, its damage ticks too fast and kills mobs almost instantly. It also only appears to be using the initial tick damage and not the lower damage it's supposed to do after the initial tick.

**Steps to reproduce**
1. Make a shaman.
2. Use Lightning Storm on a mob.
3. ...

**Expected behavior**
Lightning Storm is supposed to do a certain amount of damage on its first tick and then do lower damage spread out over 15 seconds according to its tooltip.

**Screenshots**
If needed, add screenshots to help explain your problem.

**Sources**
If needed, provide valid sources (original screenshots or videos, archived allakhazam...) that show what's the expected behavior or state.

**Comment by GrenderG** [comment]
To add on this issue, at this moment the damage is received by the caster instead of the desired targets.
