### ISSUE TITLE
Can hit/cast when stunned

### ISSUE THREAD

**Issue by sadpanda353** [The-Alpha-Project/alpha-core#452]
**Describe the bug**
Blackwood Windtalker in Darkshore cast a stun but you can hit them or cast them spells when you are ''stunned'' you just can't move.

**Steps to reproduce**
1. let them stun you
2. hit/cast spell
3. ...

**Expected behavior**
Not be able to attack/cast when stunned.

**Screenshots**

![Windwalker](https://user-images.githubusercontent.com/110544187/184078521-c58f245f-4b95-4de8-a323-9813f330c8bf.png)

**Comment by Yushe** [comment]
This is actually a general bug to do with being stunned.
Yesterday after Farador and GizBiz had there honorable duel we messed around testing mechanics in duels and we eventually found out that you could still cast spells & abilites while stunned.

**Comment by GrenderG** [comment]
For the record: in 0.5.3 it was possible to use items while stunned, but casting should indeed not be possible.

**Comment by sadpanda353** [comment]
Good to know ! (It goes the same with ability and basic attack)
