### ISSUE TITLE
TODO: Change Writhing Highborn display_id

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#455]
**Describe what needs to be implemented or enhanced**
Writhing Highborn use ghostl actually, she should use ghost and Banshee model.

screenshot
![7 APRIL 04 azhar23](https://user-images.githubusercontent.com/72315006/184179168-9db09a5f-2d0d-4d2d-af75-3cec0b99e010.jpg)
![image](https://user-images.githubusercontent.com/72315006/184468031-a9073326-2dec-422f-97de-f402510e48cf.png)

**Expected end result**
2177 Writhing highborn should use 1009 as display_id2

**Guidance**
```
-- Writhing Highborne
UPDATE `creature_template`
SET `display_id2`=1009
WHERE `entry`=2177;
```

**Comment by GrenderG** [comment]
We assumed for now that this NPC was using 2 different display ids as the screenshots seem to be from the same patch. We might be wrong, however.
