### ISSUE TITLE
"Journey to Booty Bay!" & "Journey to Ratchet!" don't teleport you

### ISSUE THREAD

**Issue by Yushe** [The-Alpha-Project/alpha-core#456]
When you turn in these quests the appropriate NPC does that casting animation but you don't get teleported.

All the other placeholder "quests" that teleport you work fine.

**Comment by GrenderG** [comment]
![image](https://user-images.githubusercontent.com/8654362/185751862-9272eed0-11f6-4255-952e-9d2e187a37b3.png)
We have screenshots showing that they were friendly, so updating the faction to 35 will fix this.
