### ISSUE TITLE
TODO: Find and change Race Master Kronkrider display_id (Thousand Needles)

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#457]
**Describe what needs to be implemented or enhanced**
4419 Race Master Kronkrider miss his display_id
Find and change Konkrider display_id.

He is dwarf, probably old model here, but it's unsure
![27 APRIL  04 - 167](https://user-images.githubusercontent.com/72315006/184225819-6be93676-bcba-4a75-8096-630c0cbbf1fd.jpg)

**Expected end result**
4419 Race Master Kronkrider should use correct display_id as screenshot show

**Comment by mindphluxnet** [comment]
Maybe he just didn't have a proper model in 0.5.3 yet? Thousand Needles has seen several passes - in 0.8 and 0.10 - so it's more than likely that Race Master Kronkrider is supposed to be a placeholder in 0.5.3. I also went to Shimmering Flats myself and it's definitely extremely unfinished. I could not find any creature template in the database matching his supposed look either which is pretty simple to do as he is wearing a very distinctive hat and beard. There are only two male dwarf creature templates with that hat and they both miss his fiery red twin braid beard.

The archive has several screenshots showing him but they are all from later builds of the alpha.

**Comment by geo-tp** [comment]
Never found this model as well.
Since other NPCs around all use placeholder models (gnomes, goblins, ogres...), this dwarf should probably use dwarf placeholder.

![Capture d’écran_2023-03-18_02-52-45](https://user-images.githubusercontent.com/72315006/226077111-3a8c012e-dc85-4967-aa31-d07c44ae26d9.png)

Vast majority of missing display_id for dwarf have been resolved by this placeholder
