### ISSUE TITLE
[Paladin] Auras sometimes disappear when starting to eat or drink

### ISSUE THREAD

**Issue by Kabedox** [The-Alpha-Project/alpha-core#463]
**Describe the bug**
Auras sometimes disappear when starting to eat or drink after a battle.
I've tried it with every aura and it shows the same behaviour.
Sometimes it's the food and sometimes it's the drink causing it to disappear.
It doesn't seem to happen when you didn't engage in a battle in advance.

**Steps to reproduce**
1. Fight something
2. Eat and/or drink to recover health or mana
3. Aura disappears (sometimes)

**Expected behavior**
The Aura should not disappear.

**Sources**
Video 1 - Aura disappears: 
https://www.youtube.com/watch?v=h5DbftBlWSs
Video 2 - Aura doesn't disappear:
https://www.youtube.com/watch?v=v3adfKrGL5w

**Comment by sadpanda353** [comment]
If you can do another test try to see if its just a visual bug, on my priest i did an issue about debuff that make my buff dissapear. Even if the buff ''dissapear'' the effect is still there when i look at my character panel. (stamina buff)

**Comment by Kabedox** [comment]
It's not a visual bug. I have to cast the Aura again after the buff is gone.

**Comment by Fluglow** [comment]
> If it was just visual the Aura should disappear when clicking it again.

This doesn't disprove the bug being visual only. Client behavior when clicking the spell depends on if the aura is present client-side. You should verify by checking if the aura's effects are still in place (stat sheet for devotion etc.)

**Comment by Kabedox** [comment]
I tested it. 
It is indeed just a visual bug.

![Bug](https://user-images.githubusercontent.com/96084593/184387999-05e77f05-4795-41bc-b7d7-29cf3464eecb.PNG)

**Comment by GrenderG** [comment]
@Kabedox can you try if you are still able to reproduce this?

**Comment by Kabedox** [comment]
I tried to replicate it on multiple occasions and it seems fixed. 👍
