### ISSUE TITLE
Pickpocket

### ISSUE THREAD

**Issue by Dusthoof-Qiraji** [The-Alpha-Project/alpha-core#468]
You can perform "Pickpocket" spell on the same NPC many times.

1. Spell id 5967

You can use "Pickpocket" on the same NPC multiple times. No stealth on you, no stand bihind, no chance of failing?, in a fight with cast into the face.

**Comment by devw4r** [comment]
You are supposed to be using Spell 921, 5967 is just a testing spell not teached by trainers.

**Comment by GrenderG** [comment]
As @devw4r said, if you use the correct spell (921) everything works fine except two things:
1. You can endlessly pickpocket the same mob (it's currently marked as a TODO in the core).
2. You always have 100% chance.
