### ISSUE TITLE
Mobs seem to cause players to crash due to some sort of delayed swing hitting players after they're dead

### ISSUE THREAD

**Issue by Farador1** [The-Alpha-Project/alpha-core#469]
**Describe the bug**
I'm not entirely sure mobs hitting the player after he dies is what causes the crash, but it does seem that way. Earlier in Deadmines someone in our group had a bunch of mobs attacking him and just as he got killed by the mobs, the other four people in the party had a crash. I've experienced the same thing myself while levelling, having been killed by a group of mobs and subsequently crashing.

**Steps to reproduce**
1. Gather up a bunch of mobs.
2. Let them kill you. 
3. ...

**Expected behavior**
You shouldn't crash when you die.

**Screenshots**
If needed, add screenshots to help explain your problem.

**Sources**
If needed, provide valid sources (original screenshots or videos, archived allakhazam...) that show what's the expected behavior or state.

**Comment by X-Genesis-Qhulut** [comment]
Could you post the message the client displays please? It could be related to: https://github.com/The-Alpha-Project/alpha-core/issues/462

**Comment by Farador1** [comment]
I'll try and replicate it again in a little while when I get back on!

**Comment by Farador1** [comment]
Hey, I think I managed to replicate the same crash now and this is what I got:

Exe:      C:\WoW 0.5.3\WoWClient.exe
Time:     Aug 13, 2022 12:50:25.502 AM
User:     user
Computer:  DESKTOP
------------------------------------------------------------------------------

This application has encountered a critical error:

ERROR #0 (0x85100000)
Program:	C:\WoW 0.5.3\WoWClient.exe
File:	D:\build\buildWoW\WoW\Source\Object\ObjectClient\Unit_C.cpp
Line:	2826
Expr:	(GetCurrentBaseAnimState() != ANIM_STATE_DEAD) || (GetCurrentTorsoAnimState() != ANIM_STATE_WOUND)


WoWBuild: 3368
Local Zone: The Yorgen Farmstead, Duskwood
Local Player: Farador, 0000000000000259, (-11113.9,-527.638,32.7303)
Last Enemy Target: Defias Enchanter, F13000000000130A, (-11111.4,-527.568,32.5847)

**Comment by X-Genesis-Qhulut** [comment]
Yep, it's the same bug. Same line in the source and everything.
