### ISSUE TITLE
[Item] Elixir of Minor Defense and Elixir of Defense adds too much armor.

### ISSUE THREAD

**Issue by Farador1** [The-Alpha-Project/alpha-core#474]
**Describe the bug**
When you use Elixir of Minor Defense, it adds 16 armor instead of the 9 it says on the tooltip. When you use Elixir of Defense it adds 29 armor instead of the 25 on the tooltip

**Steps to reproduce**
1. Use an Elixir of Minor Defense.
2. Use an Elixir of Defense.
3. ...

**Expected behavior**
Elixir of Minor Defense should add 9 armor. 
Elixir of Defense should add 25 armor.

**Screenshots**
If needed, add screenshots to help explain your problem.

**Sources**
If needed, provide valid sources (original screenshots or videos, archived allakhazam...) that show what's the expected behavior or state.

**Comment by Fluglow** [comment]
Caused by the client not showing scaling by (effective) level in tooltips. The actual armor buff is correct.
Elixir of Defense grants 25 + 0.6 armor/level; Elixir of Minor Defense grants 9 + 0.9 armor/level.
