### ISSUE TITLE
TODO: Change Commander Felstrom display_id (duskwood)

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#483]
**Describe what needs to be implemented or enhanced**
771 Commander Felstrom doesnt have display_id (Ravenhill Duskwood)
Since He is a named, he should use unused 518 display_id
![image](https://user-images.githubusercontent.com/72315006/184557647-452ee21b-d140-4e19-b018-4e86d24029fa.png)

**Expected end result**
771 Commander Felstrom should use 518 display_id

**Comment by GrenderG** [comment]
Fixed in https://github.com/The-Alpha-Project/alpha-core/pull/485 but probably his position isn't correct in 0.5.3.
