### ISSUE TITLE
Stromgarde Cavalryman/Valorcall are mounted when they shouldn't be

### ISSUE THREAD

**Issue by Yushe** [The-Alpha-Project/alpha-core#495]
I noticed this bug with these NPCs a couple of days back when I was livestreaming.
Daribon posting an old screenshot which reminded me of this issue.

![58969072566](https://user-images.githubusercontent.com/10089856/185029512-d2a225b4-b0b5-44eb-bb06-21cdaf4f56bc.jpg)

![horse ridin](https://user-images.githubusercontent.com/10089856/185029526-af987183-a3f5-47be-855b-b27593ea8d40.png)

**The Issue**
Well you can clearly see what the issue is within the screenshot I took, although there is another issue. 
If you compare screenshots you may notice that the NPCs don't have there weapons drawn in the older screenshot.

**Affected NPC Entries**
2612 & 2738.

**Comment by GrenderG** [comment]
I wonder if these NPCs are actually 
![image](https://user-images.githubusercontent.com/8654362/185751912-f844d3bc-cddd-4d1d-b165-9eb2e9d794b4.png)
instead.
