### ISSUE TITLE
[Dungeon] There's no way to get the first door in Shadowfang Keep to open.

### ISSUE THREAD

**Issue by Farador1** [The-Alpha-Project/alpha-core#500]
**Describe the bug**
There is no way to open the first door in Shadowfang Keep after the first boss. After the boss is dead, the levers to the cells don't work and even if you do get inside there you can't interact with the npc. It also seems that there is no way to get the rest of the doors in the dungeon to open either.

**Steps to reproduce**
1. Go to Shadowfang Keep.
2. Use the lever to the cell with the npc that's supposed to open the door for you.
3. ...

**Expected behavior**
The npc in the cell is supposed to open the door for you after you've defeated the first boss.

**Screenshots**
If needed, add screenshots to help explain your problem.

**Sources**
If needed, provide valid sources (original screenshots or videos, archived allakhazam...) that show what's the expected behavior or state.

**Comment by GrenderG** [comment]
Missing scripting system.

**Comment by GrenderG** [comment]
Fixed on https://github.com/The-Alpha-Project/alpha-core/commit/c142564710410dd576ec27de487ed2da154bc447
