### ISSUE TITLE
[Quest] Winterhoof Cleansing, Thunderhorn Cleansing and Wildmane Cleansing auto complete

### ISSUE THREAD

**Issue by Farador1** [The-Alpha-Project/alpha-core#502]
**Describe the bug**
When you pick up these quests (all in the same quest chain), they all auto complete and can be turned in as soon as you pick up the quests.

**Steps to reproduce**
1. Pick up the quests.
2. ...
3. ...

**Expected behavior**
You are supposed to use the totems that are provided to cleanse the wells.

**Screenshots**
If needed, add screenshots to help explain your problem.

**Sources**
If needed, provide valid sources (original screenshots or videos, archived allakhazam...) that show what's the expected behavior or state.

**Comment by devw4r** [comment]
Requires scripting.
