### ISSUE TITLE
[Spell] Divine Shield/Divine Favor makes you immune to friendly spells.

### ISSUE THREAD

**Issue by Farador1** [The-Alpha-Project/alpha-core#510]
**Describe the bug**
While Divine Shield and Divine Favor are active, you become immune to your own spells as well as other friendly spells. This means attempting to heal yourself or buff yourself while these abilities are active does nothing.

**Steps to reproduce**
1. Get low health.
2. Use Divine Shield or Divine Favor and attempt to heal/buff yourself.
3. ...

**Expected behavior**
These abilities should only make you immune to harmful attacks and spells, not your own spells.

**Screenshots**
If needed, add screenshots to help explain your problem.

**Sources**
If needed, provide valid sources (original screenshots or videos, archived allakhazam...) that show what's the expected behavior or state.

**Comment by ratkosrb** [comment]
Auras that provide immunity should not prevent positive effects, unless the aura that grants the immunity has this attribute:
```
SPELL_ATTR_EX_IMMUNITY_TO_HOSTILE_AND_FRIENDLY_EFFECTS = 0x00010000
```
