### ISSUE TITLE
Tracking Talent Spells are unlisted in the abilities/spell book

### ISSUE THREAD

**Issue by Yushe** [The-Alpha-Project/alpha-core#512]
**Describe the bug**
The spells given to you when learning talents related to tracking specific NPC types appear to be unlisted.

**Steps to reproduce**
Either learn one of the talents or give yourself them through commands
This command will give you undead tracking:
.lspell 5120

**Comment by mindphluxnet** [comment]
I've looked at this and while the spell is learned and saved to the character database, the spell book entry is never created. Should be an easy fix for someone who knows what they're doing.

**Comment by devw4r** [comment]
Those spells have the 'Do not display' attribute, so the client automatically hides them, they were probably not available in 0.5.3.
