### ISSUE TITLE
TODO: Change Jorb display_id

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#524]
**Describe what needs to be implemented or enhanced**
3659 Jorb miss display_id, here's screenshot of him
![446](https://user-images.githubusercontent.com/72315006/185637071-742ed5a0-02db-4af1-a822-0528fe46b20b.jpg)

Find a ogre display_id with a scale that fit screenshot and apply it.

**Expected end result**
Jorb should use ogre display_id

**Comment by Daribon** [comment]
![explorer_VdMGvNlvI8](https://user-images.githubusercontent.com/6137576/185703962-33b2df87-2316-4adc-af92-37a9734e2886.png)
