### ISSUE TITLE
Night Elf characters are not given there racial abilities upon being created

### ISSUE THREAD

**Issue by Yushe** [The-Alpha-Project/alpha-core#531]

**Comment by GrenderG** [comment]
Do we have any source confirming that they should have Shadowmeld in 0.5.3?

**Comment by Farador1** [comment]
> Do we have any source confirming that they should have Shadowmeld in 0.5.3?

According to the character creation screen, they are supposed to have Shadowmeld.

![image](https://user-images.githubusercontent.com/110574922/185768717-a160fc2a-cc4b-4655-afa2-241d7479c30e.png)

**Comment by Daribon** [comment]
From in game at 0.5.3:
![janvier2004-10](https://user-images.githubusercontent.com/6137576/185768868-d2fa56da-6cbd-4c9f-a1f1-00a47737047b.jpg)

**Comment by GrenderG** [comment]
Thanks! :+1:

**Comment by GrenderG** [comment]
I see the issue, in Vanilla Shadowmeld uses the one with ID 20580 but 0.5.3 only has the one with ID 743.
