### ISSUE TITLE
TODO: Missing Tauren racial spell

### ISSUE THREAD

**Issue by GrenderG** [The-Alpha-Project/alpha-core#537]
**Describe what needs to be implemented or enhanced**
According to the 0.5.3 creation screen Taurens should have "Plains running", but the actual spell named "Plainsrunning" (4082) is too op, it's permanent and increases running speed by 100%. Because of this, they were most likely using "Bull Rush" (4083) that only lasts for 30 seconds and has a 5 minutes cooldown.
![image](https://user-images.githubusercontent.com/8654362/185771145-00c5276a-dab5-4b03-9282-995c37acb558.png)
We can see they had it in the action bar, so most likely the spell needs to appear there on character creation too.

**Expected end result**
All Tauren classes should start with "Bull Rush (4083)" and be placed in their action bar.

**Guidance**
Spell needs to be added to `playercreateinfo_spell` and `playercreateinfo_action`.

**Comment by X-Genesis-Qhulut** [comment]
The text and objectives in the screenshot there are substantially different to what is on the database:

https://wow-refugee.com/alpha/index.php?action=show_quest&id=771

**Comment by diff3** [comment]
Added Bull rush to all Tauren classen, and the spell is also visible on action bar
