### ISSUE TITLE
TODO: Investigate missing racial spells for Humans and Dwarfs.

### ISSUE THREAD

**Issue by GrenderG** [The-Alpha-Project/alpha-core#538]
**Describe what needs to be implemented or enhanced**
According to their character creation screen, Humans should have "Bonus skill points" and Dwarfs are "Natural Miners". Investigation is needed to determine if any spell exists matching these descriptions.

**Expected end result**
If appropriate, these spells should be added to `playercreateinfo_spell`.

**Comment by X-Genesis-Qhulut** [comment]
See: https://www.deviantart.com/daxx-lorenzo/journal/The-Lannsirad-Project-MMORPG-Planning-803855756

> The Alpha character creation screen lists the following racials for the dwarf:
>
>    Treasure finding
>   Natural miners
>   Resistant to cold magic
>
> While treasure finding and bonus frost resistance made it into the final game, being a natural miner (most likely meaning a plus to the Mining profession) **was never given to the dwarves**. Treasure finding was later axed in Cataclysm, but dwarves still have a Frost Resistance racial. 

(My emphasis).

---

> The Alpha character creation screen lists the following racial for the human:
> 
>     Bonus skill points
> 
> **This racial trait never made it into the final game**, and it's unknown whether it means talent points, or skill points for a profession. 

(My emphasis).

**Comment by GrenderG** [comment]
Really good find, this can be closed now! I archived that page https://web.archive.org/web/20220823110857/https://www.deviantart.com/daxx-lorenzo/journal/The-Lannsirad-Project-MMORPG-Planning-803855756 just in case.

**Comment by Daribon** [comment]
That website link looks like it was straight up copied from the following url:
https://tcrf.net/Proto:World_of_Warcraft/0.5.3.3368_Friends_%26_Family_Alpha
