### ISSUE TITLE
Casting blink does not move the caster

### ISSUE THREAD

**Issue by X-Genesis-Qhulut** [The-Alpha-Project/alpha-core#540]
**Describe the bug**
If a mage casts Blink you see the animation, mana is consumed, the cooldown is started, however the caster does not move to the targeted location.

**Steps to reproduce**
1. As a mage, cast Blink
2. You remain where you are.

**Expected behavior**
You move to the target location.

**Comment by GrenderG** [comment]
Fixed in https://github.com/The-Alpha-Project/alpha-core/commit/fc77432caf660a667c52c1fea67b211bcb305491
