### ISSUE TITLE
[Mechanic] Ranged attacks should be dodgeable and blockable.

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#544]
**Describe the bug**
According to their tooltips, dodge and block give a chance for avoiding both melee and ranged attacks.

**Steps to reproduce**
1. Shoot at another character with high dodge and block percentage.

**Expected behavior**
A ranged attack should be able to be dodged or blocked a target.

**Sources**
Dodge and Block ingame tooltips.

**Comment by Fluglow** [comment]
Related to #238 (all ranged attacks are spells). Good to note when implementing.
