### ISSUE TITLE
TODO: Change Grimnal Display_id

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#550]
**Describe what needs to be implemented or enhanced**
![Capture-d-cran-2022-08-22-025713](https://user-images.githubusercontent.com/72315006/185830162-c508b550-ded0-4f51-ba23-00d57d9b9aa9.png)

**Expected end result**
980 Grimnal should use placeholder 1139 display_id as other orcs here.

**Comment by diff3** [comment]
UPDATE `creature_template` SET `display_id1`='1139' WHERE `entry`='980';
