### ISSUE TITLE
[Quest] Arugal's folly quest objective quantity.

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#551]
**Describe the bug**
The Arugal's Folly quest (ID 99) asks for 6 Pyrewood Shackles (ID 3218), when in reality it should ask for 12. It has been reduced in a later patch (0.5.4)

**Expected behavior**
The quest should require 12 pyrewood shackles to finish the quest.

**Sources**
Official Blizzard patch-notes for patch 0.5.4

**Comment by GrenderG** [comment]
> H [15] [Arugal's Folly](https://wowpedia.fandom.com/wiki/Arugal%27s_Folly_(4)): Reduced the number of [Pyrewood Shackles](https://wowpedia.fandom.com/wiki/Pyrewood_Shackle) required from 12 to 6.
