### ISSUE TITLE
[Item/Quest] Incorrect item name and quest objective.

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#552]
**Describe the bug**
The quest A Recipe for Death (ID 447) asks, among other things, for 6 stacks of Skittering Blood (ID 3254). The name of the item is incorrect, since in 0.5.3 it was called Spider Marrow. The change to Skittering blood was done in the next patch, 0.5.4.
Spider Marrow doesn't exist in the database, so most likely its ID was used for the Skittering blood later on.

**Expected behavior**
Both the quest and the item should display the correct item name of Spider Marrow

**Source**
Official Blizzard Patch-Notes from patch 0.5.4
The exact amount of how many hearts and marrows are needed is still investigated, since the current quantity of 6 is obviously wrong but solid proof is needed to change it.
![AF and RfD](https://user-images.githubusercontent.com/111394734/185914997-2e94dbcc-f190-4164-b2d8-98ba2e745430.png)

**Comment by user112233456** [comment]
maybe change the item name and and quest objective maybe something worng with sql or stuff
