### ISSUE TITLE
[Item] Incorrect item icon

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#566]
**Describe the bug**
Spiked Star (ID 925) has inv_mace_01 icon (ID 133476), when it should have inv_mace_15 icon (ID 133490) according to the screenshot made 4 days after 0.5.3 launch.

**Sources**
![2003-12-16-11-42-05](https://user-images.githubusercontent.com/111394734/186474342-e1ecc4c8-67b5-4a91-9def-d85b1166e50b.jpg)

**Comment by GrenderG** [comment]
We'd need to find the correct `display_id` for this item, would need to search between entries using that icon.

**Comment by Daribon** [comment]
Some WDB sql update must have changed this.
It used to have correct displayid in alpha-core.
![WoWClient_uE3kv2WzBL](https://user-images.githubusercontent.com/6137576/187050045-5b9b9fce-f4f8-497d-8223-00312bdbeed8.png)
I deleted WDB and now it has incorrect displayid.

**Comment by GrenderG** [comment]
Indeed, got updated here: https://github.com/The-Alpha-Project/alpha-core/commit/be3781531ffd12caf6beaae3646e83b0b2122b3d#diff-6d4a0bcd2fdfd3d6dae2809f13ba37fa44cf609a20dee73ad13cc77dce2d4365R5351-R5353

**Comment by GrenderG** [comment]
Seems like the issue is that our new wdb parser ignored items where the old display id was higher than the new one. Investigating.
