### ISSUE TITLE
TODO: Change Ruppo Zipcoil display_id

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#572]
**Describe what needs to be implemented or enhanced**
![AwesomePlaceholder](https://user-images.githubusercontent.com/72315006/186516753-9eee947e-ed2a-4b63-ac10-2b85d4337d7b.jpg)

**Expected end result**
2688 Ruppo Zipcoil should use 352 display_id, you need to change name/subname accordingly

**Comment by Daribon** [comment]
0.5.3 image so very valid source.

**Comment by diff3** [comment]
Is his name [PH] Rup...? or just Rup...

**Comment by geo-tp** [comment]
[PH] Ruppo Zipcoil
