### ISSUE TITLE
[Object/Item] Stranglekelp should be removed

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#575]
**Describe the bug**
Stranglekelp was introduced in patch 0.7, therefore Stranglekelp objects scattered throughout the world (with the entry 2045) and their loot (ID 3820)  should be removed.

**Sources**
(Pulled from 0.7 patch notes)
![Stranglekelp](https://user-images.githubusercontent.com/111394734/186530472-4b505a07-6d1e-48a5-be3f-798c04668ce2.png)

**Comment by GrenderG** [comment]
I wonder if it had a different name before that since it has a low entry.

**Comment by Daribon** [comment]
Stranglekelp has a model with the exact name Stranglekelp in 0.5.3.

![wow-mdx-viewer_ZsClDQvxt2](https://user-images.githubusercontent.com/6137576/186539656-2300a27e-ce64-4db1-a633-666f8656586d.png)

**Comment by GrenderG** [comment]
So maybe everything was present but just not spawned. 🤔

**Comment by GizzleBizzle** [comment]
I've checked all recipes from 1.12.1 requiring it, Out of seven of them only one uses stranglekelp as a reagent in Alpha, the Nature Protection Potion (Spell ID 7050). Seems fishy. I'll see if any are needed in Enchanting or maybe I can find some screenshots of it in the catalogue.

I suggest adding a "Needs investigating" tag for the time being.

**Comment by GrenderG** [comment]
Stranglekelp can still be obtained through fishing even if we remove the gameobjects. It might be possible that the only way to obtain it was through fishing in 0.5.3, considering that the item existed due to its low entry.

**Comment by GizzleBizzle** [comment]
Seems reasonable. I've dug through the whole Barrens and Wetlands catalogues and there's not a single proof of Stranglekelp or its object.
