### ISSUE TITLE
[icon] Grayson's Torch's missing icon.

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#577]
**Describe the bug**
Grayson's torch (ID 1172) should have the inv-spear-03 (ID 135126) icon. If anyone has doubts about torches having spear icons (like I did), both the Dim Torch (ID 6182) and Monster - Torch, Offhand (ID 2081) have the exact icon in game, so it seems that it was a common thing back then.

**Sources**
![NoBans](https://user-images.githubusercontent.com/111394734/186684672-add035c2-6a39-4438-a5d5-d66aafa64de6.jpg)

**Comment by C-Gulls** [comment]
![image](https://user-images.githubusercontent.com/112269703/187039776-0e6fda14-f777-4595-8eb5-ebe3715cf957.png)

Display IDs 6520 and 6537 both use the handheld torch model with the desired icon. Either one should work, they appear to be exactly the same.
