### ISSUE TITLE
TODO: NPCs Grisha and Lanie Reed might need to be relocated (maybe the had a different name/subname/purpose).

### ISSUE THREAD

**Issue by X-Genesis-Qhulut** [The-Alpha-Project/alpha-core#579]
**Describe the bug**
The NPCs Grisha and Lanie Reed are spawned in the Searing Gorge, however they were not added into the game until patch 1.13.2.30406.

There are no other NPCs within 650 yards, and no infrastructure near them. They are in the general location of Thorium Point, which has not been added yet.

**Steps to reproduce**
1. Visit the Searing Gorge and observe them
2. Lanie Reed at:  -6559.06 -1169.38 309.861 0
3. Grisha at: -6559.31 -1100.25 310.372 0

**Expected behavior**
They should not be spawned.

**Sources**
* Grisha: https://wow-refugee.com/alpha/index.php?action=show_creature&id=3305
* Lanie Reed: https://wow-refugee.com/alpha/index.php?action=show_creature&id=2941

If needed, provide valid sources (original screenshots or videos, archived allakhazam...) that show what's the expected behavior or state.

* https://classic.wowhead.com/npc=3305/grisha - "Added in patch 1.13.2.30406"
* https://classic.wowhead.com/npc=2941/lanie-reed - "Added in patch 1.13.2.30406"

**Comment by GrenderG** [comment]
Don't believe the "Added in patch" information from Wowhead, it's not correct. These NPCs existed in 0.5.3 due to their low entry. Maybe they were spawned somewhere else but that's it.

**Comment by Daribon** [comment]
However the flight master Lanie Reed wasn't spawned until 1.5.0.
It is possible she had another purpose prior to release.

**Comment by devw4r** [comment]
0.5.5

Entry: 2941
Name: Lanie Reed
Title: Spider Trainer
StaticFlags: 102
CreatureType: 7
CreatureFamily: 0

**Comment by geo-tp** [comment]
Lanie Reed is probably located in Elwyn forest Logging camp as this point

```
Entry: 1103 => Logging Camp
Name: Eldrin
Title: Tailor
StaticFlags: 102
CreatureType: 7
CreatureFamily: 0


Entry: 1975 => Logging Camp
Name: Eastvale Lumberjack
StaticFlags: 0
CreatureType: 7
CreatureFamily: 0


Entry: 2941 => ?
Name: Lanie Reed
Title: Spider Trainer
StaticFlags: 102
CreatureType: 7
CreatureFamily: 0


Entry: 5446 
Name: Tamed Spider
StaticFlags: 102
CreatureType: 1
CreatureFamily: 3


Entry: 1250 => Logging camp
Name: Drake Lindgren
Title: General & Trade Supplies
StaticFlags: 102
CreatureType: 7
CreatureFamily: 0

```

**Comment by Daribon** [comment]
Yes Lanie Reed should most likely be in Eastvale Logging Camp.
Both Wowpython and wowemu has her spawned in Eastvale Logging Camp.

Wowpython: worldport 0 -9456.99 -1309.43 45.0453 0.959931
Dated 2004-09-14

Wowemu Legion (ThePeoplesPatchNoCallback) : worldport 0 -9411.930664 -1321.798340 49.985474 6.015296
wowemu [WAD_0.4115.5(1.1.x): worldport 0 -9457.027344 -1309.580688 44.986961 1.162875
Both dated from January 2005.

Due to the nature of the database, I wouldn't trust their positioning one bit.
But it can give some hints on where the spawns possibly should be.

I've looked into the screenshots we have for Elwynn and we are lacking images when it comes to Eastvale Logging Camp so can't confirm anything.

As for Grisha I can't find anything from her from any old database.

**Comment by Daribon** [comment]
Some update regarding Grisha.

I realized by looking at entries in Sen'jin Village that an NPC Master Vornal has entry 3304 standing almost right next to the cat trainer in Senjin'Village.
Grisha has entry 3305. The very next entry 3306 is a pet trainer as well.

Considering that Lanie Reed used to be a pet trainer. It is very likely that Grisha used to be a pet trainer as well.
![pet](https://media.discordapp.net/attachments/700043968892764300/1013614260770848768/unknown.png)
![560310-534914_20040415_060](https://user-images.githubusercontent.com/6137576/187111029-f7a11e0c-be80-4a06-a372-b1099354434f.jpg)
![561792-534914_20040426_006](https://user-images.githubusercontent.com/6137576/187111050-caa3430a-9957-45a0-9a7f-18fddcb8efc0.jpg)
![WoWScrnShot_041504_222513](https://user-images.githubusercontent.com/6137576/187111151-c1ad49cb-319b-4fae-a6db-84cfb3438dd2.jpg)

**Comment by geo-tp** [comment]
Grisha is now binder of Valley of Trials.
Lanie Reed is now Spider trainer of Eastvale camp.

This issue can be closed
