### ISSUE TITLE
TODO: Change Thule Ravenclaw display_id

### ISSUE THREAD

**Issue by Ghaster** [The-Alpha-Project/alpha-core#580]
**Describe what needs to be implemented or enhanced**
Proof found in the diary:
![ravenclaw_proof](https://user-images.githubusercontent.com/11392454/186881289-d0677620-c3fb-4280-a628-750308137b48.jpg)

Only display ids with that skin are 263 and 795.

**Expected end result**
1947 Thule Ravenclaw should use either display id 263 (with 1.1 scale) or display id 795 (with 1.0 scale but fits range).

**Comment by geo-tp** [comment]
Nice find

**Comment by geo-tp** [comment]
![Capture d’écran_2022-08-26_21-12-34](https://user-images.githubusercontent.com/72315006/186975603-fb1dd23f-cebe-4be7-a724-7b9cd6fc9e92.png)

263 seems more appropriate here, it's used for a lot of placeholder.
795 is only used for Stranglethorn pirate (modified by me, it was unused before that)

All linked models used for STV pirates
![Capture d’écran_2022-08-13_02-28-24](https://user-images.githubusercontent.com/72315006/186975957-4eca2848-0878-498f-8d8a-a7f15fc54e0d.png)
