### ISSUE TITLE
TODO: Spawn pets

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#582]
**Describe what needs to be implemented or enhanced**

![Capture d’écran_2022-08-26_20-35-43](https://user-images.githubusercontent.com/72315006/186970002-b848a878-7f23-4881-917c-d304b7db2e16.png)

Shadow is already spawned, check others
Strumner and Celmoridan's pets are not spawned (SW)

**Expected end result**
All pets with a subname should be normally spawn and not summoned.

**Comment by GrenderG** [comment]
Strumber and Celmoridan pets have been spawned in https://github.com/The-Alpha-Project/alpha-core/pull/676
