### ISSUE TITLE
TODO: Change Subnames

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#583]
**Describe what needs to be implemented or enhanced**

Subnames of some NPC are not correct for 0.5.3

0.5.3 WDB
```
Entry: 5749
Name: Kayla Smithe
Title: Demon Pet Trainer
StaticFlags: 102
CreatureType: 7
CreatureFamily: 0

Entry: 4731
Name: Zachariah Post
Title: Animal Handler
StaticFlags: 102
CreatureType: 6
CreatureFamily: 0

Entry: 4773
Name: Velma Warnam
Title: Horse Riding Instructor
StaticFlags: 102
CreatureType: 6
CreatureFamily: 0

Entry: 2114
Name: Faruza
Title: Apprentice Herbalist
StaticFlags: 102
CreatureType: 6
CreatureFamily: 0

Entry: 2137
Name: Eliza Callen
Title: Apprentice Leathercrafter
StaticFlags: 102
CreatureType: 6
CreatureFamily: 0

Entry: 5750
Name: Gina Lang
Title: Demon Pet Trainer
StaticFlags: 102
CreatureType: 7
CreatureFamily: 0

Entry: 5695
Name: Vance Undergloom
Title: Enchanter
StaticFlags: 102
CreatureType: 6
CreatureFamily: 0
```

0.5.5 WDB
```
Entry: 836
Name: Durnan Furcutter
Title: Cloth & Leather
StaticFlags: 102
CreatureType: 7
CreatureFamily: 0

```

**Expected end result**
All thse mobs should use correct subname as WDB files show

**Comment by GrenderG** [comment]
Didn't we parse the 0.5.3 WDB for mobs already @devw4r? Maybe we didn't. :thinking:

**Comment by devw4r** [comment]
We did not change Titles.

**Comment by geo-tp** [comment]
![Capture d’écran_2022-08-25_03-11-37](https://user-images.githubusercontent.com/72315006/186967437-c860a5fd-238f-4a5e-963b-67e686f5e1e0.png)
![Capture d’écran_2022-08-25_03-11-55](https://user-images.githubusercontent.com/72315006/186967443-6048e4e1-c9bb-484d-91f0-de151baac002.png)

Example here
