### ISSUE TITLE
[Mob] Sen'Jin Watcher's incorrect reaction/sound

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#586]
**Describe the bug**
[Sen'Jin Watchers](https://classic.wowhead.com/npc=3297/senjin-watcher) (Entry ID 3297) are neutral to both Horde and Alliance, can be attacked by both factions and make human sounds instead of troll ones.

**Comment by GizzleBizzle** [comment]
Correction, ALL trolls in Sen'Jin Village use human sounds instead of their troll counterparts.

**Comment by GrenderG** [comment]
Faction might be incorrect, but sounds are defined client side.

**Comment by GizzleBizzle** [comment]
Thanks for the quick heads-up. I was about to write down all troll NPC entries in the village.

**Comment by GrenderG** [comment]
I checked and faction template 877 doesn't exist in 0.5.3, all mobs using 877 should probably be using `76` which is `Orc, Orgrimmar` like other troll NPCs are using.

**Comment by X-Genesis-Qhulut** [comment]
I've added a test for creatures with non-existent factions:

https://wow-refugee.com/alpha/index.php?action=unknown_faction
