### ISSUE TITLE
TODO: Change Subnames

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#589]
Following subnames have been updated already, see https://github.com/The-Alpha-Project/alpha-core/issues/589#issuecomment-1233063596

**Describe what needs to be implemented or enhanced**
![wow_oldmedia_screenshots_beta_week4_417_17s](https://user-images.githubusercontent.com/72315006/187037174-8bb0fea2-fc95-4a44-b356-31003a6e43fc.jpg)
![wow_oldmedia_screenshots_beta_week4_417_20s](https://user-images.githubusercontent.com/72315006/187037176-f97e5feb-8fc4-4782-bf39-faa79db8d81c.jpg)
![wowapc215](https://user-images.githubusercontent.com/72315006/187037184-0b48ebd4-5e87-41e9-8ae6-046e9c8d9093.jpg)
![wow2p9](https://user-images.githubusercontent.com/72315006/187037294-7395b3f4-f28a-40e4-bdce-29db6ee64b88.png)

**Expected end result**
These mobs should use correct subnames

**Comment by devw4r** [comment]
Entry: 3967
Our subname:
Leatherworking Trainer
Aug 2004 subname:
Leatherworker


Entry: 5386
Our name:
[PH] Acolyte Dellis
Aug 2004 name:
Acolyte Dellis


Entry: 3606
Our subname:
Enchanting Trainer
Aug 2004 subname:
Enchantress


Entry: 3702
Our subname:
None
Aug 2004 subname:
Tallstrider Trainer


Entry: 4900
Our subname:
Alchemy Trainer
Aug 2004 subname:
Alchemist


Entry: 5594
Our subname:
Alchemy Supplies
Aug 2004 subname:
Superior Alchemist


Entry: 3552
Our subname:
Leather Armor Merchant
Aug 2004 subname:
Leatherworker


Entry: 2816
Our subname:
Leatherworking Supplies
Aug 2004 subname:
Superior Leatherworker


Entry: 2856
Our subname:
Herbalism Trainer
Aug 2004 subname:
Superior Herbalist


Entry: 1141
Our name:
[PH] Angus Stern
Aug 2004 name:
Angus Stern


Entry: 1284
Our name:
[PH] Archbishop Benedictus
Aug 2004 name:
Archbishop Benedictus


Entry: 931
Our name:
Ariena Bloodfeather
Aug 2004 name:
Ariena Stormfeather


Entry: 246
Our name:
"Auntie" Bernice Stonefield
Aug 2004 name:
Auntie Bernice Stonefield


Entry: 2806
Our subname:
General Goods
Aug 2004 subname:
Survival Trainer


Entry: 989
Our subname:
Trade Goods
Aug 2004 subname:
Rogue Trainer


Entry: 3546
Our subname:
Food & Drink
Aug 2004 subname:
Spider Trainer


Entry: 1880
Our subname:
None
Aug 2004 subname:
Needs Model


Entry: 2481
Our subname:
Alchemy Supplies
Aug 2004 subname:
Superior Alchemist


Entry: 3364
Our subname:
Tailoring Supplies
Aug 2004 subname:
Tailoring Vendor


Entry: 1441
Our subname:
Specialty Weaponsmith
Aug 2004 subname:
Weaponsmith


Entry: 4898
Our subname:
Herbalism Trainer
Aug 2004 subname:
Herbalist


Entry: 1385
Our subname:
Leatherworking Trainer
Aug 2004 subname:
Superior Leatherworker


Entry: 2836
Our subname:
Blacksmithing Trainer
Aug 2004 subname:
Superior Blacksmith


Entry: 5384
Our name:
[PH] Brohann Caskbelly
Aug 2004 name:
Brohann Caskbelly


Entry: 1752
Our name:
[PH] Caledra Dawnbreeze
Aug 2004 name:
Caledra Dawnbreeze


Entry: 3152
Our name:
Cap'n Crunch
Aug 2004 name:
Cap'n Copyright


Entry: 3895
Our name:
Captain Eo
Aug 2004 name:
Captain Noteo


Entry: 3151
Our name:
Captain Morgan
Aug 2004 name:
Captain Obvious


Entry: 3096
Our subname:
Specialist Tailoring Supplies
Aug 2004 subname:
Specialist Tailor


Entry: 4896
Our name:
Charity Mipsy
Aug 2004 name:
Charity Mippsy


Entry: 3069
Our subname:
Leatherworking Trainer
Aug 2004 subname:
Leatherworker


Entry: 3545
Our subname:
Pet Trainer
Aug 2004 subname:
Bear Trainer


Entry: 1355
Our subname:

Aug 2004 subname:
Cooking Trainer


Entry: 2285
Our name:
[PH] Count Remington Ridgewell
Aug 2004 name:
Count Remington Ridgewell


Entry: 2672
Our subname:
Tailoring Supplies
Aug 2004 subname:
Superior Tailor


Entry: 3166
Our subname:
Cloth & Leather Armor Merchant
Aug 2004 subname:
Clothier & Leathercrafter


Entry: 3965
Our subname:
Herbalism Trainer
Aug 2004 subname:
Herbalist


Entry: 2668
Our subname:
Tailoring Supplies
Aug 2004 subname:
Tailor


Entry: 3290
Our subname:
Engineering Trainer
Aug 2004 subname:
Engineer


Entry: 3411
Our subname:
Butcher
Aug 2004 subname:
Survival Trainer


Entry: 2532
Our name:
Stormwind Girl
Aug 2004 name:
Donna


Entry: 2812
Our subname:
Alchemy Supplies
Aug 2004 subname:
Superior Alchemist


Entry: 3174
Our subname:
Blacksmithing Trainer
Aug 2004 subname:
Blacksmith


Entry: 4165
Our name:
Elyissa
Aug 2004 name:
Elissa Dumas


Entry: 1881
Our subname:
None
Aug 2004 subname:
Needs Model


Entry: 1676
Our subname:
Engineering Trainer
Aug 2004 subname:
Engineer


Entry: 908
Our subname:
Herbalism Trainer
Aug 2004 subname:
Superior Herbalist


Entry: 2682
Our subname:
Engineering Supplies
Aug 2004 subname:
Engineer


Entry: 4902
Our name:
Mikal Pierce
Aug 2004 name:
Frank Lasson
Our subname:

Aug 2004 subname:
Spider Trainer


Entry: 3091
Our subname:
Clothier
Aug 2004 subname:
Tailoring Supplier


Entry: 5051
Our name:
[UNUSED] Frewa
Aug 2004 name:
Frewa


Entry: 4043
Our subname:
Two-Handed Weapons Merchant
Aug 2004 subname:
Two Handed Weapons Merchant


Entry: 1470
Our subname:
Alchemy Trainer
Aug 2004 subname:
Alchemist


Entry: 2687
Our subname:
Engineering Supplies
Aug 2004 subname:
Superior Engineer


Entry: 1213
Our subname:
Armorer
Aug 2004 subname:
Armorer & Shieldcrafter


Entry: 2627
Our subname:
Tailoring Trainer
Aug 2004 subname:
Tailor


Entry: 3343
Our subname:
Blacksmithing Supplies
Aug 2004 subname:
Shaman Trainer


Entry: 2858
Our subname:
Wind Rider Master
Aug 2004 subname:
Gryphon Master


Entry: 3622
Our subname:
Pet Trainer
Aug 2004 subname:
Boar Trainer


Entry: 1064
Our name:
Grom'gol Grunt
Aug 2004 name:
Grom'gol Guard


Entry: 5164
Our subname:
Blacksmithing Trainer
Aug 2004 subname:
Armor Crafter


Entry: 2876
Our subname:
None
Aug 2004 subname:
Crocilisk Trainer


Entry: 3557
Our subname:
Blacksmithing Trainer
Aug 2004 subname:
Blacksmith


Entry: 3316
Our subname:
Cloth & Leather Armor Merchant
Aug 2004 subname:
Leather Armor Merchant


Entry: 3685
Our subname:
Kodo Mounts
Aug 2004 subname:
Cat Trainer


Entry: 5133
Our subname:
General Goods Vendor
Aug 2004 subname:
Wands Merchant


Entry: 3956
Our subname:
Alchemy Supplies
Aug 2004 subname:
Alchemist


Entry: 3620
Our subname:
Pet Trainer
Aug 2004 subname:
Crocilisk Trainer


Entry: 4832
Our name:
Twilight Lord Kelris
Aug 2004 name:
High Sleepwalker Kelris


Entry: 5694
Our name:
[PH] High Sorcerer Andromath
Aug 2004 name:
High Sorcerer Andromath


Entry: 1147
Our subname:
Cloth & Leather Armor Merchant
Aug 2004 subname:
Superior Clothier and Leathercrafter


Entry: 3160
Our subname:
Cloth & Leather Armor Merchant
Aug 2004 subname:
Clothier & Leathercrafter


Entry: 2844
Our subname:
Blacksmithing Supplies
Aug 2004 subname:
Superior Blacksmith


Entry: 1411
Our subname:
Rogue Trainer
Aug 2004 subname:
Mage Trainer


Entry: 1247
Our name:
Barkeep Belm
Aug 2004 name:
Innkeeper Belm
Our subname:
Burly Bartender
Aug 2004 subname:
Innkeeper


Entry: 295
Our subname:

Aug 2004 subname:
Innkeeper


Entry: 5111
Our name:
Bogrum Firebrew
Aug 2004 name:
Innkeeper Firebrew
Our subname:
Bartender
Aug 2004 subname:
Innkeeper


Entry: 3700
Our subname:
Reagent Vendor
Aug 2004 subname:
Crawler Trainer


Entry: 3483
Our subname:
Leather & Mail Armor Merchant
Aug 2004 subname:
Leatherworker & Armorer


Entry: 1471
Our subname:
Superior Macecrafter
Aug 2004 subname:
Macecrafter


Entry: 2847
Our subname:
Blacksmithing Supplies
Aug 2004 subname:
Superior Blacksmith


Entry: 2837
Our subname:
Alchemy Trainer
Aug 2004 subname:
Superior Alchemist


Entry: 1473
Our subname:
Herbalism Trainer
Aug 2004 subname:
Herbalist


Entry: 3690
Our subname:
Kodo Riding Instructor
Aug 2004 subname:
Bird Trainer


Entry: 2879
Our subname:
Pet Trainer
Aug 2004 subname:
Bird Trainer


Entry: 954
Our subname:
Leather Armor Merchant
Aug 2004 subname:
Leathercrafter


Entry: 5121
Our subname:
Mace Merchant
Aug 2004 subname:
Maces & Staves


Entry: 4901
Our name:
Sara Pierce
Aug 2004 name:
Kenna Larnad
Our subname:

Aug 2004 subname:
Crocilisk Pet Trainer


Entry: 3484
Our subname:
Tailoring Trainer
Aug 2004 subname:
Tailor


Entry: 4752
Our subname:
Wolf Riding Instructor
Aug 2004 subname:
Wolf Rider


Entry: 3346
Our subname:
Enchanting Supplies
Aug 2004 subname:
Enchanting Supplier


Entry: 3348
Our subname:
Alchemy Supplies
Aug 2004 subname:
Alchemy Vendor


Entry: 3360
Our subname:
Mace & Staves Vendor
Aug 2004 subname:
Mace Vendor


Entry: 5411
Our subname:
Blacksmithing Supplies
Aug 2004 subname:
Superior Blacksmith


Entry: 3703
Our subname:
Leatherworking Trainer
Aug 2004 subname:
Leathercrafter


Entry: 3621
Our subname:
Food & Drink
Aug 2004 subname:
Cat Trainer


Entry: 3436
Our name:
Kuz
Aug 2004 name:
Kuz Orcbane


Entry: 3964
Our subname:
Alchemy Trainer
Aug 2004 subname:
Alchemist


Entry: 3689
Our subname:
Food & Drink
Aug 2004 subname:
Wolf Trainer


Entry: 1671
Our subname:
Herbalist
Aug 2004 subname:
Fruit Seller


Entry: 4730
Our subname:
Animal Handler
Aug 2004 subname:
Tiger Handler


Entry: 2795
Our name:
Lenny "Fingers" McCoy
Aug 2004 name:
Lenny Fingers McCoy


Entry: 1672
Our subname:
Tailoring Supplies
Aug 2004 subname:
Tailoring Supplier


Entry: 5049
Our subname:
Guild Tabard Designer
Aug 2004 subname:
Guild Tabard Vendor


Entry: 3704
Our subname:
Tailoring Trainer
Aug 2004 subname:
Tailor


Entry: 3005
Our subname:
Leatherworking & Tailoring Supplies
Aug 2004 subname:
Tailoring Supplier


Entry: 3008
Our subname:
Apprentice Leatherworker
Aug 2004 subname:
Leatherworking Supplier


Entry: 3961
Our subname:
Food & Drink Vendor
Aug 2004 subname:
Grocer


Entry: 3010
Our subname:
Alchemy Supplies
Aug 2004 subname:
Alchemy Supplier


Entry: 332
Our subname:
Guildmaster of the Stormwind Assassins
Aug 2004 subname:
Leader of SI:7


Entry: 1339
Our name:
Mayda Thane (Needs Vendor List)
Aug 2004 name:
Mayda Thane


Entry: 338
Our name:
Mazen Mac'Nadir - (Texture Set)
Aug 2004 name:
Mazen Mac'Nadir


Entry: 2685
Our subname:
Engineering Supplies
Aug 2004 subname:
Superior Engineer


Entry: 2357
Our subname:
Horse Breeder
Aug 2004 subname:
Horse Trainer


Entry: 3184
Our subname:
Alchemy Trainer
Aug 2004 subname:
Alchemist


Entry: 3185
Our subname:
Herbalism Trainer
Aug 2004 subname:
Herbalist


Entry: 3513
Our name:
Christina
Aug 2004 name:
Miss Danna


Entry: 1751
Our name:
[PH] Mithras Ironhill
Aug 2004 name:
Mithras Ironhill


Entry: 3434
Our name:
Nak
Aug 2004 name:
Nak Orcbane


Entry: 2683
Our subname:
Engineering Supplies
Aug 2004 subname:
Engineer


Entry: 2380
Our subname:
Alchemy Supplies
Aug 2004 subname:
Alchemist


Entry: 3012
Our subname:
Enchanting Supplies
Aug 2004 subname:
Enchanting Supplier


Entry: 3412
Our subname:
Apprentice Engineer
Aug 2004 subname:
Engineering Trainer


Entry: 1700
Our subname:
Brewing Trainer
Aug 2004 subname:
Fisherman


Entry: 3684
Our subname:
Leather Armor Merchant
Aug 2004 subname:
Stylish Leathercrafter


Entry: 1747
Our name:
King Anduin Wrynn
Aug 2004 name:
Prince Anduin Wrynn


Entry: 2849
Our subname:
Cloth Armor and Accessories
Aug 2004 subname:
Light Armor & Tailoring Supplies


Entry: 1249
Our subname:
Armorer
Aug 2004 subname:
Armorer & Shieldcrafter


Entry: 1410
Our name:
Loranna Dawnfyre UNUSED (Reuse me)
Aug 2004 name:
Rakaiah Iceborne


Entry: 5050
Our name:
[UNUSED] Rallus
Aug 2004 name:
Rallus


Entry: 1474
Our subname:
Tailoring Supplies
Aug 2004 subname:
Tailor


Entry: 3625
Our subname:
General Goods
Aug 2004 subname:
Raptor Trainer


Entry: 3688
Our subname:
Pet Trainer
Aug 2004 subname:
Tallstrider Trainer


Entry: 241
Our name:
Remy "Two Times"
Aug 2004 name:
Remy Two Times


Entry: 1432
Our name:
[PH] Renato Gallina
Aug 2004 name:
Renato Gallina


Entry: 2699
Our subname:
Leatherworking Supplies
Aug 2004 subname:
Superior Leatherworker


Entry: 2684
Our subname:
Engineering Supplies
Aug 2004 subname:
Superior Engineer


Entry: 3543
Our subname:
Superior Armorsmith
Aug 2004 subname:
Armorsmith


Entry: 5637
Our name:
[PH] Roetten Stonehammer
Aug 2004 name:
Roetten Stonehammer
Our subname:
Reclaimers Inc. <Texture - Warrior/Explorer>
Aug 2004 subname:
Reclaimers Inc.


Entry: 1386
Our subname:
Alchemy Trainer
Aug 2004 subname:
Superior Alchemist


Entry: 3541
Our subname:
General Goods
Aug 2004 subname:
Drink Merchant


Entry: 3936
Our subname:

Aug 2004 subname:
General of the Sentinel Army


Entry: 2669
Our subname:
Tailoring Supplies
Aug 2004 subname:
Tailor


Entry: 3037
Our subname:
None
Aug 2004 subname:
Drum Merchant


Entry: 3361
Our subname:
Weapon Vendor
Aug 2004 subname:
Blade Merchant


Entry: 2622
Our name:
Sly Garrett
Aug 2004 name:
Sly Garett


Entry: 2855
Our subname:
Apprentice Tailor
Aug 2004 subname:
Superior Tailor


Entry: 1383
Our subname:
Apprentice Blacksmith
Aug 2004 subname:
Superior Blacksmith


Entry: 3413
Our subname:
Engineering Supplies
Aug 2004 subname:
Engineering Supplier


Entry: 1407
Our subname:
Light Armor & Weapons Merchant
Aug 2004 subname:
Rogue Trainer


Entry: 3366
Our subname:
Leatherworking Supplies
Aug 2004 subname:
Leatherworking Supplier


Entry: 3953
Our subname:
Leather Armor Merchant
Aug 2004 subname:
Leathercrafter


Entry: 4962
Our name:
Tapoke "Slim" Jahn
Aug 2004 name:
Tapoke Slim Jahn


Entry: 2999
Our subname:
Blacksmithing Supplies
Aug 2004 subname:
Blacksmithing Supplier


Entry: 984
Our subname:
Cloth & Leather Armor Merchant
Aug 2004 subname:
Cloth & Leather Merchant


Entry: 2857
Our subname:
Apprentice Engineer
Aug 2004 subname:
Superior Engineer


Entry: 3494
Our subname:
Engineering Trainer
Aug 2004 subname:
Engineer


Entry: 4195
Our subname:
Food & Drink Vendor
Aug 2004 subname:
Grocer


Entry: 3315
Our subname:
Cloth & Leather Armor Merchant
Aug 2004 subname:
Cloth Armor Merchant


Entry: 3478
Our subname:
Blacksmithing Trainer
Aug 2004 subname:
Blacksmith


Entry: 2819
Our subname:
Leatherworking Supplies
Aug 2004 subname:
Superior Leatherworker


Entry: 3623
Our name:
[UNUSED] Tursk
Aug 2004 name:
Tursk


Entry: 5169
Our subname:
Poison Vendor
Aug 2004 subname:
Shady Dealer


Entry: 3079
Our subname:
Leather Armor Merchant
Aug 2004 subname:
Leathercrafter


Entry: 3074
Our subname:
Leather Armor Merchant
Aug 2004 subname:
Leatherworker


Entry: 3492
Our subname:
Cloth & Leather Armor Merchant
Aug 2004 subname:
Clothier & Leathercrafter


Entry: 3682
Our subname:
Weaponsmith & Armorcrafter
Aug 2004 subname:
Ancient Blacksmith


Entry: 2872
Our name:
[UNUSED] Whaldak Darbenk
Aug 2004 name:
Whaldak Darbenk


Entry: 2533
Our name:
Stormwind Boy
Aug 2004 name:
William


Entry: 3485
Our subname:
Tailoring Supplies
Aug 2004 subname:
Tailoring Goods


Entry: 2670
Our subname:
Tailoring Supplies
Aug 2004 subname:
Superior Tailor


Entry: 5392
Our subname:
Miner
Aug 2004 subname:
Mining Trainer


Entry: 2530
Our subname:
Darkspear Hostage
Aug 2004 subname:
Darkspear hostage


Entry: 328
Our name:
Valdios Ellmara
Aug 2004 name:
Zaldimar Wefhellt


Entry: 3402
Our subname:
None
Aug 2004 subname:
Lockpicking Trainer


Entry: 2482
Our subname:
Superior Weaponsmith
Aug 2004 subname:
Superior Swordsmith


Entry: 3409
Our subname:
Weapon Vendor
Aug 2004 subname:
Axe Vendor


Entry: 3624
Our subname:
Pet Trainer
Aug 2004 subname:
Scorpid Trainer
