### ISSUE TITLE
TODO: Spawn Dylan Bissel

### ISSUE THREAD

**Issue by Daribon** [The-Alpha-Project/alpha-core#592]
**Describe what needs to be implemented or enhanced**
Dylan Bissel <Wolf Trainer> is currently not spawned in Goldshire.

**Expected end result**
Should be spawned in Goldshire.

**Guidance**
Current displayid doesn't exist in alpha, was later changed to a Dwarf and thats the displayid its currently using.

![world-of-warcraft-ss101091530907043_1083101](https://user-images.githubusercontent.com/6137576/187047583-1b2fd9a2-4d36-4933-9e79-2c6bc7d435f0.jpg)
![images_3207](https://user-images.githubusercontent.com/6137576/187047639-3de22f56-d10b-45ea-a5fd-d685fd7a48de.jpg)
![WoWScrnShot_032204_010105](https://user-images.githubusercontent.com/6137576/187047670-17cbd77f-f779-442a-a1dc-6e980fe99156.jpg)
![WoWScrnShot_052304_164802](https://user-images.githubusercontent.com/6137576/187047767-01850934-8b3b-49f5-96bf-d8e9f253daa3.jpg)

**Comment by geo-tp** [comment]
his display_id for 0.5.3 is probably 428
