### ISSUE TITLE
Lua error when opening bag

### ISSUE THREAD

**Issue by X-Genesis-Qhulut** [The-Alpha-Project/alpha-core#609]
**Describe the bug**
I equipped an extra bag (other than the backpack) however attempting to open it yields a Lua error message.

**Steps to reproduce**
1. With some character add a bag: .additem 1977
2. Equip that bag into a bag slot
3. Attempt to open the bag

**Expected behavior**
I expect to see the contents of the bag.

**Screenshots**

![error opening bag](https://user-images.githubusercontent.com/110961189/187366064-7a238185-ebcf-4ece-b6b3-6e41a4b0faf2.png)

**Comment by GrenderG** [comment]
This is 100% a client issue, most likely 20 slots bags weren't really supported in 0.5.3.
