### ISSUE TITLE
Mage spell Blizzard does not display the exected animation

### ISSUE THREAD

**Issue by X-Genesis-Qhulut** [The-Alpha-Project/alpha-core#610]
**Describe the bug**
When casting Blizzard, it seems to work as far as damage goes:

* You have a 2s cast time
* The mobs targeted aggro when the cast time is up
* The mobs take damage over time

However the animation at the end of the cast is very brief. It starts and immediately stops. However the tooltip says it does damage "over 10 seconds" so I expect to see the animation for 10 seconds.

**Steps to reproduce**
1. As a Mage, cast Blizzard
2. Note that the animation stops immediately after it starts, and does not last for 10 seconds.

**Expected behavior**
I expect the animation to continue for 10 seconds.

(Possibly this is a client bug, possibly the server is not telling the client the correct duration of the animation).

**Comment by GrenderG** [comment]
I can't reproduce this issue, the animation works fine for me until the channeling ends. Did you do anything in particular @X-Genesis-Qhulut? I tried with Rank 1 (ID 10).

**Comment by X-Genesis-Qhulut** [comment]
Hmm. Trying with the latest pull I see an animation on the caster, but the shards of ice pelting the target area stop immediately. This was with a new mage, boosted to level 24 to learn the spell, and then learning Blizzard level 1.


https://user-images.githubusercontent.com/110961189/187566042-ff6d864f-372c-4e73-bbd9-c7a7163fe21a.mp4

**Comment by X-Genesis-Qhulut** [comment]
Maybe it's a client thing. I can't see anything in the SMGs that got sent that would account for it. But when the tooltip says:

> Ice Shards pelt the target area doing 190 damage over 10 sec.

I expect to see ice shard pelting the target area TBH - over 10 seconds.

**Comment by X-Genesis-Qhulut** [comment]
These are the messages I saw:

```
[DEBUG] [31/08/2022 15:13:02] [127.0.0.1] <- Handling CMSG_CAST_SPELL
[DEBUG] [31/08/2022 15:13:02] [127.0.0.1] -> Sending  SMSG_SPELL_START n=40 0x10 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x10 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xa 0x0 0x0 0x0 0x0 0x0 0xd0 0x7
[DEBUG] [31/08/2022 15:13:02] [127.0.0.1] -> Sending  SMSG_PLAY_SPELL_VISUAL n=12 0x10 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xc5 0x0 0x0 0x0
[DEBUG] [31/08/2022 15:13:02] [127.0.0.1] -- Handling CMSG_CAST_SPELL
[DEBUG] [31/08/2022 15:13:04] [127.0.0.1] -> Sending  SMSG_CAST_RESULT n=5 0xa 0x0 0x0 0x0 0x0
[DEBUG] [31/08/2022 15:13:04] [127.0.0.1] -> Sending  SMSG_SPELL_GO n=38 0x10 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x10 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0xa 0x0 0x0 0x0 0x0 0x0 0x0 0x0
[DEBUG] [31/08/2022 15:13:04] [127.0.0.1] -> Sending  MSG_CHANNEL_START n=8 0xa 0x0 0x0 0x0 0x10 0x27 0x0 0x0
[DEBUG] [31/08/2022 15:13:04] [127.0.0.1] -> Sending  SMSG_SPELL_COOLDOWN n=16 0xa 0x0 0x0 0x0 0x10 0x0 0x0 0x0 0x0 0x0 0x0 0x0 0x60 0xea 0x0 0x0
[DEBUG] [31/08/2022 15:13:14] [127.0.0.1] -> Sending  MSG_CHANNEL_UPDATE n=4 0x0 0x0 0x0 0x0
[DEBUG] [31/08/2022 15:13:17] [127.0.0.1] <- Handling CMSG_PING
[DEBUG] [31/08/2022 15:13:17] [127.0.0.1] -> Sending  SMSG_PONG n=4 0x2 0x0 0x0 0x0
[DEBUG] [31/08/2022 15:13:17] [127.0.0.1] -- Handling CMSG_PING
```

MSG_CHANNEL_START was spell 10 for 10000 (ms) which sounds right.
SMSG_SPELL_COOLDOWN was spell 10 for 60000 (ms) which also sounds right.

And then no messages for 10 seconds.
