### ISSUE TITLE
Alliance mage can train teleport to Undercity

### ISSUE THREAD

**Issue by X-Genesis-Qhulut** [The-Alpha-Project/alpha-core#617]
**Describe the bug**
As a human mage I was able to train to teleport to Undercity. I also successfully teleported there, fortunately far enough away from the NPCs to not be attacked.

**Steps to reproduce**
1. Make a human mage.
2. Increase level enough to learn Teleport (ie. level 20).
3. Train Teleport to Undercity.

**Expected behavior**
You should not be offered to train to teleport to the other faction's cities.

**Screenshots**

![teleport to Undercity](https://user-images.githubusercontent.com/110961189/187828951-c6fd4e9c-ee16-4b87-8d01-1cc7d5a05b87.png)

**Comment by GrenderG** [comment]
Fixed in https://github.com/The-Alpha-Project/alpha-core/commit/f72c0d4a2e82bd090a1aeddb7628c99e8431b639
