### ISSUE TITLE
TODO: Change More Subnames

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#621]
**Describe what needs to be implemented or enhanced**
![WoWScrnShot_061604_113421](https://user-images.githubusercontent.com/72315006/188214313-35f96747-8e9e-471d-b9a0-783087c4cea3.jpg)
![p1](https://user-images.githubusercontent.com/72315006/188214323-0e495c52-0523-4dee-b61d-a2963c48088f.jpg)
![EEE32](https://user-images.githubusercontent.com/72315006/188214330-0bc328ad-7fdb-4cec-8502-675aaeb46c86.jpg)
![25 - 2Ps1uOA](https://user-images.githubusercontent.com/72315006/188214340-adc3a444-d970-4d26-86fd-1ff6a77116eb.jpg)
![23 - pLNt5OR](https://user-images.githubusercontent.com/72315006/188214346-14375ad9-7f72-49af-9810-f00222371c01.jpg)

![teuksung](https://user-images.githubusercontent.com/72315006/188214316-6a3e70e1-222d-432d-aad7-161e6ba831ff.JPG)

**Expected end result**
These mobs should use correct subname

**Comment by mindphluxnet** [comment]
None of these screenshots are from 0.5.3 tho so what do they prove?

**Comment by GrenderG** [comment]
> None of these screenshots are from 0.5.3 tho so what do they prove?

The database of alpha-core started with 1.2 data, so everything pre-1.2 is better than using 1.2 until older data can be found.
