### ISSUE TITLE
Young Wolves and Timber Wolves dis-located

### ISSUE THREAD

**Issue by Rhope79** [The-Alpha-Project/alpha-core#627]
**Describe the bug**
The Wolves of Northshire (my new bandname) have a tendency to occasionally not be hittable by melee.   I assume they are registered in different spots from server side to client side.  What causes this I dont know.  But I do know some buggy work arounds.

**Steps to reproduce**
1. Go to Northshire
2. Look for any wolf that is standing still for a prolonged period of time(1min +).
3.  Stand still facing it with Auto Attack running.

**Expected behavior**
You hit the wolf.

**Screenshots**

**Sources**
I would need a video.

PS:  Trying to auto attack these I have found also leaves you with no health regeneration and in combat.  What remedys the encounter is either usually a ranged attack (when facing the unknow right direction perhaps) or a self affecting spell, buff/heal that will cause threat and will pull the mob from its real location which will update on your screen.

**Comment by GrenderG** [comment]
Did you encounter this while playing in the PTR, or you setup your own server? If you encountered this in your own server, have you extracted the maps?

**Comment by Rhope79** [comment]
This was the 0.5.3 server,  I didnt set up my own server

**Comment by Rhope79** [comment]
This might be difficult as it feels like a disconnect between client and server

**Comment by Rhope79** [comment]
Ill get a video up later so you can see what it looks like

**Comment by GrenderG** [comment]
> Ill get a video up later so you can see what it looks like

Thanks that will definitely help.

**Comment by Rhope79** [comment]
https://www.youtube.com/watch?v=b2fir15y_VE

Seems to occasionally happen to any mob.   You can tell superficially if its bugged if its supposed to patrol and never does.   If it doesnt patrol, then you just have to walk up and see if you can hit it.
