### ISSUE TITLE
[Script] Quest trigger doesn't work.

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#630]
**Describe the bug**
Using [Ancient Flame](https://classic.wowhead.com/object=16393/ancient-flame) for the quest [Bashal'Aran](https://classic.wowhead.com/quest=957/bashalaran) while holding [Ancient Moonstone Seal](https://classic.wowhead.com/item=5338/ancient-moonstone-seal#provided-for) doesn't complete the quest objective.

**Steps to reproduce**
1. Take the [Bashal'Aran](https://classic.wowhead.com/quest=957/bashalaran)
2. Interact with [Ancient Flame](https://classic.wowhead.com/object=16393/ancient-flame)

**Expected behaviour**
Using [Ancient Flame](https://classic.wowhead.com/object=16393/ancient-flame) should complete the objective of [Bashal'Aran](https://classic.wowhead.com/quest=957/bashalaran)

**Comment by GizzleBizzle** [comment]
I've finally managed to do it after many tries on different characters so there is either a specific place one must stand or the object was bugged and a server restart fixed it.

Posting a screenshot with coords that worked for future testing
![obraz](https://user-images.githubusercontent.com/111394734/190870830-4f5ba6d9-feba-4f66-9af4-88059f299fb7.png)

**Comment by devw4r** [comment]
There was a crash related to object interaction that was fixed a couple of days ago, can you do two tests on the same quest with two different characters? Just to make sure this is fixed in order to close this issue.

**Comment by GizzleBizzle** [comment]
I've tested it 4 more times, from different locations and on different characters.

Everything works fine now.

**Comment by devw4r** [comment]
> I've tested it 4 more times, from different locations and on different characters.
> 
> Everything works fine now.

Tyvm

**Comment by GrenderG** [comment]
Can we close this issue then @GizzleBizzle?

**Comment by GizzleBizzle** [comment]
Yes, definitely. It works as intended now.
