### ISSUE TITLE
[Quest] Zenn's Bidding cannot be completed.

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#635]
**Describe the bug**
After collecting all the quest items for [Zenn's Bidding](https://classic.wowhead.com/quest=488/zenns-bidding) the quest cannot be completed. It is stuck on the turn-in page and doesn't want to move forward.

https://user-images.githubusercontent.com/111394734/190263111-38aff1aa-c9ea-4e35-9a9e-9f839c7ee316.mov

**Comment by X-Genesis-Qhulut** [comment]
Suggest:

```
UPDATE `quest_template` SET `ReqCreatureOrGOCount1` = 0 WHERE (`entry` = 488); 
```

That allowed the quest to complete for me. However he is supposed to transform into a rabbit or something (perhaps not in Alpha?) and I presume that part has to be scripted.
