### ISSUE TITLE
Phantom dmg when getting healed from food

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#636]
**Describe the bug**
There's a visual bug appearing before most of healing ticks from food (it has a varying offset, it doesn't always happen at the same interval). It doesn't show up in combat log, neither has any effect on health pool or combat state, It is purely visual.

**Steps to reproduce**
1. Lose a nice chunk of hp
2. Begin eating
3. Watch the character picture in the top-left corner.

https://user-images.githubusercontent.com/111394734/190265928-f594c542-7178-4c2b-b8c7-460f8a12d683.mov

**Comment by GrenderG** [comment]
Hmm I'm not being able to reproduce this.

**Comment by Fluglow** [comment]
May have been fixed by #855 with deferred combat log handling.
