### ISSUE TITLE
NPCs which should move randomly do not

### ISSUE THREAD

**Issue by X-Genesis-Qhulut** [The-Alpha-Project/alpha-core#646]
**Describe the bug**
Fighting the Mountain Cougars (entry 2961) - they are supposed to move around and not just stand in one place.
Their movement type (movement_type) is set to 1 (random).
The movement range is set to between 3 and 15.
For example, spawn_id 25747 is set to a movement range of 5.
However the NPC does not move.

**Steps to reproduce**
1. Go to -3427.72  -442.405  95.1764  1 (for example) and note that the cougars never move.

**Expected behavior**
They should wander around randomly.

**Comment by devw4r** [comment]
Did you manually modified the movement type?

movement_type is 2. (Waypoints)

Not yet implemented.

**Comment by X-Genesis-Qhulut** [comment]
Not at all. movement_type is 1 (random).

https://wow-refugee.com/alpha/index.php?action=show_creature&id=2961&filter=2961&sort_order=name&pos=1&max=1

**Comment by X-Genesis-Qhulut** [comment]
Ah I see now that there is movement_type of 1 on the creature_template but movement_type 2 on the spawns_creatures entry.

**Comment by X-Genesis-Qhulut** [comment]
I just set the movement_type to 1 for the spawns_creatures entries for those cougars and they looked a lot more realistic. You surely are not going to set up waypoints for 73 mountain cougars are you? Much easier to switch the movement type to 1.

**Comment by X-Genesis-Qhulut** [comment]
There would be no proof of exactly what waypoints 73 mountain cougars used, so I strongly recommend just making them random movement. If you want to find others that are using waypoints right now you can run this:

```
select name from spawns_creatures AS T1 
            left join creature_template on spawn_entry1 = entry 
            where T1.movement_type = 2 and ignored = 0 
            group by spawn_entry1 order by name;
```

**Comment by devw4r** [comment]
Their movement behavior is not set by us, that was probably sniffed from retail, so even if it doesn't make 'sense' we should honor that behavior, else we could probably apply that way of thinking to other stuff and just be done with it. Ofc you are free to override behavior on any local db. You might want to rename the issue title to something like 'Implement Movement Type: Wayponts' or something.

Thx for the report.

**Comment by GrenderG** [comment]
We actually have the waypoints, we just need to port the creature_movement table from VMaNGOS and add waypoint movement handling to our core. Any idea about why they are using waypoints instead of normal wandering @ratkosrb? I checked their waypoints and they seem to be very small, like actual wandering. The template has movement_type = 1 but all of the spawns have movement_type = 2 except one (guid 25723) that has movement_type = 0.

**Comment by X-Genesis-Qhulut** [comment]
I would just be very surprised if, when rushing to get the game out the door, they would sit down and set up 73 sets of waypoints (and that is just for the cougars, no doubt there are others) when setting the movement types to random would make the mobs behave in much the same way.

I can understand waypoints for someone like Fozruk, who wanders along a set path which is not at all random. Similarly for other mobs that patrol around the place, like guards.

Even if the waypoints exist in MaNGOS that is not really proof they were in the alpha game.

As an interim measure, since the waypoint code is not implemented, why not switch them to random for now, make it look more natural, and if you really want to, switch them back to waypoints later?

**Comment by GrenderG** [comment]
Because we are in no rush to "finish" the emulator, so no need to implement wrong temporary stuff unless it's 100% needed. Anyway let's wait until @ratkosrb answers since it might be an error :+1:

**Comment by ratkosrb** [comment]
Nicky has added tons of waypoints based on classic, so it's possible he added it for these mobs too.
