### ISSUE TITLE
Quest-givers with placeholder models do not show "?" or "!" over them

### ISSUE THREAD

**Issue by X-Genesis-Qhulut** [The-Alpha-Project/alpha-core#656]
**Describe the bug**
Quest givers (or finishers) who are shown on-screen with placeholder model do not have "?" or "!" over their heads in yellow.

**Steps to reproduce**
1. Go to a quest-giver with a placeholder model, for example Pilot Bellowfix (pictured).
2. Observe the absence of the "?" or "!" over their head

**Expected behavior**
They should show "?" or "!" over their head, whether or not they have a known model (the place-holder is a model, after all)

**Screenshots**

![Screenshot from 2022-09-25 14-45-51](https://user-images.githubusercontent.com/110961189/192128877-e8b66492-9a09-4d35-b00e-83620642e5f5.jpg)

**Comment by devw4r** [comment]
Client issue.
