### ISSUE TITLE
TODO: Change Rathorian's Display ID

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#672]
Rathorian was a dreadlord before Blizz created a felguard model.

There are two identical dreadlord displayIDs in the catalogue, either one should work.
- 130
- 348

Source (from 0.5.5)
![normal_WoWScrnShot_032404_023005](https://user-images.githubusercontent.com/111394734/194320357-a4ca12f7-ad8f-4f43-a92f-44dec236d028.jpg)

**Comment by fuzionproject** [comment]
Will be fixed
