### ISSUE TITLE
[Core] Debuffs improve their respective skills only when damaging mobs.

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#678]
**Describe the bug**
Abilities, that don't damage mobs in any way do not improve their skills upon using.
On the other hand damage over time effects can improve the skill with each tick of damage.

**Steps to reproduce**
First Method
1. Create a warrior.
2. Learn shouts, taunt and inner rage (which drops cooldown after relogging) for quick rage generation. 
3. Spend the next 20 minutes shouting at boars and taunting them over and over.
4. Reevaluate your life.

Second method
1. Use Corruption on any target (remember to have Shadow Magic skill learned)

**Expected behavior**
 The skill improvement check should be made upon using an ability, not with every damage dealt of that ability.

**Screenshots**
From patch 0.6
![WoWScrnShot_051304_053542](https://user-images.githubusercontent.com/111394734/194782533-9ee2e7fd-4593-4dce-b628-8755b876c57f.jpg)
From patch 0.6
![WoWScrnShot_050804_053404](https://user-images.githubusercontent.com/111394734/194782541-82859f62-8335-4271-8f2f-eb7021e188c1.jpg)
From patch 0.5.5
![WoWScrnShot_032704_160107](https://user-images.githubusercontent.com/111394734/194782592-1129f3c8-ecc1-4364-a6d1-0b4a2b3b3c12.jpg)

**Comment by fuzionproject** [comment]
is a class bug? to know

**Comment by GizzleBizzle** [comment]
No, I tested other classes.
