### ISSUE TITLE
AoE spells' arbitrary damage intervals.

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#696]
**Describe the bug**
AoE abilities sometimes do not deal damage with all of their ticks. 
Tested on multiple mobs, with Flamestrike, Blizzard and Lightning Storm, but most likely all AoE spells are affected

Flamestrike (should deal initial hit two 15 dmg ticks)
https://user-images.githubusercontent.com/111394734/197388391-fa2e5803-b106-4ce5-9c0d-6456f1298b5a.mov

Lightning storm (should deal the initial hit + 3 ticks of damage afterwards. I've seen it deal anywhere between one and four ticks, but for some reason this ability buggs the most often for me.
https://user-images.githubusercontent.com/111394734/197388503-9bd51963-f1c2-40e6-a1bf-127bf425b79b.mov

Blizzard (should have 5 intervals every 2 seconds)
https://user-images.githubusercontent.com/111394734/197388836-cdff1cea-d57b-4ac3-be17-78de11bbd2e6.mov

Flash bundle (should deal initial hit + two 15 dmg ticks)
https://user-images.githubusercontent.com/111394734/197389401-295ce0f9-b49d-448a-9fb2-4e78fe0ab674.mov

**Expected behaviour**
The only two ways mobs can avoid AoE damage while standing int he spell's radius should be:
- No line of sight between the target and the aoe spell's center (a wall between them, for example)
- Tick resist, info of which should be displayed in the combat log.

As both of those methods aren't implemented yet, It is considered a bug.

**Comment by GrenderG** [comment]
Not exactly related with this issue, but I noticed that if you move after having casted Flamestrike, spell will appear as Interrupted even though you aren't channeling anything.
