### ISSUE TITLE
Warlock minions don't start with full hp at higher lvls.

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#714]
**Describe the bug**
Minions scale only their maximum health pool with level, without adjusting the actual hp they have aswell.
Tested on all warlock minions.

**Steps to reproduce**
1. summon any minion at high lvl (tested on lvl 25 and 60)

**Expected behavior**
Summoned minions should always begin with full hp and mana.

**Video**
https://user-images.githubusercontent.com/111394734/199618172-c63448f1-87fc-4f64-a671-b571a8270a43.mov

**Comment by Fluglow** [comment]
Closed by #774.
