### ISSUE TITLE
Palemane Poacher's quick shot is too quick.

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#716]
**Describe the bug**
[Palemane Poachers](https://db.thealphaproject.eu/index.php?action=show_creature&id=2951&filter=poacher&sort_order=name&pos=1&max=2) spam their [Quick Shot
](https://db.thealphaproject.eu/index.php?action=show_spell&id=1516) ability, which can absolutely destroy anyone in a similar lvl range. 

**Steps to reproduce**
1. Pick a fight with a poacher

**Expected behavior**
If the info about Poachers having this ability comes from a valid source, then most likely this ability should have a 1 min cooldown like it currently does in 1.12.1 version. I would strongly advise giving this ablitiy a cooldown, since it's impossible to do this quest solo now.
 
**Screenshots**
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/WoWScrnShot_043004_145900.jpg
https://archive.thealphaproject.eu/media/Alpha-Project-Archive/Images/Azeroth/Kalimdor/Mulgore/WoWScrnShot_043004_145902.jpg

**Video**
https://user-images.githubusercontent.com/111394734/199623720-3d801b4d-1a28-4ff9-8db8-727a66032751.mov

**Comment by GrenderG** [comment]
Seems to still be happening according to @GizzleBizzle.
