### ISSUE TITLE
Purge doesn't behave the way it should.

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#730]
**Describe the bug**
[Purge](https://db.thealphaproject.eu/index.php?action=show_spell&id=370&filter=purge&sort_order=Name_enUS&pos=1&max=4) can be cast on enemy targets only, despite what is written in its tooltip. No defensive purges can be currently made with this ability.

**Steps to reproduce**
1. Try purging a debuff from a friendly target.

**Expected behavior**
According to the tooltip, purge can be used offensively to take off enemy's beneficial spell as well as defensively, to take off harmful effects from friendly targets.

**Sources**
Purge In-game tooltip.

**Comment by Fluglow** [comment]
Client issue/mistake by original developers.
1. The spell has a target type that restricts the client to attackable targets only
2. The description was changed to the following in 0.5.5 to match the targeting:
`Purges the enemy target, removing $m1 magic $leffect:effects;.`
