### ISSUE TITLE
Crippling poison doesn't wear off

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#755]
**Describe the bug**
[Crippling poison](https://db.thealphaproject.eu/index.php?action=show_spell&id=3408) lasts for 30 minutes and procs every hit. If a rogue coats both weapons he can apply -60% movement speed penalty.

**Expected behavior**
[Crippling poison](https://db.thealphaproject.eu/index.php?action=show_spell&id=3408) shouldn't have a duration and should wear off the weapon after the first proc.

**Sources**
In-game tooltip.
![poison](https://user-images.githubusercontent.com/111394734/203444607-c8f37a87-b4a4-4dde-8ed9-5799ee7a9448.png)

**Comment by devw4r** [comment]
Both [Crippling poison](https://db.thealphaproject.eu/index.php?action=show_spell&id=3408) (Parent spell) and  [Poison (Snare)](https://db.thealphaproject.eu/index.php?action=show_spell&id=3409) (Proc spell) have 0 proc charges. So this might just be a wrong tooltip. @Fluglow ?

**Comment by Fluglow** [comment]
I don't think it's a tooltip issue. Enchant charges aren't implemented yet, and this is the only enchant that would use them as far as I can tell. We already have `spell_enchant_charges` in the world database for this behavior, but it contains data for vanilla (charges for Deadly Poison/Mind-numbing Poison).
