### ISSUE TITLE
More Health Funnel Issues.

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#758]
**Describe the bug**

- [ ] First Issue

As long as the minion is visible, health funnel can transfer health to it.

Theoretically it can still be cast if the minion is outside of vision range, but it doesn't transfer health.

**Steps to reproduce**
1. Attack a mob with a minion
2. Move outside of 20y range
3. Cast Health Funnel

**Expected behavior**
Casting Health Funnel shouldn't be possible if the distance between the caster and its minion is more than 20 yards and health funnel should cancel once a minion runs away from that range.

**Sources**
in-game tooltip

**Video**
https://user-images.githubusercontent.com/111394734/203666606-facb3a7c-df05-4fbb-97f2-c553c3cc8fa6.mov

- [ ] Second issue

**Describe the bug**
Only the first rank of health funnel applies an icon on the caster.
Only the icon is missing, everything else works great.

**video**
https://user-images.githubusercontent.com/111394734/203666665-3fb67a7e-7a36-486c-83ac-8b7d45d724db.mov

**Comment by GizzleBizzle** [comment]
A small errata - After double-checking with @Kadiro, who is more knowledgable when it comes to warlocks it seems, that health funnel **shouldn't**  break when a minion moves outside of funnel range when it is being channeled.

The rest of the issue is still valid, though.

Sorry for confusion, Mandella effect, I guess.

**Comment by devw4r** [comment]
> A small errata - After double-checking with @Kadiro, who is more knowledgable when it comes to warlocks it seems, that health funnel **shouldn't** break when a minion moves outside of funnel range when it is being channeled.
> 
> The rest of the issue is still valid, though.
> 
> Sorry for confusion, Mandella effect, I guess.

I think this should be covered, range validation is done upon cast attempt.

**Comment by GizzleBizzle** [comment]
> I think this should be covered, range validation is done upon cast attempt.

Indeed it is, We've just checked it and it works the way it should.
As I said, the rest of the issue is still valid.
