### ISSUE TITLE
TODO: Change Hogan Ference's DisplayID

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#778]
[Hogan Ference](https://db.thealphaproject.eu/index.php?action=show_creature&id=325&filter=Hogan&sort_order=name&pos=1&max=1)'s DisplayID should be changed to 1724

Source (First days of 0.5.5)
https://web.archive.org/web/20051025050314/http://kevinho.net/gallery/albums/wowbeta/j2_1.jpg

**Comment by GrenderG** [comment]
This is fixed then @GizzleBizzle?

**Comment by GizzleBizzle** [comment]
Hogan Ference is a cube, but I confused him with another NPC in this room so I closed it to prevent someone from changing his DisplayID to an incorrect one.
