### ISSUE TITLE
TODO: Move Kaebrus Survival trainer

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#780]
**Describe what needs to be implemented or enhanced**
![SW2](https://user-images.githubusercontent.com/72315006/205934564-3648e007-3ac1-4248-a593-19b481d2b226.png)
located in SW park.
![swn](https://user-images.githubusercontent.com/72315006/205934978-d006d9c3-8731-485f-bb4d-997acd52b40d.png)

https://db.thealphaproject.eu/index.php?action=show_creature&id=5501&filter=kaer&sort_order=name&pos=1&max=1

**Expected end result**
Move 5501 Kaerbrus to SW park.

**Comment by Daribon** [comment]
'Always a good skill to have that Survival is.\n\nKaerbrus is who you are looking for. He\'s usually around the moonwell in the Park.', 3008, 7, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 31727),

From broadcast text.
