### ISSUE TITLE
TODO:  Move and update Bale Survival Trainer

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#781]
**Describe what needs to be implemented or enhanced**
![Capture d’écran_2022-12-06_20-52-22](https://user-images.githubusercontent.com/72315006/206009128-b06c054f-347c-4289-a15c-216398ccc158.png)
![thunderbluff](https://user-images.githubusercontent.com/72315006/206009140-eaf169db-42e7-4c0c-9bcd-6bf3174d8323.jpg)

https://db.thealphaproject.eu/index.php?action=show_creature&id=2806&filter=bale&sort_order=name&pos=1&max=1

**Expected end result**
Update subname and move 2806 Bale

**Comment by Daribon** [comment]
From broadcast text:
'You, in harmony with nature, and only your skills to survive.  This is the way that the Earth Mother intended it to be.  You will want to find Bale on the Hunter Rise.', 5493, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 31727)

So yes, above image seems correct.
