### ISSUE TITLE
TODO:  Move Kar Stormsinger Bird Trainer

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#785]
**Describe what needs to be implemented or enhanced**
![wow04041604_1082104426](https://user-images.githubusercontent.com/72315006/206579160-f337c6ec-8c87-482a-be3b-4623895aff57.jpg)

1.12 model
![20274-kar-stormsinger](https://user-images.githubusercontent.com/72315006/206579193-217268ab-d8d9-401c-990a-31b3fac11efc.jpg)

https://db.thealphaproject.eu/index.php?action=show_creature&id=3690&filter=kar+storm&sort_order=name&pos=1&max=2

**Expected end result**
3690 Kar Stormsinger should be moved to screenshot location, subname should be updated to `<Bird Trainer>`

**Comment by Daribon** [comment]
Yep, should have the subname <Bird Trainer>.

http://web.archive.org/web/20041115021303/http://wow.allakhazam.com/db/mob.html?wmob=3690
