### ISSUE TITLE
TODO: Move Denni'ka Survival Trainer

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#791]
**Describe what needs to be implemented or enhanced**
![survival](https://user-images.githubusercontent.com/72315006/206737110-bb5debae-6f34-480c-80cf-fad4602e281a.png)
![Capture d’écran_2022-12-09_13-20-12](https://user-images.githubusercontent.com/72315006/206737124-cecef157-e714-4b77-b44b-93991fe2eae9.png)

http://web.archive.org/web/20041114232607/http://wow.allakhazam.com/db/mob.html?wmob=3411
https://db.thealphaproject.eu/index.php?action=show_creature&id=3411&filter=denni&sort_order=name&pos=1&max=1
Located In Orgrimmar

**Expected end result**
Should be at same spot than First Aid Trainer
Move 3411 Denni'ka to right spot, change subname to Survival Trainer and change flag

**Comment by Daribon** [comment]
Denni\'ka can show you how to keep warm.  Look for her at Survival of the Fittest, a hut on the shore of the lake next to the Spirit Lodge.  Head up above and west of the Valley of Strength.', 4787, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 31727),

I prefer my food raw, but if you like yours cooked Denni\'ka can show you how to light a fire.  Find her at Survival of the Fittest, a hut on the shore of the lake next to the Spirit Lodge.  Look for it up above and to the west of the Valley of Strength.', 4786, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 31727),
