### ISSUE TITLE
Can see some mobs levels who are >10 above you, but not others.

### ISSUE THREAD

**Issue by dirtbikercj** [The-Alpha-Project/alpha-core#807]
**Describe the bug**
Can see some mobs levels who are >10 above you, but not others.

**Steps to reproduce**
be level 1 
.tel crossroads
find creatures and see if you can see their levels.

**Expected behavior**
Should not be able to see levels >10 above player level on any mob.

**Screenshots**
![image](https://user-images.githubusercontent.com/62989449/209243716-7d9a8c8c-0841-4ce9-9719-0fc09e8d52ee.png)
![image](https://user-images.githubusercontent.com/62989449/209243725-d88719e8-ee26-42ba-9085-5a516d6c4a7f.png)
<img width="968" alt="image" src="https://user-images.githubusercontent.com/62989449/209243765-111433d6-c742-4068-ad7f-32702f69dfc8.png">
<img width="968" alt="image" src="https://user-images.githubusercontent.com/62989449/209243783-b256467e-fe92-4084-a32b-f1601c057726.png">

**Comment by GrenderG** [comment]
Need to properly investigate this issue, it might be entirely client related.

**Comment by devw4r** [comment]
This is client handled and should be closed.

```
          ActivePlayer = ClntObjMgrGetActivePlayer();
          v29 = ClntObjMgrObjectPtr((unsigned int)aDBuildBuildwow_118, 572, ActivePlayer);
          msg.m_read = (unsigned int)v29;
	  // Hated/Hostile AND Player level <= target level - 15 (Hidden/Lethal Screenshot #1)
          if ( v29 // Player = v29 , Unit = v8
            && CGUnit_C::UnitReaction(v8, (CGUnit_C *)v29) <= 1
            && *(_DWORD *)(*(_DWORD *)(msg.m_read + 56) + 104) <= v8->m_unit->level - 15 )
          {
            v30 = FrameScript_GetText(aUnitLethalLeve, -1, GENDER_NOT_APPLICABLE);
            SStrCopy((char *)v52, v30, 0x80u);
            CGTooltip::AddLine(this, (const char *)v52, &s_normalColor, 0);
          }
	  // Not 'lethal' (Visible)
          else
          {
            v31 = v8->m_unit;
            v48 = v31->level;
            if ( (v31->flags & 0x40) != 0 ) // Plus mob 'UNIT_FLAG_PLUS_MOB'
              v45 = FrameScript_GetText(aUnitPlusLevelT, -1, GENDER_NOT_APPLICABLE);
            else // Normal
              v45 = FrameScript_GetText(aUnitLevelTempl, -1, GENDER_NOT_APPLICABLE);
            SStrPrintf((char *)v52, 0x80u, v45, v48);
            CGTooltip::AddLine(this, (const char *)v52, &s_normalColor, 0);
          }
```
