### ISSUE TITLE
Missing Model in Stormwind

### ISSUE THREAD

**Issue by Daniel3614** [The-Alpha-Project/alpha-core#809]
Missing model for the NPC Rema Schneider.
![1](https://user-images.githubusercontent.com/73966356/209246927-e610c6b7-abe1-4fb6-8e74-a80c1b4347e9.PNG)

**Comment by dirtbikercj** [comment]
Duplicate of #796

**Comment by Daniel3614** [comment]
![Uploading 2.PNG…]()
Same with Suzetta Gallina
