### ISSUE TITLE
Quest/Item: Young lovers/unknown reward

### ISSUE THREAD

**Issue by dirtbikercj** [The-Alpha-Project/alpha-core#814]
**Describe the bug**
The quest  [young lovers](https://db.thealphaproject.eu/index.php?action=show_quest&id=106&filter=Young+lovers&sort_order=Title&pos=2&max=2) rewards an [Unknown reward](https://db.thealphaproject.eu/index.php?action=show_item&id=1217)

**Steps to reproduce**
.qadd 106
look at reward

**Expected behavior**
Rewarded item should not be unknown

**Screenshots**
<img width="254" alt="image" src="https://user-images.githubusercontent.com/62989449/209324806-3a1d28ee-2c58-4c04-b0d7-f21abeac6ef1.png">

**Comment by GrenderG** [comment]
Not a bug, this information comes from original WDB data. https://github.com/The-Alpha-Project/alpha-core/commit/60c1170d34eda032d44fd646bece72719622a342

**Comment by mindphluxnet** [comment]
While the displayed "reward" is correct, the quest reward doesn't currently function as intended as the player is indeed rewarded with "Unknown Reward", a worthless item.

As far as I know this is the only quest working like that. On quest resolution the server converts the "Unknown Reward" into the actual items, two Lesser Healing Potions.

This should probably be fixed. As it's only needed for that single quest one could likely hardcode it in QuestManager.handle_choose_reward() and simply replace the "reward" with two Lesser Healing Potions.

**Comment by Yushe** [comment]
Completing the quest does give you the "Unknown Reward" item.
Its possible that it was meant to have different functionality and wasn't just a placeholder to indicate to quest designers that this quest needs an actual reward added.

Within the database there is a quest called [Deep Ocean Vast Sea](https://db.thealphaproject.eu/index.php?action=show_quest&id=982) which mentions that it needs a reward.
This quest does not have any reward set.

Until more hints of what this item was meant to do is uncovered this is my best guess after looking around.

**Comment by mindphluxnet** [comment]
No, the quest was identical in vanilla retail. I played from the very first day of US retail and still remember it. It was also identical in EU retail.

**Comment by mindphluxnet** [comment]
According to http://web.archive.org/web/20041120143705/http://wow.allakhazam.com/db/quest.html?wquest=114 the reward listed was indeed "Unknown Reward" and in the comments (from 2004!) someone posts that the actual reward was 5 Minor Healing Potions.

**Comment by GrenderG** [comment]
The quest was updated in Allakhazam the 5th of October and the comment is from the 12th of November so it could also be that in the span of that month Blizz added the actual rewards but it wasn't still reflected in Allakhazam.
