### ISSUE TITLE
TODO:  Move Rellian Greespyre

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#821]
**Describe what needs to be implemented or enhanced**
![wow_art_darnassus](https://user-images.githubusercontent.com/72315006/209481126-31c86c94-4924-43c1-a77a-2130e16b9efd.jpg)

**Expected end result**
3517 Rellian Greenspyre should be moved to darnassus entrance, display_id should be 2572 
https://db.thealphaproject.eu/index.php?action=show_creature&id=3517&filter=greenspy&sort_order=name&pos=1&max=1

**Comment by mindphluxnet** [comment]
There's an Ancient Protector standing on the spot you want Rellian moved to, where does he go? He's not visible on the screenshot.

**Comment by Fluglow** [comment]
The Ancient Protector has waypoints that we're just not using yet, so it shouldn't cause an issue with placement.

**Comment by mindphluxnet** [comment]
Alright, I'll whip up a change.
