### ISSUE TITLE
Empty and Leaded Vial Money Duplication Issue

### ISSUE THREAD

**Issue by radongc** [The-Alpha-Project/alpha-core#828]
**Describe the bug**
Empty vial stacks cost 2c, but sell to vendors for 5c. Leaded vial stacks cost 20c, but sell for 25c.

**Steps to reproduce**
1. Purchase a stack of either Leaded Vial or Empty Vial
2. Sell back to vendor
3. You will have more money than you started with.

**Expected behavior**
All items should sell back to the vendor for less than they can be purchased for.

**Comment by geo-tp** [comment]
![Capture d’écran_2022-12-27_06-21-11](https://user-images.githubusercontent.com/72315006/209681586-26f49719-ffe8-4609-af6b-b163f7ab01ea.png)
![Capture d’écran_2022-12-27_06-20-51](https://user-images.githubusercontent.com/72315006/209681590-85c3a603-f8e6-4021-9284-ae03508f3e2d.png)
![Capture d’écran_2022-12-27_06-20-30](https://user-images.githubusercontent.com/72315006/209681606-f5e0e05f-7c6c-434e-8f4b-b5432e2d3f96.png)
