### ISSUE TITLE
TODO: Add mob in Duskwood

### ISSUE THREAD

**Issue by Raynbock** [The-Alpha-Project/alpha-core#838]
Missing mob in Duskwood, probably entry 200, Shambling Skeleton, seen on an e3 image from 2003 and listed on the warcry map. Probably level 20-21
https://cdn.discordapp.com/attachments/700043968892764300/1058193917817933914/king_day03_1215.JPG
https://cdn.discordapp.com/attachments/700043968892764300/1058193917364936764/image.png

**Comment by mindphluxnet** [comment]
This seems to be related to the quest "The Night Watch" which had slightly different objectives:

The Night Watch (1)
From: Commander Elthea Ebonlocke (Darkshire)
Description: Kill 6 Skeletal Warriors, 6 Skeletal Mages, and 6 **Shambling Skeletons**
Reward: 18 silver, 78 copper
Class: All

[Source](https://crawler.thealphaproject.eu/mnt/crawler/media/Website/ultimategamers/web.archive.org/web/20040529080132/http:/www.ultimategamers.com/worldofwarcraft/quests/duskwoodquests.html)

The question remains which patch changed the quest. None of the patch notes past 0.5.3 mention Duskwood changes.

Allakhazam also lists them to be present in Tranquil Gardens Cemetary, Duskwood at level range 20-21. However, the same site also lists the quest shown above with the new requirements (but also lists Shambling Skeleton as being related ...)

Pretty sure the quest in it's original form was present in 0.5.3 until at least patch 0.5.5 (when the NDA was lifted).

**Comment by geo-tp** [comment]
Here's some links about this mob

https://web.archive.org/web/20040911021927/http://www.goblinworkshop.com/quests/the-night-watch.html

https://web.archive.org/web/20041114105136/http://wow.allakhazam.com/db/mob.html?wmob=200

https://crawler.thealphaproject.eu/mnt/crawler/media/Website/warcry.com/Atlas-May-June-2004/WoW%20Warcry%20-%20Content%20-%20Atlas%20-%20Duskwood.php.html

**Comment by geo-tp** [comment]
![king_day03_1211](https://user-images.githubusercontent.com/72315006/220663814-a30179a7-e5c9-4223-9dda-326e9cbf13ad.JPG)
![king_day03_1215](https://user-images.githubusercontent.com/72315006/220663827-f1ddd409-063b-47c2-9ec5-fdf95051a9ff.JPG)
