### ISSUE TITLE
TODO: Add NPC to Stormwind

### ISSUE THREAD

**Issue by Raynbock** [The-Alpha-Project/alpha-core#839]
Corbett Schneider (ID1433) is marked on Warcry´s 0.6 map, maybe in the game already? On retail he walks from the cheese shop to the Schneider Tailoring shop, maybe thats the case here too, since his location was added at the cheese shop. 
https://cdn.discordapp.com/attachments/521831233966309396/1058214190667550811/image.png

**Comment by mindphluxnet** [comment]
This should be closed.

Corbett Schneider only spawns after a player has turned in the quest "Harlan Needs A Resupply" (333). He's then going through his scripted routine of fetching and delivering the requested goods to Harlan. After that he goes shopping at Trias' Cheese and returns to his shop where he despawns.

With scripting and waypoint movements being now implemented this should already (mostly) work. The quest end script and his waypoints are present and working, only the scripts at several waypoints aren't running yet.

**Comment by GrenderG** [comment]
Closed in favor of https://github.com/The-Alpha-Project/alpha-core/issues/300
