### ISSUE TITLE
Smite doesn't generate threat

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#851]
**Describe the bug**
[Smite ](https://db.thealphaproject.eu/index.php?action=show_spell&id=585&filter=smite&sort_order=Name_enUS&pos=1&max=26)doesn't seem to generate any hate towards the target. Mobs don't aggro when hit by this spell. 
Tested on different mobs using different ranks of smite

**Steps to reproduce**
1. Attack any target with a smite spell.

**Expected behavior**
Smite should generate threat.

**Video**
https://user-images.githubusercontent.com/111394734/210158398-25b367fb-be70-4d29-95b9-97424fde34f4.mov

**Comment by devw4r** [comment]
Fixed here https://github.com/The-Alpha-Project/alpha-core/pull/846
