### ISSUE TITLE
Trainer Spell Availability Issue

### ISSUE THREAD

**Issue by radongc** [The-Alpha-Project/alpha-core#858]
**Describe the bug**
Occasionally, spells that should be unavailable will appear as available for training on profession & class trainers.

**Steps to reproduce**
1. Open a profession trainer window.
2. Click around randomly on unavailable spells
3. Eventually, they should appear green.
4. If that doesn't work, do something that causes the player to update. Ex. level up while a trainer window is open
5. Some or all of the unavailable spells will become green and trainable.

**Expected behavior**
Spell availability should be determined by skill, level, previous spell, or other checks, and red spells should never become green if the proper conditions haven't been met.

**Screenshots**
![WoWClient_PIwqPgt6kZ](https://user-images.githubusercontent.com/51402068/210496898-891be9ce-8e48-4feb-9f0d-8a351105f502.jpg)

**Comment by GrenderG** [comment]
I wonder if this is a client issue :thinking:

**Comment by Fluglow** [comment]
> I wonder if this is a client issue 🤔

Maybe the client expects updates for open trainer lists when other updates happen? The list could be changed by level/skill up etc.

**Comment by devw4r** [comment]
They client itself has hooks for different events in order to refresh TrainerList state, if we force an update, the current list will reset user selection, scrolling, etc.

**Comment by devw4r** [comment]
void __thiscall CGPlayer_C::OnLevelChange(CGPlayer_C *this)
{
  CGObjectData *m_obj; // eax
  unsigned int m_guid; // edi
  unsigned int m_guid_high; // ebx

  m_obj = this->m_obj;
  m_guid = m_obj->m_guid;
  m_guid_high = HIDWORD(m_obj->m_guid);
  if ( __PAIR64__(m_guid_high, m_guid) == ClntObjMgrGetActivePlayer() )
  {
    CGSpellBook::UpdateSpells();
    CGClassTrainer::RefreshList(); <----
    CGPlayer_C::UpdateQuestStatusAll();
  }
  CGUnit_C::OnLevelChange(this);
}

**Comment by radongc** [comment]
We can also check the conditions for avail/unavailable again on spell buy, (and then refresh the list?) if conditions are not met to partially fix this. Currently in this scenario spells that appear green clientside can be trained. At least that way, the spells cannot be bought.
