### ISSUE TITLE
Profession trainer overwrite

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#903]
**Describe the bug**
Hiding the learnable recipe at a trainer by using the plus/minus icon rewrites its description with previously selected visible patterns from the "Skills" group. I seems connected to #259 

**Steps to reproduce**
1. Click either Journeyman Engi or Expert Engi at the trainer
2. Click a random recipe from the "recipes" subgroup
3. Click "-" at the "recipes" subgroup, hiding all the recipes
4. Some of the previously clicked Engi information carries over to the recipe description box.

**Expected behavior**
The information should stay the same until we click a new recipe/skill

**Video**
https://user-images.githubusercontent.com/111394734/218342294-0d290ffc-a52b-4455-87b8-9f052fa017ae.mov

**Comment by GrenderG** [comment]
Most likely client related, but worth a check.

**Comment by devw4r** [comment]
There is no client-server interaction when you browse/select/expand/collapse/filter this lists, server just provides the initial array of items, client takes it from there, hence, there is nothing we can do to solve this.
