### ISSUE TITLE
Sentinel Hill, Westfall: NPC stuck in the ground

### ISSUE THREAD

**Issue by mindphluxnet** [The-Alpha-Project/alpha-core#904]
**Describe the bug**
At Sentinel Hill, Westfall, a lumberjack NPC is stuck in the ground due to a wrong Z coordinate.

**Steps to reproduce**
1. Visit Sentinel Hill, Westfall
2. Check on the lumberjack in front of the sawmill

**Expected behavior**
He's not supposed to be stuck in the ground.

**Screenshots**
![image](https://user-images.githubusercontent.com/4683319/218343584-8b3a242c-017d-4d48-968e-17d4306fdc41.png)

**Suggestion** 

Set his Z coordinate to 34.408

**Comment by devw4r** [comment]
You could probable fix this and include it on #902 ? 👍
