### ISSUE TITLE
[Needs Investigation] Talent purchase issues

### ISSUE THREAD

**Issue by mindphluxnet** [The-Alpha-Project/alpha-core#906]
**Describe the bug**

- [x] Talents > rank 1 cost less than advertised

Purchases of talents beyond rank 1 cost significantly less than the displayed cost:

![image](https://user-images.githubusercontent.com/4683319/218817444-715b467e-fb18-4c22-867d-6d7c06c6def0.png)
Paladin - Mace Finesse Rank 2 - 30 TP

Before purchasing I have 55 TP.

![image](https://user-images.githubusercontent.com/4683319/218817635-5842df52-048f-40e3-bf58-e925f470f16a.png)
But after purchasing I still have 40 TP so the talent only cost me 15.

**Steps to reproduce**
1. Create a new character - in my case a Human Paladin
2. .level 12
3. Buy Mace Finesse 1, then 2.
4. End up with more TP than you should.

**Expected behavior**
Talents should cost exactly the amount of TP the UI displays.

- [ ] Purchasing the skill Melee Finesse enables the user to purchase talents they shouldn't be able to

![image](https://user-images.githubusercontent.com/4683319/218818422-5473da45-8019-4ab8-8e29-08bc5d54fec2.png)
After purchasing Melee Finesse on a new character - human pally again - who doesn't know how to use Swords yet I'm able to purchase Sword related talents despite the UI clearly showing I lack the requirements.

**Steps to reproduce**
1. Create a new character (Human Pally ftw)
2. .level 12
3. Buy Melee Finesse
4. Try to buy any of the now unlocked Sword related talents and be surprised it actually works

**Expected behavior**
Talents with unmet requirements should be unable to be purchased.

**Comment by GrenderG** [comment]
Second issue reported seems to be client side. Server doesn't let you actually train it (and closing & opening the window will make them disappear). Maybe there's some workaround we can do though...
