### ISSUE TITLE
Paladin randomly loses Devotion Aura 

### ISSUE THREAD

**Issue by mindphluxnet** [The-Alpha-Project/alpha-core#907]
**Describe the bug**
Devotion Aura does not have a duration. It is toggled active/inactive by casting it.

However, it happens frequently that Devotion Aura is removed without any indication in the combat log.

**Steps to reproduce**
1. have a Paladin with Devotion Aura
2. play normally for a while - usually this happens after a few minutes
3. watch as the Devotion Aura is lost

**Expected behavior**
As said before, Devotion Aura is a toggle, it should never fade on its own volition.

**Screenshots**
[Video](https://www.youtube.com/watch?v=fmMrUYgwI7s&t=120s)

**Comment by Fluglow** [comment]
Same issue as #463?

**Comment by mindphluxnet** [comment]
Yes

**Comment by mindphluxnet** [comment]
... and yep, it's still a display bug, just checked. An odd one, granted, but the armor bonus is still active even while the aura seems to be not.
