### ISSUE TITLE
TODO: Actually use vendor_id for vendor units

### ISSUE THREAD

**Issue by mindphluxnet** [The-Alpha-Project/alpha-core#942]
**Describe what needs to be implemented or enhanced**
Despite creature_template having a field "vendor_id" it's not being used. Instead, the "entry" field of the npc_vendor table needs to be equal to the "entry" field of creature_template, preventing me from implementing an unified vendor list for tradeskill vendors (which all have the same list).

**Expected end result**
The "vendor_id" of creature_template should be used to fetch entries from "npc_vendor" with the same entry id.

**Comment by mindphluxnet** [comment]
So that means unified trade vendors aren't possible unless that npc_vendor_template table can help us with that.

**Comment by GrenderG** [comment]
> So that means unified trade vendors aren't possible unless that npc_vendor_template table can help us with that.

Yep, that's what `npc_vendor_template` is for, don't worry. :+1:

**Comment by mindphluxnet** [comment]
Ah, good. I'll look into the table tomorrow and rewrite my queries accordingly.

**Comment by GrenderG** [comment]
> Ah, good. I'll look into the table tomorrow and rewrite my queries accordingly.

Structure is exactly the same, so only table name needs to be changed.
