### ISSUE TITLE
Runners flee after every hostile action

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#949]
**Describe the bug**
Mobs capable of "fleeing in fear" (called runners) start running away after every hostile action, regardless if it deals damage, misses or shouldn't aggro them in the first place. 

**Expected behavior**
Humanoid mobs (or other mobs that were hardcoded to do so) should start running away in fear when their health drops below 20%

**Video**
https://user-images.githubusercontent.com/111394734/224330432-00a0397a-edd5-4604-ad65-908687135368.mov

**Comment by mindphluxnet** [comment]
Fleeing is handled by scripts that trigger at specific health breakpoints. This has worked before, but some change must have regressed the feature.
