### ISSUE TITLE
Spell resistance of neutral spells

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#951]
- [x] Fix rneutral spell resistances

**Describe the bug**
Spells not resulting in any dmging effects have started being impossible to cast due to high resistance chances. I believe it may be connected with #949 since dmging spells work fine, however the server may think non-dmging spells can't trigger "runs away in fear" state, therefore they result in resists.

Regardless if it is connected to that topic, it doesn't work as intended.

Spells tested
- [Sleep](https://db.thealphaproject.eu/index.php?action=show_spell&id=726&filter=sleep&sort_order=Name_enUS&pos=4&max=12)
- [Shadow Word: Befuddle](https://db.thealphaproject.eu/index.php?action=show_spell&id=5704&filter=befuddle&sort_order=Name_enUS&pos=3&max=6)
- [Mind Vision](https://db.thealphaproject.eu/index.php?action=show_spell&id=2096&filter=Mind+Vision&sort_order=Name_enUS&pos=2&max=3)

- [ ]  Connect Mind Vision's channeling timer to its effect.

**Describe the bug**
Mind vision is treated as channeling even if it resists, bugging the cast bar for the duration of what Mind Vision should last for.
This makes the cast bar stay frozen until the supposed timer runs out.

**Video**
https://user-images.githubusercontent.com/111394734/224333664-47df317b-7e02-47b5-ab53-8d35bab954b6.mov
Second issue
https://user-images.githubusercontent.com/111394734/224335099-5ef60282-89b1-4526-96a2-0cd30c7cb31f.mov

**Comment by Fluglow** [comment]
The reason for the high resist chance is your relatively low Shadow Magic skill. The formulas can be found in `StatManager.get_spell_miss_result_against_self`, and I can elaborate on them if you're interested.

**Comment by GizzleBizzle** [comment]
No need, I understand perfectly and I can't believe I made this mistake.

I was doing most of my reporting before #333 was fixed and it didn't cross my mind that it could have been the reason.

I'll complete the first issue, the second one however is still active as it will always happen upon a resist.
