### ISSUE TITLE
TODO: Research Paxton Ganter <Brewing Trainer>

### ISSUE THREAD

**Issue by mindphluxnet** [The-Alpha-Project/alpha-core#964]
**Describe what needs to be implemented or enhanced**
Paxton Ganter <Brewing Trainer> is standing up to his knees in the ice on Iceflow Lake in Dun Morogh. He's also a fishing trainer.

Wowhead Classic lists him as "Fisherman" and the screenshot shows that while the position is likely correct the Z is too low:

https://www.wowhead.com/classic/npc=1700/paxton-ganter

Things to research:
- is this the correct position for Paxton?
- is he supposed to have the subtitle "Brewing Trainer"?

![image](https://user-images.githubusercontent.com/4683319/224672949-f0b0cb30-0bbe-4368-b8c0-fc1ba81cb9fd.png)

**Comment by devw4r** [comment]
https://crawler.thealphaproject.eu/mnt/crawler/media/Database/WDB/version_3494_creatures2.txt

**Comment by mindphluxnet** [comment]
Oh that's interesting! So the location *is* wrong and he was most likely not a fishing trainer either as I can't see a fishing rod in his hands.
