### ISSUE TITLE
Senator Barin Redstone likely has wrong gossip text

### ISSUE THREAD

**Issue by mindphluxnet** [The-Alpha-Project/alpha-core#967]
**Describe the bug**
Senator Barin Redstone greets the player like this:

![image](https://user-images.githubusercontent.com/4683319/224707781-ea9978c6-9dcf-48eb-a115-413f33ac69da.png)

He is a senator, not a fishing trainer.

**Comment by geo-tp** [comment]
![images_4871](https://user-images.githubusercontent.com/72315006/224802097-c8e098f4-514c-4259-9fcd-b5e097197ebc.jpg)

**Comment by geo-tp** [comment]
![images_4872](https://user-images.githubusercontent.com/72315006/224802626-6c7d4383-0235-4dee-9250-8359c809f99b.jpg)

**Comment by mindphluxnet** [comment]
Yeah, that part is identical. It's just the gossip text that's questionable.
