### ISSUE TITLE
TODO: Remove pet trainer duplicates

### ISSUE THREAD

**Issue by GizzleBizzle** [The-Alpha-Project/alpha-core#979]
Two of the pet trainers:
- [Bernie Heisten <Spider Trainer>](https://db.thealphaproject.eu/index.php?action=show_creature&id=3546&filter=trainer&sort_order=name&pos=39&max=446)
- [Bolyun <Spider Trainer>](https://db.thealphaproject.eu/index.php?action=show_creature&id=3698&filter=trainer&sort_order=name&pos=42&max=446)
Have double spawn points. one uncovered by @geo-tp, one from later patches.

**Bernie**
- **Spawn 1** Spawn ID 2703 / Guid 2308 is present in blasted lands (where there aren't any spiders), in a weird position behind nethergarde walls, some distance away from its gold mine.
- **Spawn 2** Spawn ID 400078 / Guid 18824 is standing by the road near Goldshire.

I believe that **Spawn 1** is in this spot because in later patches this NPC was changed to a food and drink vendor in Nethergarde. Since the Nethergarde keep hasn't been changed into its vanilla model yet, he is just standing in place that would eventually become his shop.

**However** both Spawn ID and Guid suggests, that **Spawn 1** is the original NPC, with his spawn-point not artificially added like **Spawn 2**

**Potential solution**
Remove the correct standing **Spawn 2**, move **Spawn 1** into **Spawn 2**'s former place.
This way we can have genuine mob in the correct place.

**Bolyun**
- **Spawn 1** - Spawn ID 32651/ Guid 30474 - This mob is sitting half-buried in a small hill, which is inside the tree, which is high up in inaccesible mountains of southern Ashenvale with an underground campfire to keep him company.
- **Spawn 2** - Spawn ID 400076 / Guid 36767 - This  npc is standing in Darnassus beside the bench with other npcs.

**Spawn 1** is there most likely due to similar situation Bernie had. This area will be eventually changed in the future and Bolyun will be moved there to serve as a general <pet trainer> according to WoWhead.
**Spawn 2**'s general location was confirmed by @geo-tp in #789 as Darnassus, so this one should be used.

**However**, distinguishing which spawn is the original one here is trickier, since both spawns have high Spawn ID and Guid. 

**Potential solution**
I would suggest doing the same thing as with Bernie's spawns - remove **Spawn 2** and move **Spawn 1** into **Spawn 2**'s former place, since lower IDs usually have a higher chance of being genuine. 

Still, the call is Yours.

If You decide to make use of my suggestion, I would also reccomend to take care of **Spawn 1**'s campfire, which is also buried inside inaccesible mountains.

I have archived its details in case we need to restore it, which is very unlikely, but still.
![Bolyan's campfire](https://user-images.githubusercontent.com/111394734/225470122-1c1e13dd-c032-452e-9eb9-a207b970e47f.png)

**Comment by mindphluxnet** [comment]
Is Bernie supposed to hold a bottle as spider trainer too? Makes little sense if you ask me.

**Comment by Fluglow** [comment]
Found a few more duplicates.
```
> SELECT entry, name, subname FROM creature_template ct INNER JOIN spawns_creatures sc ON ct.entry = sc.spawn_entry1 WHERE ct.subname LIKE "%Trainer%" AND sc.ignored != 1 GROUP BY ct.name HAVING COUNT(*) > 1 ORDER BY ct.entry;
+-------+-------------------+----------------+
| entry | name              | subname        |
+-------+-------------------+----------------+
|  2878 | Peria Lamenur     | Cat Trainer    |
|  2941 | Lanie Reed        | Spider Trainer |
|  3546 | Bernie Heisten    | Spider Trainer |
|  3689 | Laer Stepperunner | Wolf Trainer   |
|  3698 | Bolyun            | Spider Trainer |
+-------+-------------------+----------------+

**Comment by mindphluxnet** [comment]
I've handled them all now.

**Comment by geo-tp** [comment]
![Capture d’écran_2023-03-16_15-08-27](https://user-images.githubusercontent.com/72315006/225643397-69833124-4fc9-4904-ba2d-33d694587a2a.png)

Peria Lamenur should be double spawned

**Comment by mindphluxnet** [comment]
Okay, I'll respawn her at the airstrip.
