### ISSUE TITLE
TODO: Hearthglen (Western Plaguelands) needs a database do-over

### ISSUE THREAD

**Issue by mindphluxnet** [The-Alpha-Project/alpha-core#983]
**Describe what needs to be implemented or enhanced**
In vanilla, Hearthglen was an elite area full of Scarlet Crusade dudes. In 0.5.3 it was very likely completely devoid of life as Western Plaguelands were opened almost a *year* later in patch 0.10. Still, our data has all mobs spawned and correctly named, although everyone's running around shane cubed. 

There are also several game objects - including chests - spawned there which make no sense in the same context. They are shane cubes as well. The chests are either empty or contain unfinished loot.

Unfortunately we don't have any pictures from alpha (or even beta) showing Hearthglen, but I assume that's simply because there was nothing of interest there to find until shortly before retail release.

**Expected end result**
My personal idea would be to despawn all of this as it's borderline impossible to have been present in 0.5.3, but of course I can't prove anything. Looking for feedback on how to handle this.

**Comment by geo-tp** [comment]
Entries of these mobs is around 1800-1900. Even if it's in WPL, Hearthglen seems to be kind of an early zone.

![Capture d’écran_2023-03-18_14-45-18](https://user-images.githubusercontent.com/72315006/226110215-9cbfe36e-977e-43ba-b0b9-802fa0b82ab7.png)


We can see here, there are a lot of unused scarlet display_id : 
![Capture d’écran_2023-03-18_14-47-31](https://user-images.githubusercontent.com/72315006/226110113-ddba08b6-8075-4db7-936c-298c29a58c5c.png)

![Capture d’écran_2023-03-18_14-46-10](https://user-images.githubusercontent.com/72315006/226110115-2f1d2ac7-b91a-4a18-bdd4-c975508b3739.png)
![Capture d’écran_2023-03-18_14-47-59](https://user-images.githubusercontent.com/72315006/226110118-b424d3fa-dfa6-4864-9fdb-ef58d6c55721.png)

It's even possible that Tirion should stand in Hearthglen area in 0.5.3

**Comment by geo-tp** [comment]
Based on vanilla display id and unused ones, guesses here : 

1826 Scarlet Mage :  1640 (male) & 1641 (female)
1827 Scarlet Sentinel : 2467 & 2478
1831 Scarlet hunter :  1023
1832 Scarlet Magus : 2039
1833 Scarlet Knight :  1025 & 2460
1834 Scarlet Paladin : 1025 & 2460
1835 Scarlet Invoker ; 1640 & 1641
1836 Scarlet Cavalier : 1025 & 2460
1837 Scarlet Judge : 1025 & 2460
1838 Scarlet Interrogator : 1611 & 1612
1839 Scarlet High Clerist : 1613 & 1614
1840 Grand Inquisitor : 1641
1841 Scarlet executionner : 2044
1843 Foreman Jerris : 1611
1844 Foreman Marcrid : 1611
1845 High Protected Tarsen : 1025
1846 High Protected Lorik : 1025
1883 Scarlet Worker : 1617 & 1615 (remove display_id 3 & 4)

It will be the first time that we see missing display human models resolved by anything else than old human models, so this could be totally wrong.

Don't know if @GrenderG  wants to wait for evidence (it could never came) or use guesses for now.

**Comment by GrenderG** [comment]
I think we can probably go with these :arrow_up:  until / if we find more evidences.

**Comment by mindphluxnet** [comment]
Okay, I'll work on this tomorrow.

**Comment by mindphluxnet** [comment]
@geo-tp Scarlet Smith is missing from your list, any suggestion?

**Comment by geo-tp** [comment]
1842 Highlord Taelan Fordring 1025
1884 scarlet lumberjack  2520 & 2521
1885 scarlet smith 2465 & 2476

There are guesses as well.
