### ISSUE TITLE
TODO:  Move Durdek Karrin Bear Trainer

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#984]
2881 Durdek Karrin is actually located inside basement at Misty Pine Refuge. It not makes sense for a pet trainer to be indoor. There is no other example of indoor pet trainer.

He was moved some month ago, so its actual location is not blizzlike.

![Capture d’écran_2023-03-16_19-46-30](https://user-images.githubusercontent.com/72315006/225722600-82cb0e58-3fab-4729-ad83-e1097e3c3373.png)

Expected Results : 
2881 Durdek Karrin should stand in front of Misty Pine Refuge

**Comment by mindphluxnet** [comment]
"In front of" Misty Pine Refuge is a bit vague. I couldn't find a single screenshot of his location, any ideas?
