### ISSUE TITLE
TODO:  Gabrielle Chase <Food & Drink> should be located in SW

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#985]
**Describe what needs to be implemented or enhanced**
3298 Gabrielle Chase is actually located in a unfinished zone, she should stand in Stormwind

![2004-01-15-19-43-12](https://user-images.githubusercontent.com/72315006/225731954-3dcaf88c-8879-4ff5-ab45-de24cc24ef69.jpg)

https://db.thealphaproject.eu/index.php?action=show_creature&id=3298&sort_order=name&filter_column=display_id1&filter_compare=equals&filter_value=1442&pos=1&max=1

I remember moving Jen Langston thinking it was her on the screenshot, the display_ids are very close(https://displayidbrowser.azurewebsites.net/Human-female). Gabrielle should use Jen Langston's current position

Jen Langston position should be reverted to vanilla one (it's not so needed now that waypoint works, but it will be better)

**Expected end result**
3298 Gabrielle Chase should stand at Jen Langston actual position.
3626 Jen Langston position should be reverted to vanilla one.

**Comment by devw4r** [comment]
Please make sure to check movement tables when moving units, I remember that specific npc from the screenshot trying to walk through the wall behind her endlessly.

**Comment by mindphluxnet** [comment]
Gabrielle doesn't move, Jen does, and from what I could see in testing she does just fine.
