### ISSUE TITLE
TODO: Change missing herbs display id to this generic model

### ISSUE THREAD

**Issue by geo-tp** [The-Alpha-Project/alpha-core#992]
**Describe what needs to be implemented or enhanced**

We know that some herbs are for sure part of 0.5.3 but don't have a unique model yet.

For this case, we should use this  placeholder :

![images_6206](https://user-images.githubusercontent.com/72315006/226074696-96c6bf77-bfa7-4d34-91d7-6bae7ee83d5d.jpg)
![aout2003-04](https://user-images.githubusercontent.com/72315006/226074699-8c597fda-1a64-42df-af9e-0720eb68bf0e.jpg)
![Capture d’écran_2023-03-17_21-30-31](https://user-images.githubusercontent.com/72315006/226074705-a7c8549c-32c1-4d17-9784-ab62391054f5.png)

**Expected end result**
Missing herbs display_id should use placeholder model

**Comment by mindphluxnet** [comment]
For reference the display_id for the berry bush is 28.

**Comment by mindphluxnet** [comment]
Done with PR #1023:

- Wintersbite
- Khadgar's Whisker
- Firebloom
