### ISSUE TITLE
Client crash fighting a Black Slime

### ISSUE THREAD

**Issue by mindphluxnet** [The-Alpha-Project/alpha-core#994]
**Describe the bug**
Client crash as seen in the screenshot a few hits into fighting the slime.

**Steps to reproduce**
1. .port -3951.43 -2716.34 27.2922 0 (approximate)
2. find a Black Slime and attack it
3. boom

**Expected behavior**
Shouldn't crash. Seems to be an animation issue maybe?

**Screenshots**
![image](https://user-images.githubusercontent.com/4683319/226113588-8d9ba7d7-686d-4097-a60b-86351cd9f9cd.png)

**Comment by devw4r** [comment]
Try checking which spell the creature is casting (causing the crash) and test adding it to:

https://github.com/The-Alpha-Project/alpha-core/blob/master/game/world/managers/objects/spell/ExtendedSpellData.py#L244

**Comment by mindphluxnet** [comment]
That did the trick, I added it to my current PR.
