### ISSUE TITLE
OOC scripts disable quest givers almost completely

### ISSUE THREAD

**Issue by mindphluxnet** [The-Alpha-Project/alpha-core#995]
**Describe the bug**
I've encountered this in Dun Modr where a group of dwarves - among them several quest givers - lays siege to the enemy. Three of them have repeating OOC events to have them shoot/throw dynamite and if they are a quest giver their flag gets turned off as soon as the event goes into its cooldown period. In reality this means they are basically non-interactable as the scripts are extremely short (one action).

This seems to be because the ScriptHandler turns off the NPC_FLAG_QUESTGIVER while the script is *not* started which is 99.9% of the time for OOC scripts.

**Steps to reproduce**
1. .level 22
2. .tel dunmodr
3. watch the NPCs turn their quest sign on and off

**Expected behavior**
OOC events should not make quest NPCs non-interactive, especially if the associated script runs for only a fraction of a second.

**Screenshots**
Note, the video below already includes my fixes for their spells, without them they just stand there doing nothing.

https://user-images.githubusercontent.com/4683319/226143419-445d4335-07bf-43a6-b50c-3a6e52309327.mp4

**Comment by devw4r** [comment]
![image](https://user-images.githubusercontent.com/108442943/226143869-e813e997-f303-42bc-a29d-3bad71d15151.png)

Just get rid of the code that intereacts with NPC_FLAG_QUESTGIVER, we'll deal with that later. Else you could try to improve upon it, calculate the complete script time inside Script() ctor given its initial delay plus nested commands delays, and only trigger this behavior if its greater than X amount of time.

**Comment by mindphluxnet** [comment]
It's not the script delay, it's the time it sits idle while waiting for the "repeat after" timer to expire. It's sadly not that simple ...

**Comment by mindphluxnet** [comment]
Actually scripts can disable/enable NPC flags themselves if needed so that's likely the better option.
